### ISSUE TITLE
`scala-mode2` is no longer available in MELPA

### ISSUE THREAD

**Issue by inflation** [bbatsov/prelude#1000]
There is only `scala-mode` there.

From the [project repo](https://github.com/hvesalai/scala-mode2), the latest commit is 11 months ago. I can say that it is not active now.

Also, `ensime` is an exceptional package to use together with `scala-mode`, which I think is under very active development.

BTW, I modified the `prelude-scala.el` to replace the package, should I make a pull request? Thanks.

**Comment by bbatsov** [comment]
> BTW, I modified the prelude-scala.el to replace the package, should I make a pull request? Thanks.

Sure.
