### ISSUE TITLE
Create a Prelude logo

### ISSUE THREAD

**Issue by bbatsov** [bbatsov/prelude#1003]
It'd be really nice if the project had some cool logo (like Spacemacs), but unfortunately I can't create one myself (drawing is not my strong suit). I'd really appreciate it, if someone tackled this.

**Comment by JavChz** [comment]
I hope this help (even if i'm more like a vim person to be honest =P, but prelude makes me like emacs a little more).

The idea it's have for icon a pentagram-like-thing... but at the same the shape of indented lines of code; and a curly brace that usually works for music and programing. 

![prelude-a](https://cloud.githubusercontent.com/assets/13250549/15626679/5a2226e6-2488-11e6-8e11-71cd57a6ae4d.png)

Dark version:

![prelude-b](https://cloud.githubusercontent.com/assets/13250549/15626681/5e64b674-2488-11e6-8661-3132bc7bdd17.png)

Was something quick, but I hope you like it. In case it used, please let me know so I can put it in my portafolio (that will not be a problem right?), and upload the vectorial SVG too. 

BTW this proposal of logo use the font "Raleway", so the font license will not be a problem (OFL).

**Comment by lipanXJ** [comment]
@JavChz  The light one is good,it'd better to use another color for "PRELUDE"??(just a guess)
The dark one,i am sorry to say that it made me remember "Spacemacs" ,because i notice "Spacemacs" have a lot of purple.

**Comment by bbatsov** [comment]
@JavChz Thanks for those logos. I'll have to think about them for a bit (and I'm wondering if someone else won't submit some ideas as well). 

In general my concerns with this visual direction are not big, but there are couple.
Shouldn't the logo share a bit of visual identity with Emacs itself? Or a Honda Prelude? ;-)

**Comment by dmh43** [comment]
Cute! But I personally think parens would be better suited that curly braces. This is Emacs, after all :)
