### ISSUE TITLE
C-p s s went from helm-projectile-ag to projectile-ag in recent change

### ISSUE THREAD

**Issue by lvh** [bbatsov/prelude#1014]
Not entirely sure where this happened (or if it's even a prelude change) but since a recent update I no longer get my fancy helm autocomplete for ag. I can attempt to rebind this, but I thought this was something I got automagically through prelude, so I wanted to check if this is intentional or something messed up about my setup. I have `(require 'prelude-helm)` and `(require 'prelude-helm-everywhere)` in my `prelude-modules.el`.

`C-h f helm-projectile-ag` shows:

> helm-projectile-ag is an interactive autoloaded compiled Lisp function in
> ‘helm-projectile.el’.
> 
> It is bound to C-c p <remap> <projectile-ag>, s-p <remap> <projectile-ag>.
> 
> (helm-projectile-ag &optional OPTIONS)
> 
> Helm version of projectile-ag.
> 
> [back]
> 

`C-h f projectile-ag` shows:

> projectile-ag is an interactive autoloaded compiled Lisp function in
> ‘projectile.el’.
> 
> It is bound to C-c p s s, s-p s s, <menu-bar> <tools> <Projectile> <Search in
> project (ag)>.
> 
> (projectile-ag SEARCH-TERM &optional ARG)
> 
> Run an ag search with SEARCH-TERM in the project.
> 
> With an optional prefix argument ARG SEARCH-TERM is interpreted as a
> regular expression.
> 
> [back]

helm still works for `M-x`, `C-x b` et cetera. The projectile completion system is appropriately set:

> projectile-completion-system is a variable defined in ‘projectile.el’.
> Its value is ‘helm’
> Original value was ido
> 
> Documentation:
> The completion system to be used by Projectile.
> 
> You can customize this variable.

Helm works properly for switching projects or searching files (so, <kbd>C-p p</kbd>; <kbd>C-p f</kbd>). It is only disabled for <kbd>C-p s s</kbd> and <kbd>C-p s g</kbd>; i.e. they are bound to `projectile-ag` and `projectile-grep` respectively, and I was  expecting them to be bound to their `helm-` variants. 

Manually calling `helm-projectile-on` does not help; all of the other helm projectile continues to work as expected but -ag and -grep do not.

(I can fix this by just adding some global bindings, but this seems like maybe something I should report? Is this supposed to work/expected change?)

**Comment by lvh** [comment]
(I am also volunteering to help find that change if this was intentional; but I guess I better check first :))

**Comment by xitkov** [comment]
This is fixed for me after upgrading helm and projectile related packages.

**Comment by lvh** [comment]
Confirmed :)
