### ISSUE TITLE
prelude-update is not working

### ISSUE THREAD

**Issue by dball** [bbatsov/prelude#1020]
When I run `prelude-update`:

> Do you want to update Prelude? (y or n) y
Updating installed packages...
Contacting host: melpa.org:443
url-insert-file-contents: https://melpa.org/packages/zenburn-theme-20160327.520.el: Not found

**Comment by xitkov** [comment]
Please try `prelude-update` after running `package-refresh-contents` and see if it helps.

**Comment by dball** [comment]
iirc I had done that to no effect, but I've since manually updated my whole prelude
