### ISSUE TITLE
smartparens-global-strict-mode   is not working.

### ISSUE THREAD

**Issue by rushpixy** [bbatsov/prelude#1023]
A-x  smartparens-global-strict-mode      is   right.    (xxxx )|xxxx)       backspace  will  delete  the middle  ).
but  add     (smartparens-global-strict-mode -1)   in .el file  personal forder.  It's not working.

**Comment by bbatsov** [comment]
You should report this to smartparen's issue tracker, as it's not a Prelude issue.
