### ISSUE TITLE
eldoc error needs an inferior python process running

### ISSUE THREAD

**Issue by kxxoling** [bbatsov/prelude#1026]
When I enabled prelude-company, it also requires a running python process. Isn't added to prelude-python? What should I do to fix this issue? I do not want to start a useless python console every time.

**Comment by rpgdude** [comment]
Same problem here.

**Comment by bingtangben** [comment]
I have the same problem! 

Now I must run M+run python command to fix it. But I wanna a better way to solve it.

@bbatsov has any suggestions?

**Comment by ycopin** [comment]
I have the further issue that when I "M+run-python", emacs will just freeze, with the (probable) error msg:
```
eldoc error: (wrong-type-argument arrayp nil)
```

**Comment by shaunvxc** [comment]
Bump: having the same issues.  Anyone have a fix for this yet?

**Comment by ycopin** [comment]
Bump?

**Comment by mien** [comment]
I have the same issue "eldoc error: (error Eldoc needs an inferior Python process running)"

**Comment by ycopin** [comment]
Bump? Using native emacs 24.5 on Ubuntu 16.04.
