### ISSUE TITLE
For beginners ??? Not so sure...

### ISSUE THREAD

**Issue by Arcanum-XIII** [bbatsov/prelude#103]
Hi, 

General issue here, so not bug related... I'm here because I was thinking this config file will help me with my first step in emacs — and ease my way into lisp. 
The install is easy —can't deny it. But the configuration after is, for a beginner, very hard — without event speaking about the strange behavior I got with my MacOS X key — like the alt key not working anymore, and so, no more extended character (easily change with the (setq mac-option-modifier 'alt) line but you don't know how much time it took me to find those keymodifier on the emacswiki, understand it, and change it). Now I'm stuck trying to install and configure slime — I finally found that I have to install it from quicklisp, so I've done that within SBCL. After that, another quest to find that I was to launch (M-X prelude-load-common-lisp-slime) so M-X slime can at last be use... but now I'm stuck with "no such find or directory 'ccl'"... I know it's because the config file is, somewhere, telling it to use CCL and not SBCL, and there's probably a command inside prelude to change that, but... where's the doc ? 
Am I missing something ? 

My beginning with vim were not THAT hard — and it was frustrating at the time. Maybe I've misunderstood the point of this "sane" config file altogether ? Installing slime by dlw it, on a bare emacs was far easier !

Oh, and it seem aquamacs doesn't like prelude a lot. Lot of strange behavior with the zenburn theme for example — but well, aquamacs feels strange ;)

**Comment by bigos** [comment]
I use SBCL, I prefer it over CCL and was disappointed when my favourite Lisp suddenly stopped working.

After adding following line to my personal.el everything works. So I hope Prelude updates will not have surprises like this one.

(setq slime-default-lisp 'sbcl)
