### ISSUE TITLE
Fetch packages list before prelude-update in prelude-update

### ISSUE THREAD

**Issue by MatthewRock** [bbatsov/prelude#1032]
Hi!

I sometimes encounter a problem where my `prelude-update` fails, because after connecting to melpa it can't find some package(all I get is somelongpackagename: not found). This can be easily fixed by doing M-x package-list-packages, which fetches latest packages info. I don't really know what's going on under the hood, but I believe some funtion is called that updates known packages list, allowing for fetch to succeed.

It would be nice if such an option was already built-in in `prelude-update`, or if there was some other command, e.g. `prelude-update-and-fetch`, so that confusion that arises would be avoided.

**Comment by seban** [comment]
There is also `prelude-update-packages` which updates packages from prelude-packages defined in `core/prelude-packages.el` (all or specified one only). `prelude-update` basically do only `git pull` and recompile init.
I think there can be defined some function which will be performing `package-refresh-contents`, `perlude-update` and `prelude-update-packages`.
