### ISSUE TITLE
support planned for Emacs v25?

### ISSUE THREAD

**Issue by khaije1** [bbatsov/prelude#1033]

**Comment by bbatsov** [comment]
Prelude works just fine on Emacs 25.

**Comment by yu-yuxuan** [comment]
@bbatsov 
Today I update packages by using `M-x package-list-package`
It shows following packages aren't needed and asks me delete it

> which-key, vkill, test-simple, slime, realgud, mediawiki, macrostep, lua-mode, lodgeit, loc-changes, load-relative, list-utils, link, key-chord, jtags, jdee,\
>  javadoc-lookup, java-snippets, imenu-anywhere, hide-comnt, helm-dictionary, ggtags, exec-path-from-shell, elfeed, dictionary, crux, connection, company-c-he\
> aders, bash-completion, proceed?

Then when I restart
It shows error.

> Debugger entered--Lisp error: (error "Unable to activate package ‘slime’.
> Required package ‘macrostep-0.9’ is unavailable")
>   signal(error ("Unable to activate package ‘slime’.\nRequired package ‘macrostep-0.9’ is unavailable"))
>   error("Unable to activate package `%s'.\nRequired package `%s-%s' is unavailable" slime macrostep "0.9")
>   package-activate-1([cl-struct-package-desc slime (20160612 1532) "Superior Lisp Interaction Mode for Emacs" ((cl-lib (0 5)) (macrostep (0 9))) nil nil "/Us$
>   package-activate(slime)
>   package-initialize()
>   eval-buffer(#<buffer  *load*> nil "/Users/yuyuxuan/.emacs.d/init.el" nil t)  ; Reading at buffer position 1444
>   load-with-code-conversion("/Users/yuyuxuan/.emacs.d/init.el" "/Users/yuyuxuan/.emacs.d/init.el" t t)
>   load("/Users/yuyuxuan/.emacs.d/init" t t)
>   #[0 "^H\205\266^@     \306=\203^Q^@\307^H\310Q\202?^@ \311=\204^^^@\307^H\312Q\202?^@\313\307\314\315#\203*^@\316\202?^@\313\307\314\317#\203>^@\320\321\32$
>   command-line()
>   normal-top-level()

**Comment by khaije1** [comment]
@bbatsov Thanks for that point of clarification!

Prelude is always the first project I recommend to people interested in Emacs and since much of the documentation still references Emacs v24.x I just wanted to make sure that the support commitment does inded extend to Emacs v25.

Kind regards.

**Comment by bbatsov** [comment]
Guess I'll have to update the documentation. :-)
