### ISSUE TITLE
ediff-files didn't highlight fine diffs in line for emacs -daemon

### ISSUE THREAD

**Issue by sunlin7** [bbatsov/prelude#1036]
Hi,

I met the issue that prelude will make ediff no fine diffs show in line when the emacs run as daemon and start ediff from emacsclient GUI.
Here is the reproduce steps,

```
$echo 'hello world' > ~/a
$echo 'hello x world' > ~/b
$emacs -daemon
$emacsclient -c -e '(ediff-files "~/a" "~/b")'
```

Then press `n` to move highlight to the line, there is no fine diffs (need press `*` to show the find diffs, which will made "x" highlight in line.)

It's OK without prelude, 

```
$echo 'hello world' > ~/a
$echo 'hello x world' > ~/b
$emacs -q -daemon # without prelude
$emacsclient -c -e '(ediff-files "~/a" "~/b")'
```

then press `n`, the fine diffs will show in line automatically, the " x " will highlighted in the middle of the line.

**Comment by sunlin7** [comment]
hi All, 

Finally, I got the solution, just use the `setq-default` to set the `ediff-window-setup-function`, then issue is gone.
But don't know why it's happened. 
Dose anyone can merge this patch? 
```
diff --git a/core/prelude-editor.el b/core/prelude-editor.el
index d6f5917..99ce3e6 100644
--- a/core/prelude-editor.el
+++ b/core/prelude-editor.el
@@ -285,8 +285,8 @@ The body of the advice is in BODY."
 (require 'dired-x)

 ;; ediff - don't start another frame
-(require 'ediff)
-(setq ediff-window-setup-function 'ediff-setup-windows-plain)
+;; (require 'ediff)
+(setq-default ediff-window-setup-function 'ediff-setup-windows-plain)

 ;; clean up obsolete buffers automatically
 (require 'midnight)
```

**Comment by sunlin7** [comment]
@bbatsov @genexp @lukerandall 

Dose anyone can help to review the patch and apply it ? 
Thank you so much.

**Comment by bbatsov** [comment]
It's best to convert your patch into a PR.

**Comment by sunlin7** [comment]
@bbatsov 
Okay, create a new PR.

Thank you.

**Comment by sunlin7** [comment]
The RP is https://github.com/bbatsov/prelude/pull/1111.
