### ISSUE TITLE
Prelude doesn't start with emacs 26

### ISSUE THREAD

**Issue by ewollesen** [bbatsov/prelude#1038]
So I know prelude is for emacs 25, but I figure 26 will eventually be supported, so I thought I'd share my experience. I got emacs 26 built from the ubuntu elisp PPA on xenial. When I start it up with `--debug-init`, I see this in `*Messages*`.

``````
Prelude is powering up... Be patient, Master ericw!
Loading personal configuration files in /home/ericw/.emacs.d/personal/preload...
Loading Prelude’s core...
insert-file-contents: Recursive load: "/usr/share/emacs/26.0.50/lisp/jka-compr.el.gz", "/usr/share/emacs/26.0.50/l\
isp/emacs-lisp/debug.el.gz", "/usr/share/emacs/26.0.50/lisp/jka-compr.el.gz", "/usr/share/emacs/26.0.50/lisp/jka-c\
ompr.el.gz", "/usr/share/emacs/26.0.50/lisp/jka-compr.el.gz", "/usr/share/emacs/26.0.50/lisp/jka-compr.el.gz", "/u\
sr/share/emacs/26.0.50/lisp/emacs-lisp/cl.el.gz", "/home/ericw/.emacs.d/core/prelude-packages.el", "/home/ericw/.e\
macs.d/init.el"
Error in post-command-hook (eldoc-schedule-timer): (error "Recursive load" "/usr/share/emacs/26.0.50/lisp/jka-comp\
 r.el.gz" "/usr/share/emacs/26.0.50/lisp/jka-compr.el.gz" "/usr/share/emacs/26.0.50/lisp/jka-compr.el.gz" "/usr/sha\
re/emacs/26.0.50/lisp/jka-compr.el.gz" "/usr/share/emacs/26.0.50/lisp/jka-compr.el.gz" "/usr/share/emacs/26.0.50/l\
isp/calendar/time-date.el.gz")```
``````

I'm using the latest code in master, `b05126e4`.

Thanks!

**Comment by bbatsov** [comment]
Hmm, that's really odd. I don't even know what this `jka` package is. Guess some requires got changed in 26 or something like this.

**Comment by hut8** [comment]
Seems to load fine in 26.0.50.2

**Comment by ewollesen** [comment]
I confirm, fixed for me as well. I had to remove `~/.emacs.d/savefile/recentf` as well, but that's unrelated.

**Comment by suutari-ai** [comment]
I had similar problem with Ubuntu 16.04 with Emacs 25.3.50.2 from this PPA: https://launchpad.net/~ubuntu-elisp/+archive/ubuntu/ppa

It seems to be caused by `emacs25-el` package. Removing that package helped.
