### ISSUE TITLE
OSX Sierra compatability 

### ISSUE THREAD

**Issue by brettywhite** [bbatsov/prelude#1040]
Hello,

This may be me just being an emacs n00b, but it seems on emacs 24 on MacOS sierra, in org mode, python and LaTeX's paths dont seem to be correct. I know that in the newer MacOS's that the tex path has changed to /Library/TeX/texbin. Not sure on why python isnt working. 

Previously I could load python with just:
(org-babel-do-load-languages
      'org-babel-load-languages '((latex . t)(python . t) (R . t)))

After installing prelude i am getting the no org-babel-execute function for python. For LaTeX, its saying it cant find pdflatex, which is more than likely associated with the different path as stated above.

Apologies if this is just my naivety with emacs, of if the newer MacOS actually did break some things.

Thanks

**Comment by brettywhite** [comment]
ok, so adding
(org-babel-do-load-languages
'org-babel-load-languages '((latex . t)(python . t) (R . t)))
to the end of the init.el file allows python to work again, but pdflatex still isnt found:
"/bin/bash: pdflatex: command not found [3 times]"

**Comment by brettywhite** [comment]
ok i answered my own question, adding:

(setenv "PATH" (concat (getenv "PATH") ":/Library/TeX/texbin"))
(org-babel-do-load-languages
      'org-babel-load-languages '((latex . t)(python . t) (R . t)))

to the end of the init.el file fixed the pdflatex and no org-babel-execute python errors for me. I will leave this open in case it actually is an issue and not just me for other mac users. Many thanks for this excellent lib.

**Comment by dareno** [comment]
This fixed the same python error for me on the following versions:

- macOS Catalina Version 10.15.7
- prelude 3a31d58 - Fri, 25 Sep 2020 14:59:08 +0300
