### ISSUE TITLE
Unset shift+up/down/left/right from doing windmove key bindings

### ISSUE THREAD

**Issue by hisnawi** [bbatsov/prelude#1068]
Prelude enable the default key bindings for windmove, but I use shift+direction to select text.

I can't find a peaceful way to unset this binding.

Doing this:

    (global-unset-key (vector (list 'shift 'left)))

    (global-unset-key (vector (list 'shift 'right)))

    (global-unset-key (vector (list 'shift 'up)))

    (global-unset-key (vector (list 'shift 'down)))

Works but it breaks shift+M+direction for some reason as it ignores the shift.

**Comment by KarlFish** [comment]
Comment out lines 150 and 151 in `.emacs.d/core/prelude-editor.el` 

```
;; use shift + arrow keys to switch between visible buffers
(require 'windmove)                         ;; 150
(windmove-default-keybindings)      ;; 151
```

I uesed describe-key (bound to `C-h k`) to find Shift+direction was bound to windmove-up. Then I searched `.emacs.d` for windmove-up which didn't find anything, but searching for windmove found these lines.
