### ISSUE TITLE
[modules/prelude-programming.el - line 62] sp-pair invokes debugger

### ISSUE THREAD

**Issue by rprimus** [bbatsov/prelude#1075]
Sat Mar 11 20:23:10 GMT 2017

FYI:

```elisp
(sp-pair "{" nil :post-handlers
         '(((lambda (&rest _ignored)
              (crux-smart-open-line-above)) "RET")))
```
invokes the debugger.

Please refer to [this gist](https://gist.github.com/rprimus/4a904c2d4b621036d8e45238f27c45d4) for the debugger trace.

This may be related to the change in smartparens-20170311.548 referred to in  [this issue](https://github.com/Fuco1/smartparens/issues/718).

**Comment by Fuco1** [comment]
Nope, this is a different issue and I know exactly where it is :) I turned on lexical-binding today so there is going to be quite a lot of issues I haven't catched I'm sure.

Better stay away from master if you can't afford broken setup.  But of course having these reports is awesome, so thanks for taking the hit for me :)  Expect this to be fixed soon.

**Comment by Fuco1** [comment]
Should be fixed now, sorry for the troubles.  Melpa will probably build this some time in the next three hours.

**Comment by bbatsov** [comment]
OK, guess I can close this.
