### ISSUE TITLE
init error

### ISSUE THREAD

**Issue by jaydenhe** [bbatsov/prelude#1077]
Debugger entered--Lisp error: (void-function wrap)
  (wrap insert autoskip navigate)
  eval((wrap insert autoskip navigate))
  sp-pair("{" nil :post-handlers (((lambda (&rest _ignored) (crux-smart-open-line-above)) "RET"))$
  eval-buffer(#<buffer  *load*-293413> nil "/root/.emacs.d/modules/prelude-programming.el" nil t)$
  load-with-code-conversion("/root/.emacs.d/modules/prelude-programming.el" "/root/.emacs.d/modul$
  require(prelude-programming)
  eval-buffer(#<buffer  *load*-367170> nil "/root/.emacs.d/modules/prelude-c.el" nil t)  ; Readin$
  load-with-code-conversion("/root/.emacs.d/modules/prelude-c.el" "/root/.emacs.d/modules/prelude$
  require(prelude-c)
  eval-buffer(#<buffer  *load*-948761> nil "/root/.emacs.d/prelude-modules.el" nil t)  ; Reading $
  load-with-code-conversion("/root/.emacs.d/prelude-modules.el" "/root/.emacs.d/prelude-modules.e$
  load("/root/.emacs.d/prelude-modules.el")
  (if (file-exists-p prelude-modules-file) (load prelude-modules-file) (message "Missing modules $
  eval-buffer(#<buffer  *load*> nil "/root/.emacs.d/init.el" nil t)  ; Reading at buffer position$
  load-with-code-conversion("/root/.emacs.d/init.el" "/root/.emacs.d/init.el" t t)
  load("/root/.emacs.d/init" t t)
  #[0 "^H\205\266^@     \306=\203^Q^@\307^H\310Q\202?^@ \311=\204^^^@\307^H\312Q\202?^@\313\307\3$

**Comment by bbatsov** [comment]
See #1075.
