### ISSUE TITLE
`xx` key-chords binding don't show helm with `prelude-helm-everywhere` activated

### ISSUE THREAD

**Issue by sadhu89** [bbatsov/prelude#1080]
Hi everyone! `key-chords` and `prelude-helm-everywhere` are amazing, but I can not make them work together when I press `xx` for the `execute-extended-command`. (When I use M-x it shows helm)

**Comment by am** [comment]
Same here, using emacs `25.2.2` on osx

**Comment by am** [comment]
@sadhu89 `xx` key-chord [binds to](https://github.com/bbatsov/prelude/blob/e0ca7c700389e70df457177ea75b0936dbe254e0/modules/prelude-key-chord.el#L43) `execute-extended-command`.
In your config file change this to:
```elisp
(key-chord-define-global "xx" 'helm-M-x)
```
