### ISSUE TITLE
how to add colorful comment in ruby mode

### ISSUE THREAD

**Issue by earthIsAPrisonIfYouNotAwareItCanNotOut** [bbatsov/prelude#1085]
sometimes I need many colors in comment and annotation in order to distinguish between important information and others
for instance:
<pre><code>
## the comment start with "##" should be red
# "the string in double quotes" should be green

</code></pre>

**Comment by KarlFish** [comment]
@earthIsAPrisonIfYouNotAwareItCanNotOut Well, I've got an ugly, but workable solution.

Add the following code to any file in `~/.emacs.d/personal/`

    (make-face 'font-lock-important-comment-face)
    (set-face-foreground 'font-lock-important-comment-face "Red")
    (font-lock-add-keywords 'ruby-mode
                            '(("^## .*$" . 'font-lock-important-comment-face)))
    
    (defalias 'my/ruby-important-comment-propertize
      (syntax-propertize-rules ("\\(^## .*$\\)" (1 "."))))
    
    (add-hook 'ruby-mode-hook
              (lambda ()
                (add-function :before (local 'syntax-propertize-function)
                              #'my/ruby-important-comment-propertize)))


When I open `temp.ru` I get:

    ################
    ### green
    ##green
              ## green
    ## VERY VERY BRIGHT RED
    # green
    
    " mutli-line-string
    ## string-colored - not red
    "


The `"Red"` can be a hex code, so something like `"#BF2F2F"` would be a more comfortable red.
