### ISSUE TITLE
Ruby editing configuration should be consistent with Rubocop Style/FirstParameterIndentation

### ISSUE THREAD

**Issue by twhaples** [bbatsov/prelude#1086]
My organisation uses RuboCop to enforce a consistent code style. While there are quite a few customisations, many of the settings are pretty ordinary. For instance, there is no override to the defaults for `Style/FirstParameterIndentation` ("Indent the first parameter one step more than the start of the previous line.")

This means that you are expected to indent code like

```
    expect(some_class).
      to receive(:method).with(
        arg1: :val1,
        date: date,
        info: "some info",
      ).and_return(mock_class)


    expect(some_class).
      to_not receive(:method).with(
        arg1: :val1,
     )
```
with a simple 2 spaces per new level of indentation.

I use Emacs `(GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)` with emacs-prelude as recent as 7667ee4ba0165c8c6e8b3a156e8fb5e9933601b6. 

By adjusting configuration with `(setq ruby-deep-indent-paren nil)` and `(setq ruby-deep-arglist nil)` you can get as close as
```
    expect(some_class).
      to receive(:method).with(
           arg1: :val1,
           date: date,
           info: "some info",
         ).and_return(mock_class)


        expect(some_class).
          to_not receive(:method).with(
                   arg1: :val1,
                 ).and_return(:value)
```
Using rubocop-mode, I can fix this, producing errors like

```
file_spec.rb:27:16: C: [Corrected] Style/FirstParameterIndentation: Indent the first parameter one step more than the start of the previous line.
file_spec.rb:30:14: C: [Corrected] Style/ClosingParenthesisIndentation: Indent `)` the same as the start of the line where `(` is.
```

emacs-prelude should ship with a configuration for ruby-mode or ship with another modes for editing ruby which provides indentation that is consistent with these guidelines, instead of leaving the poor user to dig through configuration settings and ruby-mode alternatives for hours. *(I still have not figured this out and suffer a hellish experience editing files.)*

**Comment by twhaples** [comment]
nice bot

**Comment by twhaples** [comment]
Well I changed jobs and I work in Python now, so, um, I guess this problem will persist unabated forever

**Comment by bbatsov** [comment]
Well, I'm the author of RuboCop as well, so I guess this will be addressed at some point. 😆 In my experience RuboCop's defaults and ruby-mode's defaults are quite compatible, but obviously ruby-mode supports way fewer customizations that RuboCop does and there's little I can do about this.
