### ISSUE TITLE
Bind existing map in evil mode

### ISSUE THREAD

**Issue by LaloHao** [bbatsov/prelude#1088]
`C-c p` manages all bindings to projectile in prelude, i was wondeing if there is a way of mapping `SPC p` to `C-p p` so i can use the whole keymap without binding each of the keys manually

I tried

```lisp
(define-key evil-normal-state-map (kbd "SPC") nil)
(define-key evil-normal-state-map (kbd "SPC p") (kbd "C-c p"))
```

but it seems to just bind it to `^Cp`  without letting me use the map

Thanks in advance

**Comment by KarlFish** [comment]
It's not exactly what you wanted, but I could make `SPC p` act as the projectile prefix by enabling and changing `~/.emacs.d/modules/prelude-key-chord.el`.

I changed all the code in the file to:
```
(prelude-require-package 'key-chord)

(require 'key-chord)

(defun space-chord-define (keymap key command)
  "Define in KEYMAP, a key-chord of KEY with space starting a COMMAND.
\nCOMMAND can be an interactive function, a string, or nil.
If COMMAND is nil, the key-chord is removed."
  (define-key keymap (vector 'key-chord ? (if (stringp key) (aref key 0) key)) command))

(define-key projectile-mode-map projectile-keymap-prefix nil)
(space-chord-define projectile-mode-map "p" #'projectile-command-map)

(key-chord-mode +1)

(provide 'prelude-key-chord)
```



Resources I used:
https://www.emacswiki.org/emacs/space-chord.el
https://github.com/bbatsov/projectile/issues/991#issuecomment-270265305

**Comment by LaloHao** [comment]
I wasn't aware of the *-command-map functions, i could just call it instead of translating the key
`(define-key evil-normal-state-map (kbd "SPC p") 'projectile-command-map)`
