### ISSUE TITLE
Manual installation (what do I put in .emacs)

### ISSUE THREAD

**Issue by chrissound** [bbatsov/prelude#1089]
I've cloned down the repo, copied it into `.emacs.d`, however what do I put in my `.emacs` file?

Opening emacs seems to have no difference with the steps I've taken alone.

**Comment by arbox** [comment]
Actually nothing. Since `init.el` is read during the Emacs initialization. You do not need the `.emacs` file.

**Comment by KarlFish** [comment]
Remove the `.emacs` file (or rename it to `.emacs_backup`) and clone the prelude repo into the `.emacs.d`  folder.

```
user@computer$ ls ~/.emacs.d/
auto-save-list   core  init.el   modules   prelude-modules.el   projectile-bookmarks.eld  sample    themes  var
CONTRIBUTING.md`  elpa  init.elc  personal  prelude-modules.elc  README.md                 savefile  utils   vendor
```

**Comment by KarlFish** [comment]
It seems like emacs prioritizes the `.emacs` file over the `.emacs.d` directory because when I create an empty `.emacs` file, emacs does not load any settings in the directory.

**Comment by raxod502** [comment]
This is correct. Emacs prefers `~/.emacs`, then `~/.emacs.el`, then `~/.emacs.d/init.el`. See https://www.gnu.org/software/emacs/manual/html_node/emacs/Init-File.html.

**Comment by chrissound** [comment]
Yes to confirm it works when removing the empty `~/.emacs` file. Thanks, everyone!
