### ISSUE TITLE
Not able to change web-mode-script-padding variable value

### ISSUE THREAD

**Issue by zzhjerry** [bbatsov/prelude#1095]
I'm using `web-mode` for `.vue` files and want to set indentation of `script` and `style` tag to 0 (like the screenshot here: https://vuejs.org/v2/guide/single-file-components.html). I know there's a variable `web-mode-script-padding` that can be used to change that indentation. I tried lots of ways but still can't make it work in Prelude's environment. So I want to seek for some help here.

What I did:

1. Have a freshly installed Prelude
2. moved `sample/prelude-modules.el` to `~/.emacs.d/prelude-modules.el` and uncommented `(require 'prelude-web)`
3. restarted Emacs
4. created `~/.emacs.d/personal/common.el` file
5. In the above file, I tried:

```lisp
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))
(setq web-mode-script-padding 0)
```
and 

```lisp
(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.vue\\'" . web-mode))
(add-hook web-mode-hook (lambda nil (setq web-mode-script-padding 0)))
```

But neither of them worked.

It can change `web-mode-script-padding` variable value temporarily but somehow the variable value was "changed back"

May I know the proper way to change this value?

p.s. I believe this may also be needed for people who are editing other web-mode backed files

**Comment by cailloumajor** [comment]
Hi @zzhjerry ,

I encountered the same problem and found it is caused by [editorconfig-mode](https://github.com/editorconfig/editorconfig-emacs) that overwrites the variable after Prelude executes files in `~/.emacs.d/personal/`
I ended up customizing editorconfig-mode  [as said in the README](https://github.com/editorconfig/editorconfig-emacs#editorconfig-custom-hooks) :
```emacs-lisp
(add-hook 'editorconfig-custom-hooks
  (lambda (hash) (setq web-mode-style-padding 0)))
```

**Comment by iamriel** [comment]
I am also having problems with this one and @cailloumajor 's fix worked for me. Thanks! :)

**Comment by jasalt** [comment]
Had similar issue when trying to set `(setq web-mode-block-padding 0)`, related issue https://github.com/editorconfig/editorconfig-emacs/issues/79. 

Wondering if this should be fixed in prelude-web.el as it seems like PHP indendation is bit broken by default now.
