### ISSUE TITLE
Emacs warnings concerning ido-ubiquitous

### ISSUE THREAD

**Issue by sitesonix** [bbatsov/prelude#1096]
I received warnings upon restarting Emacs after a normal package update today followed by a prelude update. The warning message said that ido-ubiquitous-mode has been replaced with ido-complete-read. The issue seems to be with  ~/.emacs.d/modules/prelude-ido.el since that's where the require statements and references are to ido-ubiquitous-mode.

So I uncommented the following line in my prelude-modules.el for now:

`;; (require 'prelude-ido) ;; Super charges Emacs completion for C-x C-f and more`

But that still didn't solve the problem, since ido-ubiquitous is a prelude dependency.  So I then manually uninstalled ido-ubiquitous-mode and then installed ido-complete-read from the Emacs package manager. The warning messages then disappeared after another Emacs restart. Now to bring back the lost functionality.

Note: I'm using Emacs 25.2.1 on Fedora and my Prelude repo is even with the master branch.

**Comment by ryukinix** [comment]
I experienced that same issue and more using emacs on Windows yesterday. I fixed replacing strings of all ~/.emacs.d of `ido-completin-ubiquitous` to `id-completin-read+`. BTW, after that, I got weird warnings about free-variables on `ido-completing-read+`. https://github.com/DarwinAwardWinner/ido-ubiquitous/issues/121

**Comment by sitesonix** [comment]
Thanks. I came up with a similar solution but I ultimately decided to switch to ivy. After using it for a couple of days now I am convinced that ivy, swiper and counsel would add tremendous value to prelude. 

Still looking into potential keybinding conflicts with prelude's defaults (including projectile) but so far so good.
