### ISSUE TITLE
Create prelude-rust.el

### ISSUE THREAD

**Issue by ryukinix** [bbatsov/prelude#1098]
@bbatsov any intention to do that?

**Comment by bbatsov** [comment]
PR welcome! I haven't done any rust programming myself, so I can't really create anything useful.

**Comment by ryukinix** [comment]
Prelude is awesome, for me is the best and simple distribution to enforce an real emacs experience (not things messy like spacemacs which mixups a lot). Thanks for the open source project.

I just would want you keep that issue opened. If no one implement this, I'll maybe implement it.

**Comment by dougm** [comment]
I worked on a brief Rust experiment and used this during the time: https://github.com/dougm/prelude/commit/1c61ff411f9ce5498f4e5a0b31b5e7a1e282ab73

Not if it still works or what new things have come to be since.

**Comment by ryukinix** [comment]
Thanks for pointing that @dougm! I'll test it.

**Comment by ryukinix** [comment]
@dougm I update your rust setup and create a pull-request here #1102

That setup are working fine on my machine. I like it.

**Comment by ryukinix** [comment]
Implemented on #1102
