### ISSUE TITLE
ad-handle-definition: ‘ido-completing-read’ got redefined

### ISSUE THREAD

**Issue by ryukinix** [bbatsov/prelude#1103]
Always on my prelude startup I got this twice.
```
Using an Emacs configured with --with-x-toolkit=lucid does not have this problem.
Prelude is powering up... Be patient, Master lerax!
Loading personal configuration files in /home/lerax/.emacs.d/personal/preload...
Loading Prelude’s core...
Loading /home/lerax/.emacs.d/prelude-pinned-packages.el (source)...
Loading /home/lerax/.emacs.d/prelude-pinned-packages.el (source)...done
ad-handle-definition: ‘ido-completing-read’ got redefined
ad-handle-definition: ‘ido-completing-read’ got redefined
Loading /home/lerax/.emacs.d/savefile/recentf...
Loading /home/lerax/.emacs.d/savefile/recentf...done
Loading Prelude’s modules...
Loading /home/lerax/.emacs.d/prelude-modules.el (source)...
Turn on helm-projectile key bindings
Loading /home/lerax/.emacs.d/prelude-modules.el (source)...done
Loading personal configuration files in /home/lerax/.emacs.d/personal...
Loading /home/lerax/.emacs.d/personal/coding-system.el (source)...
Loading /home/lerax/.emacs.d/personal/coding-system.el (source)...done
Loading /home/lerax/.emacs.d/personal/custom.el (source)...
Loading /home/lerax/.emacs.d/personal/custom.el (source)...done
Loading /home/lerax/.emacs.d/personal/daemon.el (source)...
Loading /home/lerax/.emacs.d/personal/daemon.el (source)...done
Loading /home/lerax/.emacs.d/personal/hooks.el (source)...
Loading /home/lerax/.emacs.d/personal/hooks.el (source)...done
Loading /home/lerax/.emacs.d/personal/keybindings.el (source)...
Personal keybindings loading...
Loading /home/lerax/.emacs.d/personal/keybindings.el (source)...done
Loading /home/lerax/.emacs.d/personal/modes.el (source)...
Modos do Manoel
Loading /home/lerax/.emacs.d/personal/modes.el (source)...done
Loading /home/lerax/.emacs.d/personal/modules.el (source)...
Loading /home/lerax/.emacs.d/personal/modules.el (source)...done
Prelude is ready to do thy bidding, Master lerax!
Starting new Ispell process aspell with default dictionary...
```

Even if I disabled the `prelude-ido` I still got this. Any idea where this is been redefined? I'm stuck

**Comment by KarlFish** [comment]
Because the warnings appear right after loading `prelude-pinnend-packages.el`, and later both `ido-completing-read+` and `ido-ubiquitous` were both removed from it, **I suspect the error will go away if you update your pinned packages.**

I cant reproduce this issue, even on the 67b1a54e537 (the latest commit available at the time you opened this issue). I do get an error buffer on opening that says:
>    Warning (ido-ubiquitous): The ido-ubiquitous package is now redundant. All functionality, including ido-ubiquitous-mode, has been merged into the ido-completing-read+ package. You should replace ido-ubiquitous with ido-completing-read+ in your Emacs config. For more information, see:
>    https://github.com/DarwinAwardWinner/ido-ubiquitous#version-40-changes

**Comment by ryukinix** [comment]
I'm in shame. You are completely right. I just deleted the `ido-completing-read+` definition and works, no more warning. Actually this was related too with #1104 (which was fixed).

Thanks for the tip, @KarlFish! I'm closing this issue.
