### ISSUE TITLE
While in minibuffer, Ctrl-a to move cursor to beginning of line, returns Search failed

### ISSUE THREAD

**Issue by dmerz75** [bbatsov/prelude#1107]
> When I run compile command: 
`M-x compile`
cursor is in the mini-buffer: 
`Compile command: make -k`
I enter `Ctrl-a` command to move the cursor to the first space in the mini-buffer, and enter a new compile command, I get a Search failed error message: 
`Search failed: "^[[:space:]]*"`
before being allowed to continue...  from the *Messages* buffer, it gives this output:
`let: Search failed: "^[[:space:]]*"`
`apply: Command attempted to use minibuffer while in minibuffer`
`let: Search failed: "^[[:space:]]*"`
`Quit`

Has anyone seen this error message when using (Ctrl-a) in the mini-buffer?
It occurs in my emacs with prelude with/without personal directory customization.
Emacs-version: 25.2.1

C-a runs the command crux-move-beginning-of-line (found in
prelude-mode-map), which is an interactive Lisp closure in ‘crux.el’.
It is bound to C-a.
(crux-move-beginning-of-line ARG)

**Comment by knilink** [comment]
bbatsov/crux#46

**Comment by dmerz75** [comment]
Thanks knilink!
