### ISSUE TITLE
neotree won't unfold directories 

### ISSUE THREAD

**Issue by chrissound** [bbatsov/prelude#1109]
Pressing TAB has no effect and pressing RETURN just goes one line down.

How can I diagnose this issue? I'm not sure if it's a neotree or prelude issue.

I've installed neotree by adding:
```
(prelude-require-packages '(yafolding neotree))
(global-set-key [f8] 'neotree-toggle)
```

to **personal/custom.el**

**Comment by KarlFish** [comment]
I can't reproduce this issue on linux mint.

I clean installed prelude and appended what you wrote to [**personal/custom.el**](https://gist.github.com/KarlFish/88ece4021296fd4d4087e6dc4dd32a13)

`C-h k <press tab>` tells me tab runs `#[(&optional arg) "\301 \210\302\303\304#\207" [arg neo-global--select-window neo-buffer--execute neo-open-file neo-open-dir] 4 nil "P"]`. This isn't directly helpful, but if you get something radically different for what `<tab>` and `<space>` run, that could help solve this.

**Comment by chrissound** [comment]
```
TAB runs the command evil-jump-forward (found in
evil-motion-state-map), which is an interactive compiled Lisp function
in ‘evil-commands.el’.

It is bound to TAB.

(evil-jump-forward &optional COUNT)
```
```
RET runs the command evil-ret (found in evil-motion-state-map), which
is an interactive compiled Lisp function in ‘evil-commands.el’.

It is bound to RET.

(evil-ret &optional COUNT)
```
So I'm guessing this might be an evil key mapping conflict. Thanks for the help @KarlFish !

**Comment by chrissound** [comment]
Ah I think I've found the solution here: https://www.emacswiki.org/emacs/NeoTree#toc12

**Comment by KarlFish** [comment]
Cool
