### ISSUE TITLE
Does Prelude Emacs load ".el* or ".elc" files inside "~ /.emacs.d/personal" directory?

### ISSUE THREAD

**Issue by ofenerci** [bbatsov/prelude#1119]
Hello, 
I have a question regarding  `~.emacs.d/personal/` directory. I assume that Prelude Emacs automatically loads files inside this directory. There are two kinds of files that are `.el` and `.elc`.

For example, if I change the file my personal file "emacs_config.el" in that directory, there is already "emacs_config.elc" (byte compiled) that  will become not updated automatically. In this case, which file (either a file with a suffix `.el` or `.elc`) will Prelude load when I start Emacs? Is there a way for Prelude to automatically produce "*.elc" file whenever I update my `.el` file. I figured out that whenever I update Prelude, it automatically updates all `.el` files inside `/.emacs.d/" directory

**Comment by KarlFish** [comment]
**Prelude will load whichever file extension is newer**.

If you update `.el` file, emacs will load that. When you recompile, emacs will load `.el*.

Normally emacs will always prefer to load `.elc` over `.el` This can be confusing if you compile and then edit `.el` files: your changes won't take effect until you recompile! Prelude sets `load-prefer-newer` to `t` on line 52 in init.el to be more friendly.
