### ISSUE TITLE
preview-latex is not showing up in emacs menu bar. 

### ISSUE THREAD

**Issue by ofenerci** [bbatsov/prelude#1126]
When I open a LaTeX file, preview-latex is not showing up in the menu. For example, In this [link](https://www.gnu.org/software/auctex/preview-latex.html), it shows preview menu bar on the emacs bar. I am also the commands belong to preview-latex (such as `C-c C-p C-b`). I wonder how I could activate preview-latex?

**Comment by KarlFish** [comment]
I fixed this by adding `(package-install 'auctex)` to a `.el` file in the personal dir. Toggle the menu with `<f12>` ( `menu-bar-mode`). 

Weird because`prelude-latex` definitely calls `(prelude-require-packages '(auctex))`.

**Comment by KarlFish** [comment]
I used this named as intro.tex:

```latex
\documentclass[12pt]{article}
\begin{document}

\begin{egnarray}
  e + f &=& y
  f \Delta y - e &=& x
\end{eqnarray}


\begin{equation}
  \label{lgi}
  y = \frac{\Delta y}{\Delta x}x
\end{equation}



\end{document}
```

The equation becomes an image, but nothing else does.
