### ISSUE TITLE
Keystroke added by prelude not working as intended.

### ISSUE THREAD

**Issue by leggettc13** [bbatsov/prelude#1127]
The readme states that C-a is overidden so that it moves to the first non-whitespace character of a line, rather than the beginning of the line on the first press. However that doesn't seem to happen when I press it.

I'm running emacs 25.3, and the readme states that the latest version is 25.2. Could they perhaps have changed something in the newer version that overrides this or did I mess up installing prelude?

I'm on Arch Linux with emacs 25.3.1, running emacs in terminal mode with urxvt.

**Comment by bbatsov** [comment]
Can you check what `C-a` is bound to for you?
