### ISSUE TITLE
Version controlled packages

### ISSUE THREAD

**Issue by holocronweaver** [bbatsov/prelude#1128]
Current behavior: Prelude relies on `package.el` to load its modules, which results in frequent broken packages during upgrades and no easy way to roll back to a known working config other than to backup the elpa directory prior to each upgrade.

Desired behavior: Allow use of a version-controlled form of package management, such as [Borg](https://github.com/emacscollective/borg) or [straight.el](https://github.com/raxod502/straight.el). This could be made optional, possibly with package.el as default package manager.

Discussion: I attempted to use MELPA stable as much as possible, but after a few years of frequently broken package upgrades I am convinced we as a community need to move to a saner approach. Version controlling packages would take care of this by establishing known good configurations which can be rolled back to if an upgrade causes issues, and debugging between versions becomes much easier. The recommended way of using prelude is already via version control, so this would integrate well with the suggested config management via git.

I think this can implemented by abstracting the package manager in Prelude. This should not interfere with ease of use for new users using package.el, while allowing experienced users to switch to a version controlled approach and retaining the convenience of prelude modules.

Personally I opt for `straight.el` as the first alternative as it is the most feature complete and allows standard operations like package upgrades and dependency management which `Borg` doesn't handle. Both of these are better than everyone trying to roll their own solution and dealing with dependencies, etc.

Thoughts?

**Comment by holocronweaver** [comment]
I realize now a fairly simple solution. Switch to `use-package` for prelude package management. By default `use-package` uses `package.el`, but it can be hooked up to other package managers including `straight.el` by simply adding it early in `init.el` (perhaps via the `preload` folder?). Problem solved!

**Comment by redguardtoo** [comment]
See https://github.com/redguardtoo/elpa-mirror 

You don't need even install this package. Just run it as script from time to time.

**Comment by holocronweaver** [comment]
Seems only slightly better than manually backing up my elpa folder prior to an upgrade, which is what I used to do. Version controlling package management still seems a better solution, I've been doing it for a few days now via `straight.el` with no complaints.

**Comment by holocronweaver** [comment]
To clarify, I am willing to implement an abstracted package manager wrapper in prelude, I just would like some feedback before doing so.

**Comment by bbatsov** [comment]
@holocronweaver Sorry about the slow response - too much work, too little time for OSS work. 

What you suggest makes sense - I've been trying to avoid using `use-package`, as I was afraid it might make it harder to people to understand and tweak the config, but as it has been becoming more and more popular I guess it's fine to adopt it.

**Comment by jlisee** [comment]
@holocronweaver any updates or public examples?
