### ISSUE TITLE
/sudo:root@localhost: appear TWICE in file path when projectile grep

### ISSUE THREAD

**Issue by andyafter** [bbatsov/prelude#1129]
When I grep file(in a project under ~), after I press enter in one of the helm options, the file is empty, because "/sudo:root@localhost:" appears twice in the path.

**Comment by andyafter** [comment]
Solved by deleting all the sudo opened records in recentf(I set the whole project as 777), but there's definitely a bug here.

**Comment by bbatsov** [comment]
But it seems the bug is in either Projectile or Helm Projectile, so I'll close this ticket.
