### ISSUE TITLE
GitHub project description implies Emacs 25 incompatibility

### ISSUE THREAD

**Issue by silverlyra** [bbatsov/prelude#1133]
<img width="359" alt="screen shot 2017-10-27 at 2 03 59 pm" src="https://user-images.githubusercontent.com/25393735/32125226-c0e3ba5a-bb1f-11e7-85ac-5ca0afdbf0df.png">

I'm new to emacs and exploring the ecosystem, and just came across prelude—and almost closed my browser tab because I thought I'd have to downgrade Emacs to use it.

**Comment by ryukinix** [comment]
Yes, this can misunderstood, can be changed. btw, I used prelude on the following emacs versions:

+ 24.5.1
+ 25.5.1
+ 26.0
+ 27.0.1

I had minor problems on 26+ versions but nothing specific with prelude,  most of the problems is legacy code of some packages that I use (like the matlab-mode).

**Comment by silverlyra** [comment]
ok, good to know. normally I'd open a PR, but I can't open one for a project's GitHub metadata, so, either change it to, say “24+”, or close this issue. thanks!

**Comment by bbatsov** [comment]
I'll do this now myself.
