### ISSUE TITLE
during package update I get the following error

### ISSUE THREAD

**Issue by kirk86** [bbatsov/prelude#1139]
During package update I get the following error:

`ad-handle-definition: ‘LaTeX-add-bibliographies’ got redefined`

Updating the remaining packages halts at this stage. Does anybody know how to avoid this?

Any idea where does this come from and how to resolve this?

Actually on a second look closer, what happens is that instead of prelude updating it gets stalled a that warning message and doesn't complete the full update as its supposed to do or as it was working prior to the presence of this warning.

**Comment by bbatsov** [comment]
I've never seen this message, but it seems like warning only. It also seems unrelated to Prelude. I don't recall us adding any LaTeX related advices in the code.
