### ISSUE TITLE
Dired: only one buffer when input/exit in directory

### ISSUE THREAD

**Issue by oystersauce8** [bbatsov/prelude#1140]
How do prelude folks deal with this issue?

https://emacs.stackexchange.com/questions/36596/dired-only-one-buffer-when-input-exit-in-directory

"When navigating a deep directory structure with 'dired', I end up with many 'tired buffers' inside my 'list-buffers' (C-x C-b)

I was just pressing enter to traverse the nested directory tree. I don't need to clutter up my buffer list with all this 'tired' buffers."

**Comment by bbatsov** [comment]
Just press `a` instead of `Enter`.
