### ISSUE TITLE
Can not create new file with c-x c-f

### ISSUE THREAD

**Issue by vaxilicaihouxian** [bbatsov/prelude#1141]
When I use `c-x c-f` to create a new file there is some auto-complete file name displaying.

```
Find file: ~/.emacs[.d]{.emacs.d.pre-prelude.tar | .emacs.d/}

```

So,I can not create a file like '.emacs'.

**Comment by bbatsov** [comment]
You just have to press `C-f` one more time and it will disappear. That's standard `ido-mode` behaviour.
