### ISSUE TITLE
Anybody have a Prelude Cheat Sheet ?

### ISSUE THREAD

**Issue by oystersauce8** [bbatsov/prelude#1142]
(In the README)
It would be really cool if we can have/link-to an updated version of this
with all the prelude (shortcut) goodies included

![rxlwp](https://user-images.githubusercontent.com/10361390/33995102-bc89d7fe-e091-11e7-8669-6a733a337c74.png)

**Comment by bbatsov** [comment]
PRs welcome! 😄 

I created one for CIDER a while ago - https://github.com/clojure-emacs/cider/blob/master/doc/cider-refcard.tex

Someone can use it as a template to easily create one for Prelude.
