### ISSUE TITLE
Error in post-command-hook (global-fci-mode-check-buffers): (void-variable fci-mode)

### ISSUE THREAD

**Issue by kirk86** [bbatsov/prelude#1144]
Just transfered my .emacs from osx to my linux box.
Removed all *.elc and on opening emacs I keep getting this error.
Any thoughts on that?

**Comment by bbatsov** [comment]
Seems you had installed `fci-mode` manually and forgot to install it afterwards.

**Comment by kirk86** [comment]
@bbatsov thanks! I think the issue was due the fact that the linux version was 23, 24 and column-fill-indicator has an issue with those emacs versions on linux. After deactivating column-fill-indicator everything was working fine.
