### ISSUE TITLE
Help needed: How access <s-w> for ace-window

### ISSUE THREAD

**Issue by poulpoulsen** [bbatsov/prelude#1147]
hello,
i'm on windows 8.1 with emacs 25.
As far as i read, <s-> means superkey. The superkey on windows is the key with the windows symbol.
But the combination <s-w> for ace-window in prelude opens the windows search.
So i think, there might be a problem with my understanding of <s->.
Is it bound to an alternative combination?
How could i find out?

Regards
Poul

**Comment by bbatsov** [comment]
I guess you need to set a different keybinding on Windows. And I guess we should also add some check about the OS and add this extra keybinding there.
