### ISSUE TITLE
prelude-c.el c indentation doesn't work

### ISSUE THREAD

**Issue by yfy-** [bbatsov/prelude#1149]
I have a freshly installed emacs and prelude.
Although the c-basic-offset is 4 in modules/prelude-c.el the indentation is still 2 in c-mode.

Note:
(require 'prelude-c) line is uncommented in sample/prelude-modules.el

**Comment by Bankq** [comment]
Hey @yfy- I believe you'll need to put `prelude-modules.el` under prelude-dir directly to take effect (e.g copy it out of samples/). This is described in README

```
If you are doing a manual install then you first need to copy the prelude-modules.el available in the sample directory to the root of path/to/prelude/installation and then adjust that one.
```

Also make sure there's no configuration under personal to overwrite it (esp. custom.el). I learned it the hard way :)
