### ISSUE TITLE
Collision of Key mappings of Ivy and Crux

### ISSUE THREAD

**Issue by bgschaid** [bbatsov/prelude#1151]
I noticed that `prelude-ivy.el` sets the key combination `C-c k` to `counsel-ag` but that this is not used because it is overridden by the setting in `prelude-mode.el` (which sets it to `crux-kill-other-buffer`)

I'm fine with the current setting but it would be nice if there was a "Prelude standard"-mapping to `counsel-ag`

**Comment by bbatsov** [comment]
Ops, we should certainly fix this. I just copy/pasted the suggested keybindings from `ivy` without reviewing them carefully.
