### ISSUE TITLE
orgmode is too old, how to update it

### ISSUE THREAD

**Issue by yxsongbo** [bbatsov/prelude#1155]
The new is 9.0

**Comment by patrixl** [comment]
Add the org-mode ELPA repo to your package archives and update:

https://orgmode.org/elpa.html

**Comment by x61** [comment]
how do you update?

**Comment by brianmcgillion** [comment]
I have the following in personal/ainit.el

-----------------------
```
;; Bootstrap `use-package'
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;; Force org install from latest mainline branch
(require 'package)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)

(use-package org :ensure org-plus-contrib :pin org)
```

-----------------------

**Comment by pmeckoni** [comment]
The latest release of emacs [notes that](https://www.gnu.org/software/emacs/news/NEWS.26.1)  
> Emacs 26.1 comes with Org v9.1.6.
This should be recent enough for most users. 
If you can, try to migrate to the latest emacs version.
