### ISSUE TITLE
CDLatex has not turned on

### ISSUE THREAD

**Issue by allenryb** [bbatsov/prelude#1156]
Dear everyone,

I am new to Emacs, but recently I try to work on Emacs with AUCTex and CDLatex. 
Prelude is good for me.
But one problem troubles me: `cdlatex-mode`  isn't auto-turned-on after `.tex` file is loaded. 
I have  uncommented the code in `prelude-modules.el`.
`cdlatex-mode` works if I type `M-x cdlatex-mode`.

What should I do to make `cdlatex-mode` auto-load?

Thanks!

**Comment by bbatsov** [comment]
Just add this to your config:

```
(add-hook 'LaTeX-mode-hook #'cdlatex-mode)
```
