### ISSUE TITLE
No way to interrupt minibuffer completion with prelude+magit

### ISSUE THREAD

**Issue by vineus** [bbatsov/prelude#1157]
Autocomplete is great, as long as you can interrupt it (eg: `C-f` after a `C-x C-f`), and sometimes you can't do it with `C-g` (it interrupts the current action).

This is particularly annoying when trying to tag a commit with magit (`t t`) and other longer version of the tag you want to write exist.

In the following screenshot, how can I add the tag `1.1` ?

![image](https://user-images.githubusercontent.com/467126/37411564-60b34a1a-27a3-11e8-9a75-a31e81a2ed62.png)

(it always selects one of the possible completion stating with `1.1`)

I tried to look for a way to interrupt completion while typing but could not find any.

Thanks.

**Comment by bbatsov** [comment]
I guess it's documented somewhere here - http://oremacs.com/swiper/#commands

@abo-abo might be able to provide an answer faster. In my experience you can just type whatever as the search and this is going to be the end result, which is probably what you want.

**Comment by vineus** [comment]
Hey @bbatsov thanks a lot for the doc pointer. 

>  In my experience you can just type whatever as the search and this is going to be the end result

Unfortunately no, the end result is whatever is highlighted, not what you typed (in the case if the example above: `1.1.0`, not `1.1`

But I found the command to interrupt here: http://oremacs.com/swiper/#key-bindings-for-navigation

> `C-M-j (ivy-immediate-done)`
Exits with the current input instead of the current candidate (like other commands).
>
> This is useful e.g. when you call find-file to create a new file, but the desired name matches an existing file. In that case, using C-j would select that existing file, which isn't what you want - use this command instead.
