### ISSUE TITLE
Unable to load Custom Theme from MELPA

### ISSUE THREAD

**Issue by JamesLaverack** [bbatsov/prelude#1161]
I'm having trouble loading a custom theme. The README states:

>Or you can use another theme altogether by adding something in personal/preload like:
>
>```
>(prelude-require-package 'solarized-theme)
>(setq prelude-theme 'solarized-dark)
>```

But attempting to use `prelude-require-package` in a file `personal/preload/theme.el` results in the following error:

>Symbol's function definition is void: prelude-require-package 

From reading the code I understand that elisp files in `personal/preload/` are loaded before any prelude core files, which means that the `prelude-require-package` function is not available yet.

However if I put this elisp file in `personal/` so that prelude loads it *after* `core/prelude-packages.el` (which defines `prelude-require-package`) then it's too late, as the code to actually load the theme based on the value of `prelude-theme` happens when `core/prelude-ui.el` is loaded.

What's the best approach for loading custom themes when you need to download them from MELPA too?

**Comment by bbatsov** [comment]
I guess we should just require the core Prelude functions earlier. They are not part of the config, so that makes sense. 

In general you can always replace the theme in the normal part of the config using `(load-theme ...`.

**Comment by Bankq** [comment]
@bbatsov May I send a PR to fix the description in readme before we have core prelude functions loaded before personal?
