### ISSUE TITLE
On initial installation with sh script, receive numerous warnings about obsolete and unknown issues

### ISSUE THREAD

**Issue by wlharvey4** [bbatsov/prelude#1167]
`Warning (bytecomp): function seq-drop used to take 1+ arguments, now takes 2
Warning (bytecomp): function seq-take used to take 1+ arguments, now takes 2
Warning (bytecomp): function seq-drop-while used to take 2+ arguments, now takes 2
Warning (bytecomp): function seq-empty-p used to take 1+ arguments, now takes 1
Warning (bytecomp): function seq-sort used to take 2+ arguments, now takes 2
Warning (bytecomp): the following functions are not known to be defined:
    seq-map-indexed, seq-sort-by, seq-random-elt
Warning (bytecomp): cl package required at runtime
Warning (bytecomp): the following functions are not known to be defined:
    browse-kill-ring-fit-window, delete-active-region
Warning (bytecomp): the following functions are not known to be defined:
    js2-node-at-point, js2-ast-root-p, js2-node-abs-pos,
    js2-node-abs-end, js2-node-parent, js2-node-short-name
Warning (bytecomp): Unknown slot ‘:output’
Warning (bytecomp): ‘object-p’ is an obsolete function (as of 25.1); use ‘eieio-object-p’ instead. [3 times]
Warning (bytecomp): attempt to inline ‘ht-empty?’ before it was defined [2 times]
Warning (bytecomp): ‘object-p’ is an obsolete function (as of 25.1); use ‘eieio-object-p’ instead.
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead. [2 times]
Warning (bytecomp): Unknown slot ‘:input’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead. [4 times]
Warning (bytecomp): ‘object-slots’ is an obsolete function (as of 25.1); use ‘eieio-class-slots’ instead. [2 times]
Warning (bytecomp): the following functions are not known to be defined: ht?, ht<-alist,
    ht-empty?, ht-items, marshal-get-class-slot
Warning (bytecomp): Unknown slot ‘:level’
Warning (bytecomp): Unknown slot ‘:buffer’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): cl package required at runtime
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): Unknown slot ‘:version’
Warning (bytecomp): ‘object-class’ is an obsolete function (as of 24.4); use ‘eieio-object-class’ instead.
Warning (bytecomp): Unknown slot ‘:entries’
Warning (bytecomp): Unknown slot ‘:entry-cls’
Warning (bytecomp): Unknown slot ‘:value-cls’
Warning (bytecomp): Unknown slot ‘:value’
Warning (bytecomp): Unknown slot ‘:ttl’
Warning (bytecomp): Unknown slot ‘:timestamp’
Warning (bytecomp): ‘object-p’ is an obsolete function (as of 25.1); use ‘eieio-object-p’ instead.
Warning (bytecomp): ‘object-class’ is an obsolete function (as of 24.4); use ‘eieio-object-class’ instead.
Warning (bytecomp): Unknown slot ‘:timestamp’
Warning (bytecomp): Unknown slot ‘:save-delay’
Warning (bytecomp): ‘object-class’ is an obsolete function (as of 24.4); use ‘eieio-object-class’ instead.
Warning (bytecomp): Unknown slot ‘:version’
Warning (bytecomp): Unknown slot ‘:log’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): Unknown slot ‘:auth’
Warning (bytecomp): Unknown slot ‘:cache’
Warning (bytecomp): Unknown slot ‘:username’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead. [2 times]
Warning (bytecomp): Unknown slot ‘:headers’
Warning (bytecomp): Unknown slot ‘:data’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): Unknown slot ‘:http-status’
Warning (bytecomp): Unknown slot ‘:-req’
Warning (bytecomp): Unknown slot ‘:page-limit’
Warning (bytecomp): Unknown slot ‘:data-format’
Warning (bytecomp): Unknown slot ‘:base’
Warning (bytecomp): Unknown slot ‘:cache’
Warning (bytecomp): Unknown slot ‘:key’
Warning (bytecomp): Unknown slot ‘:revive’
Warning (bytecomp): Unknown slot ‘:token’
Warning (bytecomp): Unknown slot ‘:data’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): Unknown slot ‘:username’
Warning (bytecomp): Unknown slot ‘:req’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): Unknown slot ‘:password’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): Unknown slot ‘:token’
Warning (bytecomp): Unknown slot ‘:outdated’
Warning (bytecomp): Unknown slot ‘:etag’
Warning (bytecomp): ‘object-p’ is an obsolete function (as of 25.1); use ‘eieio-object-p’ instead.
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): Unknown slot ‘:url’
Warning (bytecomp): Unknown slot ‘:body’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): Unknown slot ‘:content’
Warning (bytecomp): Unknown slot ‘:files’
Warning (bytecomp): Unknown slot ‘:description’
Warning (bytecomp): Unknown slot ‘:public’
Warning (bytecomp): Unknown slot ‘:content’
Warning (bytecomp): Unknown slot ‘:filename’
Warning (bytecomp): Unknown slot ‘:content’
Warning (bytecomp): Unknown slot ‘:id’ [2 times]
Warning (bytecomp): Unknown slot ‘:name’
Warning (bytecomp): Unknown slot ‘:color’
Warning (bytecomp): Unknown slot ‘:state’
Warning (bytecomp): Unknown slot ‘:description’
Warning (bytecomp): Unknown slot ‘:due-on’
Warning (bytecomp): Unknown slot ‘:title’
Warning (bytecomp): Unknown slot ‘:assignee’
Warning (bytecomp): Unknown slot ‘:milestone’
Warning (bytecomp): Unknown slot ‘:title’
Warning (bytecomp): Unknown slot ‘:state’
Warning (bytecomp): Unknown slot ‘:number’
Warning (bytecomp): Unknown slot ‘:login’
Warning (bytecomp): Unknown slot ‘:name’
Warning (bytecomp): Unknown slot ‘:id’ [2 times]
Warning (bytecomp): Unknown slot ‘:name’
Warning (bytecomp): ‘call-next-method’ is an obsolete function (as of 25.1); use ‘cl-call-next-method’ instead.
Warning (bytecomp): Unknown slot ‘:billing-email’
Warning (bytecomp): Unknown slot ‘:blog’
Warning (bytecomp): Unknown slot ‘:company’
Warning (bytecomp): Unknown slot ‘:email’
Warning (bytecomp): Unknown slot ‘:location’
Warning (bytecomp): Unknown slot ‘:name’
Warning (bytecomp): Unknown slot ‘:login’
Warning (bytecomp): Unknown slot ‘:head’
Warning (bytecomp): Unknown slot ‘:base’
Warning (bytecomp): Unknown slot ‘:ref’
Warning (bytecomp): Unknown slot ‘:sha’
Warning (bytecomp): Unknown slot ‘:ref’
Warning (bytecomp): Unknown slot ‘:sha’
Warning (bytecomp): Unknown slot ‘:name’
Warning (bytecomp): Unknown slot ‘:homepage’
Warning (bytecomp): Unknown slot ‘:description’
Warning (bytecomp): Unknown slot ‘:private’
Warning (bytecomp): Unknown slot ‘:name’
Warning (bytecomp): Unknown slot ‘:login’
Warning (bytecomp): Unknown slot ‘:owner’
Warning (bytecomp): Unknown slot ‘:http-status’ [3 times]
Warning (bytecomp): Unknown slot ‘:transform’
Warning (bytecomp): Unknown slot ‘:callbacks’
Warning (bytecomp): ‘object-p’ is an obsolete function (as of 25.1); use ‘eieio-object-p’ instead.
Warning (bytecomp): Unknown slot ‘:data-received’
Warning (bytecomp): Unknown slot ‘:num-retries’
Warning (bytecomp): Unknown slot ‘:method’
Warning (bytecomp): Unknown slot ‘:data’
Warning (bytecomp): Unknown slot ‘:headers’
Warning (bytecomp): Unknown slot ‘:url’
Warning (bytecomp): Unknown slot ‘:query’
Warning (bytecomp): Unknown slot ‘:async’
Warning (bytecomp): Unknown slot ‘:install-callbacks’
Warning (bytecomp): Unknown slot ‘:profile’
Warning (bytecomp): Unknown slot ‘:html-url’
Warning (bytecomp): Unknown slot ‘:id’
Warning (bytecomp): Unknown slot ‘:date’
Warning (bytecomp): Unknown slot ‘:filename’
Warning (bytecomp): Unknown slot ‘:data’
Warning (bytecomp): Unknown slot ‘:user’
Warning (bytecomp): Unknown slot ‘:public’
Warning (bytecomp): Unknown slot ‘:description’
Warning (bytecomp): function ‘every’ from cl package called at runtime
Warning (bytecomp): function ‘some’ from cl package called at runtime
Warning (bytecomp): function ‘every’ from cl package called at runtime
Warning (bytecomp): Unknown slot ‘:files’
Warning (bytecomp): Unknown slot ‘:id’
Warning (bytecomp): the function ‘eshell-search-path’ is not known to be defined.
Warning (bytecomp): looking-back called with 1 argument, but requires 2-3
Error (bytecomp): Cannot open load file: No such file or directory, markdown-mode
Warning (bytecomp): Unused lexical variable ‘end-line’
Warning (bytecomp): Unused lexical variable ‘allowed-open’
Warning (bytecomp): Unused lexical variable ‘allowed-close’
Warning (bytecomp): reference to free variable ‘undo-tree-mode’
Warning (bytecomp): Unused lexical variable ‘i’ [4 times]
Warning (bytecomp): ‘undo-elt-crosses-region’ is an obsolete function (as of 25.1). [2 times]
Warning (bytecomp): Unused lexical variable ‘i’ [7 times]
Warning (bytecomp): reference to free variable ‘undo-tree-visualizer-selection-mode’ [2 times]
Warning (bytecomp): Unused lexical variable ‘i’ [4 times]
Warning (bytecomp): ‘goto-line’ is for interactive use only; use ‘forward-line’ instead.
Warning (bytecomp): ‘next-line’ is for interactive use only; use ‘forward-line’ instead.
Warning (bytecomp): ‘goto-line’ is for interactive use only; use ‘forward-line’ instead. [3 times]
`

**Comment by bbatsov** [comment]
All those warnings are coming from the various 3rd party packages that Prelude is bundling. There's not much we can do about those warnings apart from reporting them upstream to the various packages that produce them.
