### ISSUE TITLE
error: Package 'vkill-' is unavailable

### ISSUE THREAD

**Issue by umi-neko** [bbatsov/prelude#1169]
I install prelude via manual. When start emacs, it said "Warning (initialization): An error occurred while loading ‘/Users/xxx/.emacs.d/init.el’: error: Package ‘vkill-’ is unavailable".
I try to using package-install to fix this problem, but it seems that there is no package named vkill.
I download a vkill.el from github and put it in personal/preload, then add  (require 'vkill)  in my custom start el. After restart emacs I can run vkill in M-x, but the error still there. So which step I have wrong?
My OS is macOS 11.12.6, emacs version is 25.3.1
thx

**Comment by bbatsov** [comment]
Likely you're suffering from this problem - https://blog.vifortech.com/posts/emacs-tls-fix/

**Comment by umi-neko** [comment]
Thank you! It worked.
