### ISSUE TITLE
[Suggestion] Enable exec-path-from-shell On Linux

### ISSUE THREAD

**Issue by eriFelaP** [bbatsov/prelude#1171]
Hi, I find `prelude` only enable `exec-path-from-shell` on macOS. When I build Emacs by myself on openSUSE(in order to use the newer version), the Emacs I built doesn't use the shell PATH too.

The majority of Linux distributions release without the latest Emacs. So I guess other people build Emacs by himself **may be**(I am not really sure) also took the same problem. Why just enable exec-path-from-shell on Linux as well? :-)

**Comment by bbatsov** [comment]
Fine by me - PR welcome!

**Comment by palikar** [comment]
I can fix this. I'll just add a new core module `prelude-linux.el` that should be loaded only if the operating system is some GNU\Linux ("gnoo slash linox" of course). BTW, I myself compile Emacs from source.
