### ISSUE TITLE
Prelude compatibility with Emacs 2.26

### ISSUE THREAD

**Issue by AmiZya** [bbatsov/prelude#1175]
Hello guys,

Does Prelude support 2.26 yet ? I just updated emacs and it crashed. I tried updating Prelude too from git but still doesn't work.

Any one knows when the update for 2.26 will occure ?

Thanks

**Comment by bbatsov** [comment]
https://github.com/bbatsov/prelude/issues/1148

**Comment by AmiZya** [comment]
Yes. Emacs 26.1, sorry.

**Comment by bbatsov** [comment]
Seems that Prelude works just fine on 26.1 - I can't reproduce this issue. Feel free to re-open the ticket if you have more data to post.
