### ISSUE TITLE
Package `emacs-25.1' is unavailable

### ISSUE THREAD

**Issue by nshigit** [bbatsov/prelude#1179]
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"

ii  emacs24-nox                                       24.5+1-6ubuntu1.1                            amd64        GNU Emacs editor (without GUI support)

when preclude is installing, magit package report "`emacs-25.1' is unavailable" error, after comment magit package in core/preclude-packages.el, I found that the error is caused by installing 'git-commit'.

M-X package-install
        git-commit
Package `emacs-25.1' is unavailable

**Comment by bbatsov** [comment]
You'll need to install Emacs 25.1 or newer then. Many packages no longer support Emacs 24.

**Comment by otluiz** [comment]
Hello bbatsov, use this (add-to-list 'package--builtin-versions '(emacs 25)).
Ref.: https://emacs.stackexchange.com/questions/34296/package-emacs-25-is-unavail
