### ISSUE TITLE
crux-move-beginning-of-line in ansi-term

### ISSUE THREAD

**Issue by haji-ali** [bbatsov/prelude#1186]
In prelude, crux-move-beginning-of-line is mapped to C-a, which is great when editing code.

However, in an `ansi-term` character mode, this mapping breaks the behaviour of a normal `C-a`. In that, when I press it, the cursor jumps to the beginning of the right before the beginning of the prompt. When I then enter text, the cursor jumps forward and the text is added to the end of the line instead.

**Comment by squarepegsys** [comment]
I run my ansi-term in char mode, not line mode, and my C-a does nothing at all.

**Comment by fhd** [comment]
Found a workaround, FWIW: https://github.com/bbatsov/prelude/pull/1369
