### ISSUE TITLE
Provide reasons of removing (or adding) packages

### ISSUE THREAD

**Issue by azzamsa** [bbatsov/prelude#1192]
Hi.

I saw some packages removed e.g [god-mode removed](https://github.com/bbatsov/prelude/commit/dd5465752ef49de00747ed8eeca9c8a3bd674627) . But I don't find any reason in git commit message nor the commit doesn't reference an issue.

I *think* it's better to provide reason for removing (or adding) predule's packages. So people who inspired from prelude's config (and prelude users) know prelude's opinions and decisions.

Thank you :)

**Comment by bbatsov** [comment]
Yeah, that's a good point. It also reminds me that at some point we should add a changelog and maybe tag some releases. :-)

`god-mode` was removed for two reasons:

* the package was just installed with no special configuration for it (I think there was some keybinding for it at some point, which was the only special config we had for god-mode)
* it never really took off (there were many issues with it and 3 years of no commits), so I decided it's not something worth promoting to a broader audience. 

Generally I aim to have only packages that are tried, true and ideally actively maintained.

**Comment by azzamsa** [comment]
> Yeah, that's a good point.

:) 

> we should add a changelog and maybe tag some releases. :-)

I *think* the changelog should also contain reason of addition and removal. Not only log of changes.

> Generally I aim to have only packages that are tried, true and ideally actively maintained.

Same here. I believe prelude's core package should only contain 'tried, true and ideally actively maintained.'. With the exception of very useful package even they're bit outdated.

I love the 'opinionated' way. Because from this we learn what is the *best* practice in emacs. The emacs hacker way. I believe any addition or changes extremely need explanation and reason :)

Thanks :)
