### ISSUE TITLE
C-w does not kill line if no region is selected

### ISSUE THREAD

**Issue by durson** [bbatsov/prelude#1198]
The C-w shortcut does not kill line, instead the message
"The mark is not set now, so there is no region" is shown.
However, M-x kill-region works fine - it deletes the line if no region is selected.

OS: Ubuntu 18.04.1
Emacs version: GNU Emacs 25.2.2

**Comment by palikar** [comment]
I cannot reproduce this with fresh clone of the repository. Are you sure you haven't bound `C-w` to something else?

**Comment by durson** [comment]
Ok, I noticed that this issue affects emacs only in the *scratch* buffer.
