### ISSUE TITLE
Tracking Prelude modules under personal dir

### ISSUE THREAD

**Issue by arbox** [bbatsov/prelude#1206]
Prelude does a pretty good job in separating personal and global configuration (in my point of view) with only one exception: `prelude-modules.el` is stored in the root.

Maybe I've missed previous discussions so please correct me.

If not, I'd suggest moving `prelude-modules.el` under `personal` dir and change the lookup algorithm (for backward compatibility) so that Prelude looks first under `personal`, then in the root, and takes the first found configuration.

Possibly, the root location can be deprecated and removed after some longer  time.

Is that feasible?

**Comment by bbatsov** [comment]
That's a very good point and I think this is going to be easy to implement. PRs welcome!

**Comment by arbox** [comment]
OK, then I'll do that!

**Comment by arbox** [comment]
@bbatsov 
Please check #1207.
Since it's my really first Lisp contribution I'd be glad to get any suggestions!

**Comment by kirill-gerasimenko-zocdoc** [comment]
Hi @arbox, 
It looks like https://github.com/bbatsov/prelude/pull/1207/files#diff-64ed6d0a7a4f2eaf33cacc2454a19cffR152 breaks loading files in `personal/`. When I remove added part `^prelude-modules\.el$ - files are loaded.
