### ISSUE TITLE
personal directory not loaded

### ISSUE THREAD

**Issue by spaceotter** [bbatsov/prelude#1208]
My customizations in personal/ are not running. On inspection it seems there is an issue with this regex in init.el:
`(directory-files prelude-personal-dir 't "^[^#\.].*el$|^prelude-modules\.el$")`
Evaluating this yields 'nil' but there are .el files present.
`(delete prelude-modules-file (directory-files prelude-personal-dir 't "^[^#.].*\\.el$"))`
This has the expected behavior, finds only the .el files, and excludes prelude-modules.el.

**Comment by arbox** [comment]
Yep, this approach is much better, you're right!
