### ISSUE TITLE
Default pdf viewer for prelude-latex 

### ISSUE THREAD

**Issue by pmeckoni** [bbatsov/prelude#1210]
On trying to view a compiled pdf file from its latex source, it tries to open using the external viewer which defaults to Evince. For those who don't have Evince installed (generally bundled with GNOME), this gives an error.

1. Can we get the default pdf viewing program be either [DocView](https://www.gnu.org/software/emacs/manual/html_node/emacs/Document-View.html) or [pdf-tools](https://github.com/politza/pdf-tools)
2. Can you try to get this pdf viewing program to reload the (pdf) buffer after the latex file has been freshly compiled.

**Comment by haluk** [comment]
You can change the default viewer to something else with:
```emacs-lisp
(defun my-LaTeX-mode()
  (add-to-list 'TeX-view-program-list '("Xreader" "xreader --page-index=%(outpage) %o"))
  (setq TeX-view-program-selection '((output-pdf "Xreader")))
  ; Other mode specific config
  )
(add-hook 'LaTeX-mode-hook 'my-LaTeX-mode)
```
