### ISSUE TITLE
Unable todo customize css-indent-offset

### ISSUE THREAD

**Issue by gexplorer** [bbatsov/prelude#1214]
When using *css-mode* I work with a *css-indent-offset* of 4 and after customizing the value it works until I restart emacs. Whenever I restart the value gets set to 2. As far as I know it's a desirable effect, since it is set in prelude case module but I think the customized and saved value should overwrite the prelude default one.

**Comment by Bankq** [comment]
Put `(setq css-indent-offset 4)` in your `personal/*` configs and it'll overwrite the prelude default one.

**Comment by Bankq** [comment]
or you can do
```
(setq css-indent-offset 4) ;; or using M-x customize
... ;; somewhere in your personal
(customize-save-customized)
```

**Comment by gexplorer** [comment]
That's exactly the problem, I saved it using customize and i also added it
in to my configuration by hand and it works until I restart emacs. After
restarting emacs, the next time css-mode gets loaded preload overwrites my
value.

**Comment by Bankq** [comment]
I agree. It's strange that the steps work for me. `custom.el` should be saved to `personal/` given the following line in `init.el`
```
;; config changes made through the customize UI will be stored here
(setq custom-file (expand-file-name "custom.el" prelude-personal-dir))
```
Is that the case for you?
