### ISSUE TITLE
  (EL guru FlyC:1/2 company ivy EditorConfig ws Projectile[.emacs.d:generic] super-save SP/s Pre WK (*)) 

### ISSUE THREAD

**Issue by KernelWhisper** [bbatsov/prelude#1217]
How  I delete the "  (EL guru FlyC:1/2 company ivy EditorConfig ws Projectile[.emacs.d:generic] super-save SP/s Pre WK (*)) " from mode line.

**Comment by bbatsov** [comment]
See https://emacs.stackexchange.com/questions/3925/hide-list-of-minor-modes-in-mode-line

P.S. That's a standard Emacs feature, not something coming from Prelude.
