### ISSUE TITLE
How to disable swiper?

### ISSUE THREAD

**Issue by jramapuram** [bbatsov/prelude#1223]
Is it possible to disable swiper and default back to traditional C+s ? I tried force setting the C+s key in the config via :

```lisp
(global-set-key (kbd "C-s") 'search-forward)
```

While it does set it back to standard mode the search does not repeatedly search for the next occurrence with repeated C+s presses.

**Comment by jramapuram** [comment]
Never mind. Looks like `ivy` was the root-cause.
Disabling in prelude-modules resolved this.

**Comment by frozar** [comment]
If you don't want to disable all prelude-modules, you can just redefine the shortcut. As it is currently defined as follows:
https://github.com/bbatsov/prelude/blob/c951f8e52e7deed9463ca4630db992408ec9a956/modules/prelude-ivy.el#L50

In `.emacs.d/personal/custom.el` you can add this line to overwrite this key binding:
```elisp
(global-set-key "\C-s" 'isearch-forward)
```
