### ISSUE TITLE
M-x command adds "^" before the cursor

### ISSUE THREAD

**Issue by sologiler** [bbatsov/prelude#1228]
I have a fresh install of prelude using the `curl -L https://git.io/epre | sh` command. Haven't changed anything. When I do `M-x` it opens up minibuffer to type the command, but in front of the cursor is caret symbol. 

<img width="375" alt="Screenshot 2019-03-25 at 22 17 01" src="https://user-images.githubusercontent.com/48495197/54951239-cce1c380-4f4b-11e9-8716-df19c18d3b55.png">

So I have to delete the caret symbol before I can start typing my command.

One thing that I noticed is that in `.emacs.d/personal` folder I already have `prelude-modules.el` file. 

**Emacs version:** 26.1
**Prelude Git HEAD** 1ec67804

**Comment by bbatsov** [comment]
It's a ivy feature, as by default the ivy input is a regexp. Therefore that input will match only the beginning of selections. You can customize this via `ivy-initial-inputs-alist'.
