### ISSUE TITLE
Single quotes generate backslashes.

### ISSUE THREAD

**Issue by ryanpcmcquen** [bbatsov/prelude#1233]
I'm typing up some C using Prelude (it's a wonderful distribution of Emacs, by the way), and it seems to strangely insert backslashes that are unnecessary and wrong after typing a single quote (`'`):

![automatic_back_slashes_on_single_quotes_prelude](https://user-images.githubusercontent.com/772937/57338284-8e5e2d80-70e1-11e9-965c-9cfdc1efdcf1.gif)

Any idea what is causing this?

**Comment by pmeckoni** [comment]
Try using `C-q \` `till you get your solution

**Comment by ryanpcmcquen** [comment]
@pmeckoni, thanks for the workaround.

**Comment by ryanpcmcquen** [comment]
It's the `smartparens` package, how do I disable it?

**Comment by ryanpcmcquen** [comment]
@toctan's response here works for now to disable `smartparens`:
https://github.com/bbatsov/prelude/issues/675#issuecomment-54734380

Here's the upstream bug:
https://github.com/Fuco1/smartparens/issues/783

**Comment by innerout** [comment]
Instead of disabling smartparens completely you can set (setq sp-escape-quotes-after-insert nil) in your configuration and get the expected behavior in Emacs.

**Comment by ryanpcmcquen** [comment]
@innerout, sounds like that should be default behavior then.

**Comment by bbatsov** [comment]
I'll have to see what exactly is this supposed to do. I guess the quoting was meant only for a specific context (e.g. inside a string). //cc @fuco1

**Comment by ryanpcmcquen** [comment]
@bbatsov, any progress here?

**Comment by ryanpcmcquen** [comment]
This is still an issue!

**Comment by Fuco1** [comment]
I have pushed a fix upstream now.

**Comment by ryanpcmcquen** [comment]
Is this fixed now?

**Comment by ryanpcmcquen** [comment]
Is this fixed?

**Comment by innerout** [comment]
@ryanpcmcquen This is fixed, @Fuco1 has fixed the bug on the smartparens repository.
