### ISSUE TITLE
Ensime should be removed in favor of metals

### ISSUE THREAD

**Issue by gregghz** [bbatsov/prelude#1246]
Ensime has been deprecated and all work on it has stopped. https://ensime.github.io/

It should be replaced with lsp-mode and metals. https://scalameta.org/metals/

sbt-mode and scala-mode were part of the ensime project but have been pulled out into new repos. I believe they are still in melpa and so no changes should be needed for those in prelude.

**Comment by bbatsov** [comment]
@gregghz Great point! Would you be interested in tackling this?

**Comment by gregghz** [comment]
@bbatsov sure: https://github.com/bbatsov/prelude/pull/1247

**Comment by gregghz** [comment]
fixed by #1247
