### ISSUE TITLE
C-x C-e generates "End of file while parsing."

### ISSUE THREAD

**Issue by HerkOHerk** [bbatsov/prelude#1251]
Installed, updated, and then, without touching any files, ran C-x C-e, which returned "End of file while parsing."  Reinstalled three times, always with the same result.

**Comment by bbatsov** [comment]
Can you share here the complete stacktrace? Without it we can't determine where the problem is.

**Comment by HerkOHerk** [comment]
Bozhidar,

I would be more than happy to send you the stack trace, but I not longer have it.  I had begun to think that I was causing the error by mis-using` C-c C-e`.  Based on my long-ago use of Aquamacs, I was under the impression that `C-c C-e` was the “eval-buffer” command — not the “eval-region.”   Since it seemed to me that the error msg  I was getting, "End of file while parsing,” would be what one would expect if using `C-c C-e` on an entire buffer with no end-of-mark.  So, since I was just relearning Emacs after a 15 year hiatus, I didn’t have the expertise, time, or inclination to try to debug the problem, I just moved on.

I’ve read many, many good things about ‘Prelude,’ but decided to go with a different starter-package.

Thank you for following up.

Regards & Best Wishes.

Rexford Gibbs

**Comment by bbatsov** [comment]
> I would be more than happy to send you the stack trace, but I not longer have it.  I had begun to think that I was causing the error by mis-using` C-c C-e`. 

I guess that depends on the context (the major mode). I don't think that's a standard binding in elisp-mode, if you're referring to it.

> I’ve read many, many good things about ‘Prelude,’ but decided to go with a different starter-package.

No worries. I'm happy you managed to return to Emacs regardless of the starter-kit you went for. :-)
