### ISSUE TITLE
undo-tree-mode saves undo history in world-readable directory

### ISSUE THREAD

**Issue by sebleblanc** [bbatsov/prelude#1255]
Hello,
After saving a file, undo-tree-mode saves undo history in /tmp. The files have permissions `0755`, therefore any other user on the machine/server can access those files.

If a world-readable folder is used as a default location for such files, the files should be set as `0700` instead.

**Comment by bbatsov** [comment]
Isn't this something that should be tackled in `undo-tree-mode` itself?
