### ISSUE TITLE
RFC: prefer rustic-mode over rust-mode 

### ISSUE THREAD

**Issue by elmarco** [bbatsov/prelude#1256]
rustic is a fork of rust-mode, it seems to be better maintained. (I have a much more pleasant experience with it)

https://github.com/brotzeit/rustic#intro

**Comment by bbatsov** [comment]
That's fine by me. I'm not familiar with the differences, so I'll take your word for it.

**Comment by tspiteri** [comment]
It does require Emacs 26 though, so I don't know how that plays with prelude that requires 25.

**Comment by bbatsov** [comment]
Well, we can always provide 2 rust modules and people can choose which one to use. I guess some people might be fine with `rust-mode` anyways.
