### ISSUE TITLE
Install packages dont work

### ISSUE THREAD

**Issue by DeepakTivari** [bbatsov/prelude#1261]
I am trying to install a package:

I added this to my conf.el file:
; use ledger mode for files ending with ".ledger"
(package-install 'ledger-mode)
(require 'ledger-mode)

But i am getting:
Debugger entered--Lisp error: (error "package.el is not yet initialized!")
  signal(error ("package.el is not yet initialized!"))
  error("package.el is not yet initialized!")
  package-installed-p(ledger-mode nil)
  package-compute-transaction(nil ((ledger-mode)))
  package-install(ledger-mode)
  eval-buffer(#<buffer  *load*-789299> nil "/home/delta/.emacs.d/personal/preload/conf.el" nil t)  ;

I don't see any documentation or guideline to install own packages, please point me to any resource

**Comment by FredeEB** [comment]
Under Tips here:
https://prelude.emacsredux.com/en/latest/configuration/#personalizing

it says

> If you'd like to add some auto installation of packages in your personal config use the following code:
> 
>` (prelude-require-packages '(some-package some-other-package))`
> 
> If you require just a single package you can also use:
> 
> `(prelude-require-package 'some-package)`

So you'd do:
`(prelude-require-package 'ledger-mode)`

**Comment by DeepakTivari** [comment]
This is exactly what i put in my custom conf.el
`; Install ledger-mode package
(prelude-require-package 'ledger-mode)`

However this is the error i got:

Symbol's function definition is void: prelude-require-package

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.

**Comment by ryukinix** [comment]
@DeepakTivari 

You need to add on top of you conf.el:

```emacs-lisp
(require 'prelude-package)
```

Which means:

```emacs-lisp
(require 'prelude-package)
(prelude-require-package 'ledger-mode)
```

See a full functional example [here].

[here]: https://github.com/ryukinix/dotfiles/blob/89d8c0bfd76843809bd8653966694401b5144ac9/.emacs.d/personal/modes.el#L2-L13
