### ISSUE TITLE
Any plan to add dart or flutter support?

### ISSUE THREAD

**Issue by cassc** [bbatsov/prelude#1262]

**Comment by bbatsov** [comment]
No specific plans, but PRs are always welcome. :-)

**Comment by rafamedina** [comment]
Maybe https://emacs-lsp.github.io/lsp-dart/

**Comment by bbatsov** [comment]
That'd be fine by me.

**Comment by bbatsov** [comment]
Dart support has been added recently. Check `prelude-dart.el` for more details.
