### ISSUE TITLE
Prelude/Helm - Allow disabling of "Emacs Commands History"

### ISSUE THREAD

**Issue by ricardoaiglesias** [bbatsov/prelude#1264]
When using `Helm-M-x`, I find myself often needing to press `C-o` to get to the command/function I wish to execute. I tried looking around the prelude and helm documentation but was unable to find a way to either remove the "Emacs Command History" or have it automatically switch to the "Emacs Commands" part of the search results. 

I attempted to use "helm-next-source" (what `C-o` is mapped to) but was unable to get the elisp to execute without error (below):
````
(global-set-key (kbd "M-x") (lambda (arg)
                              (interactive "P")
                              (helm-M-x arg) 
                              (helm-next-source)))
````
This gives me an error of "Wrong number of arguments: (1 . 1) 0".

Attached is a screenshot of an example where I want to match with the functions on the bottom, but need to press `C-o` to get to the correct function. 

If it helps, I have fuzzy-matching turned OFF by default, since it wasn't useful for me. 
![Screenshot from 2020-05-27 19-20-44](https://user-images.githubusercontent.com/20539793/83091541-3ed20300-a050-11ea-9cdb-a7e460935289.png)

**Comment by ryukinix** [comment]
You can do a better hack by doing this:

```emacs-lisp
(advice-add 'helm-M-x :before
            (lambda (_)
              (setq-local extended-command-history nil)))
```

This basically erases all your Emacs Command History buffer-local before triggering the helm meta-x menu. I tested in my machine and worked fine.

**Comment by russell** [comment]
Helm provides a mechanism to change this, if you set `helm-M-x-reverse-history` to `t` then the history will always appear after the regular command list

```
(setq helm-M-x-reverse-history t)
```

In regards to how you would discover this, I recommend using `M-x customize-apropos` then enter a search term, it builds a custom collection of configurable values that are exposed by package developers, you can then search that buffer, or use it to find the configuration group of the package your looking at.

The fact your seeing `Wrong number of arguments: (1 . 1) 0` is a bit worrying, i would try getting a new copy of helm.  you could either update it individually or use the `prelude-update` command https://prelude.emacsredux.com/en/latest/troubleshooting/#updating-bundled-packages

If you still keep seeing the error you can enter a global debug on error mode using `M-x toggle-debug-on-error` if you trigger the error, then you should see a stack trace that could help you understand why your seeing the error.
