### ISSUE TITLE
prelude-pinned-packages.el

### ISSUE THREAD

**Issue by Gahamelas** [bbatsov/prelude#1265]
What is exactly prelude-pinned-packages.el doing?
Is it keeping these packages from not updating or keeping them to a stable version?

**Comment by bbatsov** [comment]
See https://prelude.emacsredux.com/en/latest/installation/#pinning-packages

Very simply put - it specifies the repository from which a package should be installed (in the provided sample it uses MELPA Stable for everything that normally comes from MELPA).

**Comment by Gahamelas** [comment]
Thanks! 

If I have this on my Init as the only package-archive:

`             '("melpa-stable" . "https://stable.melpa.org/packages/"))
`

I wouldn't need the pinned packages, since all packages would be only updated that come from stable melpa. Is this correct?
Thanks,
GM

**Comment by bbatsov** [comment]
Yeah, you don't.
