### ISSUE TITLE
sh: line 177: [: -lt: unary operator expected

### ISSUE THREAD

**Issue by wildeyes** [bbatsov/prelude#1266]
Getting `sh: line 177: [: -lt: unary operator expected` on running the install script on macos.

**Comment by nihilismus** [comment]
@wildeyes in the same terminal where you get the error, what's the full output of `emacs --version`? Is `emacs` already installed? What's the output of `which emacs` in a terminal?

**Comment by duckwork** [comment]
Hey, I made a pull request for a naive fix: https://github.com/bbatsov/prelude/pull/1282. Sorry I am rusty with Github's PR flow.
