### ISSUE TITLE
org-set-tags-command does not remove tags

### ISSUE THREAD

**Issue by iburunat** [bbatsov/prelude#1268]
I'm having an issue regarding `org-set-tags-command` (`C-c C-c` on heading) since I upgraded Prelude, potentially a bug (?). This means I can't remove a tag using `org-set-tags-command`, as I am forced to choose one of the predefined tags. I used to be able to remove the tag and click `RETURN` without selecting any tag.

**Comment by bbatsov** [comment]
Probably it's a bug unrelated to Prelude (e.g. in `org-mode`), as I don't think we've made any related changes recently.

**Comment by iburunat** [comment]
Thanks, I'll have a look there.
