### ISSUE TITLE
Can't drag and drop ORG files from Finder as Emacs creates a downloaded copy

### ISSUE THREAD

**Issue by iburunat** [bbatsov/prelude#1269]
Whenever I drag and drop an `ORG` file from Finder to the Emacs window, I get the following message in buffer:

```
#+DOWNLOADED: file:/path/to/file/myorgfile.org @ 2020-07-06 08:41:34
[[file:2020-07-14_08-41-34_myorgfile.org]]
```
Then I click on it and it opens the saved org file, which is a duplicate of the original. 
I am not sure if this is to do with Prelude or `ORG` behaviour. When instead of drag-and-dropping the ORG file on the Emacs window, I right-click to open it in Emacs, it starts a new instance of Emacs.

How to enable Emacs to open my original ORG files without any prompt?

**Comment by iburunat** [comment]
Hi! Any response to this issue, anybody?

**Comment by bbatsov** [comment]
I guess that comes from org itself, as Prelude doesn't really modify it. I never use drag-and-drop functionality with Emacs, so I can't say much on the topic.

**Comment by iburunat** [comment]
Thanks, I'll investigate around.
