### ISSUE TITLE
Consider not disabling menu-bar-mode by default

### ISSUE THREAD

**Issue by cadadr** [bbatsov/prelude#1278]
Hi all!

As some of you might be aware, there's discussion regarding making Emacs more approachable to newcomers, over on emacs-devel. Distributions of Emacs are part of the discussion, and it's a common conclusion that projects like yours are very helpful in this regard and there are ideas about collaboration and support.

As part of those discussions, trying to spot what some common patterns might be hiding some otherwise more discoverable functionality in Emacs, we came to the conclusion that the menu bar is important as a tool for discovering functionality, both a fixed set, and minor/major mode related stuff.

This is of course not a catch-all fix to the problems of the newcomers, and a lot of ideas are being produced around how to solve other, more major problems, but not disabling menu-bar-mode by default seems to be a step in the right direction.

So we thought that recommending distributions that seem to disable it by default to consider leaving that to the user instead. If you want to read more on the discussions, or contribute your views, please don't hesitate to do so on the emacs-devel mailing list.

**Comment by bbatsov** [comment]
The suggestion is fine by me. That's a remnant of the days where Emacs users were taking pride in the fact they didn't need the menu bar. :smile:

**Comment by cadadr** [comment]
Thanks!

So how do we do it? I don't use prelude so I'm not really familiar with it but it seems like removing [this line](https://github.com/bbatsov/prelude/blob/dd9b01a991c9599842ba88e52fe6ae8627f4a782/core/prelude-ui.el#L42) would do.  In any case I can prepare a PR if you want.

**Comment by bbatsov** [comment]
I'll take care of this.

**Comment by cadadr** [comment]
:+1:

**Comment by bbatsov** [comment]
Now it's enabled by default and the old behavior can be obtained by setting `prelude-minimalistic-ui` to `t`.

**Comment by cadadr** [comment]
Thanks!

**Comment by manuq** [comment]
I had a hard time understanding how to set the minimalistic mode. Maybe is better to be explicit in the documentation and give a snippet? Like "Create a `personal/preload/custom.el` file with the following content:"

```
(custom-set-variables
 '(prelude-minimalistic-ui t))
```
