### ISSUE TITLE
c++-mode disappear

### ISSUE THREAD

**Issue by yszhang95** [bbatsov/prelude#1285]
Hello experts

I am a newbie of emacs. After cloning `prelude-emacs` from github, 
and make `prelude-modules.el` in `personal` directory, I found I cannot find
`c++-mode` via `M-x`. Removing `prelude-modules.el` in `personal` directory will
get `c++-mode` back.

Is it an expected feature? Or did I make any mistakes?

Best reagards

## Expected behavior
```
M-x c++-mode RET
```
will enable `c++-mode`.
## Actual behavior
cannot find `c++-mode`, only `c-mode` appear in mini buffer. And no warning.
## Steps to reproduce the problem
In shell,
```
$ curl -L https://github.com/bbatsov/prelude/raw/master/utils/installer.sh | sh
$ mv /Users/yszhang/.emacs.d/sample/prelude-modules.el ~/.emacs.d/personal/prelude-modules.el
```
Open emacs and quit. Open eamcs again,
and then tryp `M-x c++-mode`.

### Emacs version
`Emacs 27.1`, installed via `sudo port install emacs-app`, on iMac.
`Emacs 27.1`, install via `sudo dnf install emacs`, on `VirtualBox`

### Operating system
Fedora 32 and OSX

**Comment by bbatsov** [comment]
Seems like some issue with `counsel`/`ivy` not being able to interpret a string with `+` signs properly, or that might be expected given those pluses have special meaning in regular expressions. If you start typing `c\+` you'll see `c++-mode` there. @abo-abo might have better suggestions how to handle this.

**Comment by bbatsov** [comment]
I guess we can close this.
