### ISSUE TITLE
How to disable super-save-mode, globally?

### ISSUE THREAD

**Issue by voland62** [bbatsov/prelude#1288]
I really tryed many ways, bun it always on, and I need to call it once every time I start emacs...
Seems lile I miss something...

**Comment by bbatsov** [comment]
Doesn't adding `(super-save-mode -1)` in your config disable it permanently?

**Comment by voland62** [comment]
Wow, works! Thnx.

P.S. Now days, you always work with some sort of hot reload - which recompiles(your **big** project) on any changes in source tree... So I try turn off all this auto-saves, auto-backups, interlocking, flychecks....
