### ISSUE TITLE
What is the best way to disable prelude-python-mode-set-encoding?

### ISSUE THREAD

**Issue by ryukinix** [bbatsov/prelude#1292]
That feature it's annoying to be used on `python3` because it's no longer necessary. On the current year, 2020, python2 is officially deprecated. I know that adding this prevents people using python2 having problem, but is not my case. I'm having problem to get my work accepted sometimes because I have that auto inserted line:

```
# coding: utf-8
```

In general is unrelated to the patch I sent and frequently on code review is requested to delete this. (unnecessary headaches)

So I'm asking how I can disable that auto-insertion using `prelude-python` module properly without the need to hack my own prelude version and giving me problems to update later. Currently, I just deleted that line:

https://github.com/bbatsov/prelude/blob/041617e8b017191044fec517003ac34b2066e139/modules/prelude-python.el#L100

But is not optimal. It would better if it have a variable to turn it off.

**Comment by bbatsov** [comment]
Probably we should add a defcustom for this and disable it by default. 

In the mean time you can just use `remove-hook` in your personal config.

**Comment by ryukinix** [comment]
> In the mean time you can just use remove-hook in your personal config.

I tried that but didn't worked as expected, because that hook is inserted by another `python` hook here: 

https://github.com/bbatsov/prelude/blob/041617e8b017191044fec517003ac34b2066e139/modules/prelude-python.el#L104-L105

So I would need to remove the entire `prelude-python-mode-hook` to get a effective change. 

> Probably we should add a defcustom for this and disable it by default.

I agreed. If I made a PR, do you will accept it?

**Comment by bbatsov** [comment]
Sure.

**Comment by ryukinix** [comment]
Ok, I'll fix it.

**Comment by ryukinix** [comment]
One doubt @bbatsov to make our code review easier later.

> Probably we should add a defcustom for this and disable it by default.

1. You mean something like `prelude-python-mode-set-encoding-toggle` and be nil as default, right? That way the default behavior will not insert `# coding: utf-8` anymore.

2. You mean ` prelude-python-mode-set-encoding-disable` and be nil as default?

Can you confirm to me what option do you prefer?

**Comment by bbatsov** [comment]
I meant 1)

I'd name the `defcustom` `prelude-python-mode-set-encoding-automatically`.

**Comment by ryukinix** [comment]
Thanks for answering! Good name.

**Comment by ryukinix** [comment]
PR submitted, @bbatsov. Review it when you can.
