### ISSUE TITLE
How to auto remove packages didn't need anymore?

### ISSUE THREAD

**Issue by wd** [bbatsov/prelude#1295]
I use `prelude-require-packages` to install packages I need, but seems the packages will still exists and load by emacs after I removed from the list, and the `packages-autoremove` says no packages need to remove.

So what's the right way to mange my packages?

**Comment by wd** [comment]
Seems I can remove `elpa` directory and `personal/custom.el` and restart emacs to reinit again to delete un-needed packages.

**Comment by bbatsov** [comment]
Yeah, nuking the `elpa` directly is probably the simplest way to get to a clean slate. Otherwise you'll have to un-install packages one-by-one.

> and the packages-autoremove says no packages need to remove.

I think it only removes packages that were auto-installed as deps.
