### ISSUE TITLE
Custom whitespace-line-column for specific modes

### ISSUE THREAD

**Issue by shixiongfei** [bbatsov/prelude#1300]
I want to force whitespace-mode highlight line after 80 characters in racket-mode. 

For other modes I want to leave this variable with default value(80). How can i do this?

I tried `(add-hook 'rack-mode-hook (lambda () (setq-local whitespace-line-column 102)))` but it didn't work

**Comment by bbatsov** [comment]
Your approach seems correct to me. What's the value of the `whitespace-line-column` in those racket buffers in question? (meaning does the `setq-local` seem to change it)

**Comment by shixiongfei** [comment]
The following is my configuration of Racket.

```
(prelude-require-packages '(racket-mode))

(require 'prelude-lisp)

(with-eval-after-load 'racket-mode
  (define-key racket-mode-map (kbd "M-RET") 'racket-run)
  (define-key racket-mode-map (kbd "M-.") 'racket-repl-visit-definition))

(add-hook 'racket-mode-hook #'racket-unicode-input-method-enable)
(add-hook 'racket-repl-mode-hook #'racket-unicode-input-method-enable)

(add-hook 'racket-mode-hook (lambda () (run-hooks 'prelude-lisp-coding-hook)))
(add-hook 'racket-mode-hook (lambda () (setq-local whitespace-line-column 102)))

(add-to-list 'auto-mode-alist '("\\.rkt$" . racket-mode))
(add-to-list 'auto-mode-alist '("\\.rkt?\\'" . racket-mode))
(add-to-list 'auto-mode-alist '("\\.rkt\\'" . racket-mode))

(provide 'prelude-racket)
```

The value of `whitespace-line-column` cannot be changed when using `setq-local` alone, it is still 80 in Racket mode.

When I use `setq` instead of `setq-local`, it works normally. But other modes have also been changed.

**Comment by bbatsov** [comment]
I can't imagine how this would happen with a buffer-local variable. I guess I'll test this myself when I can.

**Comment by shixiongfei** [comment]
Thank you very much for your time! :)
