### ISSUE TITLE
How to colapse or hide activated minor modes.

### ISSUE THREAD

**Issue by havocwave** [bbatsov/prelude#1301]
I just installed prelude, but there are so many minor modes activated that they don't fit within my Emacs frame.

How can I collapse them or hide them?

**Comment by bbatsov** [comment]
You can hide the modes you don't want to see with code like this added your personal setup:

```
(diminish 'some-minor-mode)
```

**Comment by bbatsov** [comment]
You reminded me to clean up the modeline a bit in general https://github.com/bbatsov/prelude/commit/0ebba48c9322a7d0fb4926b65e4b00d2f3737ad2
