### ISSUE TITLE
Theme tabs

### ISSUE THREAD

**Issue by manuq** [bbatsov/prelude#1313]
**Is your feature request related to a problem? Please describe.**

Emacs 27.1 comes with a great native tab bar, including the `global-tab-line-mode` that activates tabs as users from IDEs would feel at home. However they are not themed in Prelude:

![prelude-tabs](https://user-images.githubusercontent.com/83944/104763502-c20da980-5744-11eb-9ced-b8af02366581.png)

**Describe the solution you'd like**

Theme the tabs so they look nice in Prelude. Here is an example of how to do it: https://amitp.blogspot.com/2020/06/emacs-prettier-tab-line.html

**Comment by manuq** [comment]
Hmm maybe I should open a ticket in the `zenburn-emacs` project instead?

**Comment by bbatsov** [comment]
Yeah, it seems some faces for tab-line need to be added there. I've never used this mode, but I'd happily accept a PR.

**Comment by manuq** [comment]
> Yeah, it seems some faces for tab-line need to be added there. I've never used this mode, but I'd happily accept a PR.

Challenge accepted! :-) I will see what can I do.

**Comment by bbatsov** [comment]
I'll close this one as it's not directly related to Prelude.
