### ISSUE TITLE
Problems with helm-follow-mode: can't enable it interactively

### ISSUE THREAD

**Issue by AtomicNess123** [bbatsov/prelude#1316]
I have installed the last version of Prelude from scratch.
I have enabled both helm packages in my personal dir. Any help welcome.
In my init file I have `(setq helm-follow-mode-persistent t)`

Before this upgrade, I could enable `M-x helm-follow-mode` interactively, but after the upgrade, I can't.
I can't finde M-x helm-follow-mode (it does not show up as candidate, even though it should). 
Also the key binding `C-c C-f `is not binded to it (although when I `C-h f helml-follow-mode` it shows up in the buffer indicating that it exists and it is binded to that).

So before I could see the buffers when I scrolled though the candidate ones in the minibuffer, but not anymore.
I wonder what is wrong. 
Thanks for the help.

**Comment by bbatsov** [comment]
Might be some issue with the autoloads generation. If you can't see a command when doing `M-x` the reason is always the same - it's either not required or not autoloaded.
