### ISSUE TITLE
Use `display-line-numbers-mode` instead of nlinum for recent emacs

### ISSUE THREAD

**Issue by legendre6891** [bbatsov/prelude#1317]
**Is your feature request related to a problem? Please describe.**

Emacs 26 and newer has a built-in `global-display-line-numbers-mode` that is more performant than `nlinum-mode`.

**Describe the solution you'd like**

In `core/prelude-ui.el`, check for the Emacs version number, and instead of `(global-nlinum-mode t)` we could use `(global-display-line-numbers-mode)` instead.

**Describe alternatives you've considered**

We could keep the same behavior.

**Additional context**

See https://emacs.stackexchange.com/questions/278/how-do-i-display-line-numbers-in-emacs-not-in-the-mode-line

**Comment by bbatsov** [comment]
That's fine by me. PR welcome!

**Comment by legendre6891** [comment]
Awesome! Will send a PR sometime this week(end).

**Comment by legendre6891** [comment]
PR at #1318
