### ISSUE TITLE
Startup issue: lsp-mode not found

### ISSUE THREAD

**Issue by rickerbh** [bbatsov/prelude#1324]
## Expected behavior

Starting up emacs results in no warnings on initialisation

## Actual behavior

Starting up results in the following error

```
Warning (initialization): An error occurred while loading ‘/Users/rickerbh/.emacs.d/init.elc’:

File error: https://melpa.org/packages/lsp-mode-20210311.814.tar, Not found

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the ‘--debug-init’ option to view a complete error backtrace.
```

## Steps to reproduce the problem

I had installed prelude only 2 days ago, and had the issue as described in https://github.com/bbatsov/prelude/issues/1320.
I saw that issue had been closed and then in emacs ran `M-x prelude-update`
Restarted emacs, and the above error popped up

### Emacs version

GNU Emacs 27.1 (build 1, x86_64-apple-darwin18.7.0, NS appkit-1671.60 Version 10.14.6 (Build 18G95)) 

### Operating system

macOS Big Sur 11.2.3

**Comment by bbatsov** [comment]
You can try `M-x package-refresh-packages`. I'm assuming there's a newer version available or something like this.

**Comment by rickerbh** [comment]
I refreshed and manually installed. Warning gone. Thanks!
