### ISSUE TITLE
<right> keybinding is discouraged! Use <C-f> instead

### ISSUE THREAD

**Issue by cloudbuck3t** [bbatsov/prelude#1341]
Hi, I like to use the arrow keys and this message 
`<right> keybinding is discouraged! Use <C-f> instead`
is quite distracting.  Also, why are 2 keypresses superior to one?  I don't get it.  How can I disable this message?

I would like a default option for Prelude to not include such messages in the future

**Comment by bbatsov** [comment]
See https://prelude.emacsredux.com/en/latest/troubleshooting/#warnings-on-arrow-navigation-in-editor-buffers

**Comment by cloudbuck3t** [comment]
Thanks, I was able to add `(setq prelude-guru nil)` to my ~/.emacs.d/init.el successfully.
