### ISSUE TITLE
startup time, not an issue, 

### ISSUE THREAD

**Issue by wereket** [bbatsov/prelude#1342]
Hello
Wat is the average startup time ?
Isi it possible to lower prelude startup under 3 seconds,actualy mine is 5.17sec
Thank you for your time

**Comment by bbatsov** [comment]
I never bothered to measure it, as it will depend on the modules one has selected, plus I typically spend days/weeks in a single Emacs session. Generally fewer modules + deferred loading are the simplest ways to improve the startup time.
