### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by hut8** [bbatsov/prelude#1365]
A few documentation issues:

* I added doc/modules/go.md as a part of the prelude-go changes. While I had been working on that branch, the docs were moved from doc/ to docs/.
* I never updated `mkdocs.yml`. Oops.
* When doc/ got moved to docs/, the symlink for prelude-cheatsheet.pdf was not updated in the root, so it is currently broken.
* F# was not anywhere in `mkdocs.yml`; it was a recently documented module so I'll add that too.

Do you want a GitHub action to have the mkdocs documentation automatically deploy? Or do you just want to do it manually?

**Comment by bbatsov** [comment]
> Do you want a GitHub action to have the mkdocs documentation automatically deploy? Or do you just want to do it manually?

There's a hook that regens the docs automatically after each merge/commit (that's done by RTD).

**Comment by hut8** [comment]
Beautiful. Thanks for merging the fixes!
