### ISSUE TITLE
Please change Rust default LSP into Rust-Analyzer.

### ISSUE THREAD

**Issue by Mika-Lahtinen** [bbatsov/prelude#1374]
Rust-analyzer provides better experience than RLS when coding in Rust, however, I don't really clear how to make the change, any advice?

**Comment by hntrmrrs** [comment]
I followed this advice: https://robert.kra.hn/posts/rust-emacs-setup/

To integrate with prelude, I made a module that is almost copied verbatim from his standalone `init.el` file: https://github.com/rksm/emacs-rust-config/blob/master/init.el

**Comment by bbatsov** [comment]
@hntrmrrs PR welcome!

**Comment by hntrmrrs** [comment]
Will do! Are you OK with switching the default from rls to rust-analyzer and rustic?

**Comment by hntrmrrs** [comment]
@bbatsov Otherwise, I'll probably define a customization variable which switches to using rustic and rust-analyzer.

**Comment by bbatsov** [comment]
@hntrmrrs It's fine to have only `rust-analyzer` and `rustic`.
