### ISSUE TITLE
Versions missing for `orderless` and `consult`

### ISSUE THREAD

**Issue by cassiel** [bbatsov/prelude#1415]
## Expected behavior

Clean startup.

## Actual behavior

```
Warnings:
Error (use-package): Failed to install orderless: https://melpa.org/packages/orderless-20240320.1638.tar: Not found
Error (use-package): Cannot load orderless
Error (use-package): Failed to install consult: https://melpa.org/packages/consult-20240323.2016.tar: Not found
```

## Steps to reproduce the problem

Normal startup.

### Emacs version

27.1.

### Operating system

Ubuntu 22.04.4 LTS, arm64 under VMware.

**Comment by cassiel** [comment]
Actually: reported errors on the first couple of launches, now silent and seems to work fine.

**Comment by bbatsov** [comment]
Running `package-refresh-package-list` solves such problems - your local package list was out of sync with the remote.

**Comment by cassiel** [comment]
Noted - thanks - sorry for the noise.
