### ISSUE TITLE
retain tabs/spacing

### ISSUE THREAD

**Issue by bfouts** [bbatsov/prelude#185]
this may have been answered before, but i was unable to find it. 

so i know that it is the best thing in the world that prelude does a lot of cleanup on files, but unfortunately in some cases it is a disaster when working on projects that may have legacy code, etc.  The downside is a small change to a source file can end up being a dramatic change in the source.  in my particular case we separate out formatting changes as there own commits.  is there a way to toggle the "cleanup" features on/off or just outright stop them from occurring when using prelude?

**Comment by akaihola** [comment]
None of the recipes mentioned above disable trailing white space removal for me. I have emacs 26.1.6 and prelude updated ot 2018-11-21.

**Comment by akaihola** [comment]
**But,** as seen in commit 2860441f7e4289606ead46e2ce4876baa58a711e, this does work:
```
M-: (setq prelude-clean-whitespace-on-save nil)
```

This came handy when editing some PostgreSQL database dumps – the `COPY` command expects to see the correct number of tab delimiters even if trailing fields have empty values.
