### ISSUE TITLE
prelude cheat sheet to welcome new users to prelude for emacs

### ISSUE THREAD

**Issue by akshatpradhan** [bbatsov/prelude#221]
Another way the TextMate community makes their text editor very welcoming is by creating a PDF cheat sheet. 
http://www.g-design.net/textmate.pdf

It would be great to have a prelude cheat sheet. I think people would feel more welcomed into our community. I also don't think the current emacs cheat sheets out there are good enough. Prelude has some short cuts that make coding a lot of fun. 

For example, C-c p f would never be documented in the current cheat sheets, but people love those kinds of features. 

I can create a PDF like this, but I would need you to write out all the commands for me. I'm still a bit new with prelude. 

What do you think?

**Comment by HenrryPires** [comment]
I am very new using Emacs. Can any tell me what does this mean? ⌘N

**Comment by arbox** [comment]
That means that on your Mac you have to push and hold the command button, then press N and release both keys.

**Comment by HenrryPires** [comment]
Tks arbox. I have windows so I need to find cheat sheet :)

**Comment by arbox** [comment]
Ok, then you'd rather use Ctrl button instead of Command und Alt instead of Option. In some docs Alt is called Meta.

**Comment by HenrryPires** [comment]
Cool many tks for such a quick answer
