### ISSUE TITLE
Error during download request: Not Found

### ISSUE THREAD

**Issue by ershadc** [bbatsov/prelude#296]
I just installed emacs24 and Prelude. When I start emacs I get the "Error during download request: Not Found". I started emacs in the debug mode and the following message appeared. 

"

Debugger entered--Lisp error: (error "Error during download request: Not Found")
  signal(error ("Error during download request: Not Found"))
  error("Error during download request:%s" " Not Found")
  package-handle-response()
  package-download-tar(flycheck "20130404.1846")
  package-download-transaction((flycheck))
  package-install(flycheck)
  funcall(package-install flycheck)
  (let ((it (car list))) (funcall fn it))
  (while list (let ((it (car list))) (funcall fn it)) (setq it-index (1+ it-index)) (setq list (cdr list)))
  (let ((list list) (it-index 0)) (while list (let ((it (car list))) (funcall fn it)) (setq it-index (1+ it-index)) (setq list (cdr list))))
  -each((flycheck gist git-commit-mode gitconfig-mode gitignore-mode guru-mode helm helm-projectile magit melpa rainbow-mode solarized-theme undo-tree volatile-highlights yasnippet zenburn-theme) package-install)
  prelude-install-packages()
  require(prelude-packages)
  eval-buffer(#<buffer  *load*> nil "/home/ershad/.emacs.d/init.el" nil t)  ; Reading at buffer position 3414
  load-with-code-conversion("/home/ershad/.emacs.d/init.el" "/home/ershad/.emacs.d/init.el" t t)
  load("/home/ershad/.emacs.d/init" t t)
  #[0 "\205\262

"

How do I fix this issue? 

Thank you

**Comment by freizl** [comment]
thanks! :+1:
