### ISSUE TITLE
Some keybindings don't work in terminal mode

### ISSUE THREAD

**Issue by Abizern** [bbatsov/prelude#327]
Some of the standard keybindings don't work when I'm running Emacs in Terminal mode.

For example:

C-= doesn't bring up expand region
M-/ doesn't bring up hippie expand (and yes, I am using the esc key instead of M in terminal mode)
C-/ doesn't undo.

The commands do work as invoking them with M-x (or C-x C-m) is okay.

Running on OS X with zsh.

**Comment by liuchong** [comment]
To solve the conflict of "C-c o" between prelude-mode and term, I've added a hook like this:
---------------------------------------
;; unset "C-c o" in term-mode
(add-hook 'term-mode-hook
	  (lambda()
	    ;; (prelude-mode -1)
	    ;; or
	    (prelude-off)
	    (message "%s" "Turn off prelude-mode in term-mode to avoid conflict.")
	    ))
