### ISSUE TITLE
grey background of emacsclient 

### ISSUE THREAD

**Issue by thnbp24** [bbatsov/prelude#423]
Hi,

Even if I use (set-background-color "black"), the background color of emacsclient is still grey. The background color of emacs is set properly, but not emacsclient.
Any idea how I can change the background color of emacsclient?
I use "emacsclient -nw" since I run it in a terminal. Other commands, such as "emacsclient -t" can also reproduce the issue.
My OS is ubuntu 12.04 and emacsclient is opened in the default terminal.
Thanks.

**Comment by cad106uk** [comment]
I have this problem as well. Did you ever find a solution?
