### ISSUE TITLE
~/.emacs.d/themes not on custom-theme-load-path

### ISSUE THREAD

**Issue by markjfisher** [bbatsov/prelude#438]
I've got a default git install with only the following lines in personal/start.el

```
(add-to-list 'custom-theme-load-path "~/.emacs.d/themes/")
(disable-theme 'zenburn)
(load-theme 'noctilux t)
```

I've put the 2 noctilux files in themes dir.

According to http://batsov.com/articles/2012/02/19/color-theming-in-emacs-reloaded/ the themes dir should already be part of the custom-theme-load-path, but doesn't appear to be as the above errors if I comment out the (add-to-list ...) line above saying it can't find noctilux.

**Comment by benklebe** [comment]
So if we want to install themes that aren't packaged should we put them directly into our ~/.emacs.d/personal/preload ?
