### ISSUE TITLE
Tracking installed packages using cask/pallet

### ISSUE THREAD

**Issue by lotia** [bbatsov/prelude#444]
Newcomer to prelude. Wondering if there's a way to track packages you've already installed in your fork using something like pallet or cask? If not, although my elisp is rubbish, I can certainly attempt to provide such functionality if people would consider it useful.

To clarify:

You install a package, that installation is appended to a file in your personal folder.

When you set up prelude on a new machine using your fork of prelude, it checks to see if that file is present and also installs the packages tracked in that file.

**Comment by am** [comment]
@avdi so is there any recommendation how to have Pallet  to work nice with prelude?
