### ISSUE TITLE
disable flycheck-mode 

### ISSUE THREAD

**Issue by jbulow** [bbatsov/prelude#508]
The default settings for flycheck-mode is often broken on platforms like ubuntu and OS X for things like python and make files. It's not obvious how to disable flycheck-mode. Trying (global-flycheck-mode nil) does not work in personal init file.

What is the right way to disable flycheck-mode when using prelude?

**Comment by taquangtrung** [comment]
Adding `(remove-hook 'prog-mode 'flycheck-mode)` to the `personal.el` does not work for me.

What I did is to adding the following into the `personal.el` file.
It works, but I'm not sure if it is the right way to do it:

```
(defun disable-flycheck-mode ()
  (interactive)
  (flycheck-mode -1))
(add-hook 'prog-mode-hook 'disable-flycheck-mode)
```

**Comment by lunaryorn** [comment]
@taquangtrung You should be using `(global-flycheck-mode -1)` instead.

**Comment by ajohnston1219** [comment]
@lunaryorn why should he be using `(global-flycheck-mode -1)` instead? I tried using that and it doesn't work, but @taquangtrung 's method does work.
