### ISSUE TITLE
Way to override prelude-*-mode-defaults

### ISSUE THREAD

**Issue by prettynatty** [bbatsov/prelude#519]
I am trying to disable haskell-mode-indentation which is being turned on by prelude by default. Is there a way to override this behaviour? I tried many ways, for instance:

``` elisp
(require 'prelude-programming)

(defun override-prelude-haskell-mode-defaults ()
  (subword-mode +1)
  (turn-on-haskell-doc-mode)
  ;(haskell-mode-indentation nil))
)
(setq prelude-haskell-mode-hook 'override-prelude-haskell-mode-defaults)
```

but my override doesn't even being executed.

**Comment by dmh43** [comment]
A few years late on this one but i think it's still relevant. My understanding is that hooks should be lists (or in general added with `add-hook`). My way of disabling prelude-*-mode-defaults is by removing the hook with `remove-hook` and then adding my own function with add-hook. I feel like there has to be a cleaner way, but this works for now

**Comment by cfclrk** [comment]
I've settled on an approach like this:

```elisp
(defun my-haskell-mode-hook ()
  (haskell-indentation-mode -1))

;; Run my-haskell-mode-hook after prelude-haskell-mode-defaults, because my
;; hook overrides some things in the prelude hook.
(setq prelude-haskell-mode-hook '(prelude-haskell-mode-defaults
                                  my-haskell-mode-hook))
```
