### ISSUE TITLE
yasnippet not installed and enabled by default

### ISSUE THREAD

**Issue by vampolo** [bbatsov/prelude#527]
Hi,
I've just installed prelude via 

```
curl -L http://git.io/epre | sh
```

And i noticed that yasnippet is missing and thus not activated (I've tried with javascript files)

I've fixed adding these lines to my init.el

```
(prelude-require-package 'yasnippet)
(yas-global-mode 1)
(define-key yas-minor-mode-map (kbd "<tab>") nil)
(define-key yas-minor-mode-map (kbd "TAB") nil)
(define-key yas-minor-mode-map (kbd "C-<tab>") 'yas-expand)
```

The key map is to have yasnippet be nice with autocomplete.

**Comment by lartpang** [comment]
And now?
Do you still think yasnippet is still not suitable for Prelude? 
This package is really practical, and I really want to be able to support it.
@bbatsov
