### ISSUE TITLE
Ergoemacs module

### ISSUE THREAD

**Issue by alexeyr** [bbatsov/prelude#589]
It might be useful to add a small Ergoemacs module to Prelude (basically activating Ergoemacs and binding undo-tree's undo/redo). If you'll accept one, I'd be happy to contribute it.

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and I'm spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. 

To be perfectly clear - I think that's a good idea in general and I'll gladly review a PR, but it's unlikely that I'll tackle this myself in the foreseeable future. Hopefully my response is going to inspire someone else to work on this! 😉
