### ISSUE TITLE
Simple tramp with sudo hangs on 'Sending password'

### ISSUE THREAD

**Issue by vampolo** [bbatsov/prelude#594]
Hi.

Was trying a simple 

```
C-x C-f /sudo::/etc/hosts
```

on a just updated _prelude_ but it hangs on **Tramp: Sending Password** without actually asked for one like in this image

![screenshot 2014-07-02 23 55 54](https://cloud.githubusercontent.com/assets/294496/3462967/ef2ad6da-0233-11e4-8444-b0c94473ebfd.png)

Started with `emacs -q` i was able to successfully open /etc/hosts with sudo and emacs asked me for the password correctly.
Am I the only one experiencing this ?

**Comment by hotshotguy** [comment]
Setting variable `projectile-mode-line` to `nil` fix this problem to me
I'm using emacs 24.4 on Debian 7

**Comment by dowcet** [comment]
(setq projectile-mode-line " Projectile")` also works: https://github.com/bbatsov/projectile/issues/523

**Comment by jgarvin** [comment]
I can both confirm this issue in emacs 24.4.1 and that the projectile-mode-line fix suggested by @dowcet works.

**Comment by spaceotter** [comment]
I'm struggling with this too. If I navigate to a system file, it automatically tries to access with sudo, and then there is a good chance I won't be able to use Emacs after that.

**Comment by junjiemars** [comment]
comments out or ```(setq projectile-global-mode nil) is not working for me, but the following 
```elisp
(projectile-global-mode)
(set projectile-mode-line " Projectile")
```
is just work, I think the projectile-mode-line would conflicts with tramp.

**Comment by emelin** [comment]
Thank you for testing and commenting on this nasty, sustaining issue here!

JUST hacking projectile's mode-line as above has been mentioned several times.

However, this very simple code snippet using /sudo::  (while employing  org-babel or not) will hang:

    #+begin_src shell :dir /sudo::
       hostname
       whoami
    #+end_src

It will hang and only hang when projectile-global-mode is switched on, no matter what hack is applied to mode-line by stating: 

    Decrypting /Users/admin/ ... /authinfo.gpg...done
  
and then , after canceling with C-g print this in *Messages* 

    Tramp: Waiting for prompts from remote shell...failed
    Tramp: Opening connection for root@on27 using sudo...failed

If you simply switch off projectile-global-mode, tramp works flawlessly. 

projectile-global-mode remains the culprit and something should be done about it.

**Comment by stardiviner** [comment]
I meet this issue too on latest version projectile in MELPA today.
Why this problem is not fixed yet? weird

**Comment by seagle0128** [comment]
The issue still exists. I am using emacs 24.5 and 25.0 with the latest projectile. Have to disable projectile :(

**Comment by tangxinfa** [comment]
This problem coming to Emacs 27, it occurs when `projectile-mode` and
`ibuffer-auto-mode` enabled on ibuffer.
-

**Comment by andres-moreno** [comment]
This problem is happening on emacs-snapshot: GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2019-07-25

Ubuntu 18;04

It doesn't matter whether nor not projectile is enabled.

**Comment by asifhg** [comment]
I still see this problem and I have:
GNU Emacs 27.0.91 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.30)
 of 2020-05-01

**Comment by zoechi** [comment]
@asifhg looks like Tramp can't handle the prompt it receives
Perhaps `(setq tramp-verbose 6)` provides more information?

**Comment by mvaled** [comment]
I'm seeing this problem, although it does happen when I run emacs with `emacs -q`.   Using `strace` I detect it enters a loop failing to read from fd:

```
recvmsg(5, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}], 3, 0) = 0 (Timeout)
rt_sigprocmask(SIG_BLOCK, [INT], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
pselect6(15, [5 6 7 14], NULL, NULL, {tv_sec=0, tv_nsec=31760988}, {NULL, 8}) = 0 (Timeout)
rt_sigprocmask(SIG_BLOCK, [INT], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
recvmsg(5, {msg_namelen=0}, 0)          = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=5, events=POLLIN}, {fd=6, events=POLLIN}, {fd=7, events=POLLIN}], 3, 0) = 0 (Timeout)
rt_sigprocmask(SIG_BLOCK, [INT], [], 8) = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
```

**Comment by mvaled** [comment]
My problem was that at this point is asking to save the password to `.authinfo`.  Once I have it in my `.authinfo.gpg` it works.

**Comment by rileyrg** [comment]
> My problem was that at this point Emacs is asking to save the password to `.authinfo` but the message is not actually shown. Once I have it in my `.authinfo.gpg` it works.

What exactly do you have in your authinfo please? (well, not the actually password, obviously ;)

**Comment by mvaled** [comment]
Now, just this:

```
machine pavla login root port sudo password ***put-your-password****
```

**Comment by rileyrg** [comment]
If you're on  tiled WM with a password entry configured as pop up gui you might not see it.
