### ISSUE TITLE
"Personal config" instructions are unclear

### ISSUE THREAD

**Issue by crucialfelix** [bbatsov/prelude#596]
Having just followed the install instructions, naturally I now need to set something in the oft mentioned "personal config"

https://github.com/bbatsov/prelude#personalizing

Here you start off by telling us to fork the repository. All I want to do is set a variable. I've just installed according to the instructions and there is no way I want to fork the repo.

We are then advised not to touch anything (!) outside of personal. But there is nothing in personal and we don't know what to put in there and how "the system" works.

After a while I finally figured out that I should create a file personal/config.el myself. This is what this "personal config" must be.

Is everything in personal/ loaded on startup ?  I'm just guessing, I have no idea what happens. I just did added something. I restarted. I still have no idea if my file ran or not.

Wait: "Prelude will automatically preload all Emacs Lisp files in your personal/preload directory."

So it didn't run. Now I'm totally confused.

Where is my personal config supposed to be ? What's it supposed to be called ?  Maybe you should just create a blank one on startup if it doesn't exist.

Maybe:

All *.el files personal/ are parsed when prelude starts up. Create a personal/config.el for your personal settings there and additional configuration.

In the prelude distribution the personal/ folder is always empty so you are free to customize there without fear of git merge conflicts when you update.

**Comment by oyvindln** [comment]
That part could be made clearer in the readme at least, the text only mentions that prelude-modules.el should be edited, but not where it should be put (or where it is).

**Comment by bingxiao** [comment]
learned how to proceed by this thread after installing prelude. Agree that the installation guide could be more adequate.
