### ISSUE TITLE
helm-find-files error in helm-everywhere

### ISSUE THREAD

**Issue by ghost** [bbatsov/prelude#662]
When I press `C-x C-f` I receive this error message
`helm-find-files-1: Invalid function: helm-build-sync-source`

```
Debugger entered--Lisp error: (invalid-function helm-build-sync-source)
  helm-build-sync-source("Find Files" :header-name #[257 "\211P\207" [helm-find-files-doc-header] .......................
file other window `C-c o'" . find-file-other-window) ("Switch to history `M-p'" . helm-find-files-switch-to-hist) ("Find file other frame `C-c C-o'" . find-file-other-frame) ("Print File `C-c p, C-u to refresh'" . helm-ff-print) ("Locate `C-x C-f, C-u to specify locate db'" . helm-ff-locate)) :before-init-hook helm-find-files-before-init-hook :after-init-hook helm-find-files-after-init-hook)
  helm-find-files-1("/usr/local/IBSng/" nil)
  helm-find-files(nil)
  ad-Orig-call-interactively(helm-find-files nil nil)
  call-interactively(helm-find-files nil nil)

```

Do you have same problem?

**Comment by kylev** [comment]
There may be a different reason, but this has re-emerged as a bug today. I updated prelude (then did a complete re-install) and am getting `Invalid function: helm-build-sync-source`.

**Comment by pajatopmr** [comment]
I am seeing the same issue.  No joy yet. :-(

**Comment by kylev** [comment]
@pajatopmr The 2016 new version of this similar bug is tracked as #964 and imenu-anywhere#26. It should be fixed if you update packages today.

**Comment by surya46584** [comment]
hi any updates on this issue please i am getting the same error 
No method definition: initialize-instance, "#<helm-source-ffiles Find Files>"
