### ISSUE TITLE
Switch to MELPA Stable

### ISSUE THREAD

**Issue by ToBeReplaced** [bbatsov/prelude#674]
Opening up for discussion.

Is there interest in prelude (or a version of prelude) moving to MELPA Stable?

What would it take to make prelude pull packages from MELPA Stable instead of MELPA? Are there any packages currently unsuitable for this change?

**Comment by joedevivo** [comment]
I've added somethings to my personal/preload that fixes this:

Put this around here: https://github.com/bbatsov/prelude/blob/master/core/prelude-packages.el#L38
```
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives
             '("melpa-stable" . "https://stable.melpa.org/packages/") t)
(setq package-archive-priorities
      '(("melpa-stable" .  10)
        ("melpa" . 9)
        ))
```

This will prefer `melpa-stable`, but pull from `melpa` when the package isn't available in `melpa-stable`

I'll open a PR if you like it
