### ISSUE TITLE
Add emmet-mode to prelude

### ISSUE THREAD

**Issue by k1-hedayati** [bbatsov/prelude#681]
[Emmet — the essential toolkit for web-developers](http://emmet.io/) is very useful for web development and editing HTML files. Just watch demo to see how awesome is that. There is an Emacs mode to that, please add it to prelude.
https://github.com/smihica/emmet-mode

**Comment by qinix** [comment]
+1

**Comment by helgeblod** [comment]
+1. This would be a great addition!

**Comment by bbatsov** [comment]
There hasn't been much activity on this ticket and I'm spread too thin on so many tasks, so I'll just close it for the sake of having a cleaner lists of tasks to focus on. 

To be perfectly clear - I think that's a good idea in general and I'll gladly review a PR, but it's unlikely that I'll tackle this myself in the foreseeable future. Hopefully my response is going to inspire someone else to work on this! 😉
