### ISSUE TITLE
Emacs freezes when opening larger python files

### ISSUE THREAD

**Issue by shofetim** [bbatsov/prelude#703]
When opening a (larger) python file in emacs, emacs will freeze for several seconds, to a minute, taking 100% CPU. It is barely noticeable on small files, but on something with more substance, like [this](https://github.com/aparo/pyes/blob/master/pyes/es.py) it will hang for 30 seconds or so.

It appears to be a recent problem, I hadn't updated to prelude master in a month or so, and it was working before the update.

**Comment by lackita** [comment]
For anybody that is still having issues that happens upon this thread, I realized the core of my problem was actually trying to edit over tramp.

**Comment by fleutot** [comment]
I had a similar issue (freeze at opening python file) in 26.1, until I disabled flyspell-prog-mode.
