### ISSUE TITLE
Emacs is too slow over sshfs

### ISSUE THREAD

**Issue by k1-hedayati** [bbatsov/prelude#716]
When I want to open a file over sshfs, Emacs becomes extremely slow because it tries to read whole bunch of other files (vc, projectile, company backends, etc). Can we have something like `find-file-basic` command which opens the file and disables every mode that wants to read files other than specified one?

**Comment by krux02** [comment]
It is not only slow opening files for me, it is also extremely slow in everything else. I am forced to not use emacs in my sshfs folder. Evem moving around in the opened file or writing text has a delay of several seconds. I have no idea what causes this problem, but it makes emacs unusable.

**Comment by krux02** [comment]
I have this problem too, but I am not using prelude. But emacs -q does not have the problem so I guess it is one of the plugins. Do you know which plugins cause the problems so I can disable them?

**Comment by arbox** [comment]
@krux02 could you please provide any details on this problem and how you tracked it down to Projectile.

**Comment by krux02** [comment]
@arbox At the moment I am not so 100% sure anymore, because I realized some inconsistency with performance that I can't explain, but deactivating projectile helped a lot.

**Comment by bbatsov** [comment]
The issues with Projectile are fixed in 1.1 (the current `master`), so I'll close this ticket.
