### ISSUE TITLE
helm-projectile-on implemented?

### ISSUE THREAD

**Issue by HParker** [bbatsov/prelude#717]
I am getting a warning when enabling `(require 'prelude-helm-everywhere)`

```
Warning (initialization): An error occurred while loading \`/Users/adam/.emacs.d/init.elc':

Symbol's function definition is void: helm-projectile-on

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the \`--debug-init' option to view a complete error backtrace.
```

I acked the directory for a definition of that function and didn't find one. is this an issue with projectile or prelude?

Thanks!

**Comment by cies** [comment]
I also run into this error. I think it could have been avoided by using `el-get`:

https://github.com/bbatsov/prelude/issues/784
