### ISSUE TITLE
Request: please make global key bindings optional

### ISSUE THREAD

**Issue by egarrulo** [bbatsov/prelude#738]
Hello,

thank you for writing this useful package.

Would you please consider making global key bindings optional (albeit enabled by default)?  Prelude has lots of useful functions, but I would prefer to bind them to keys of my own choice.  Other users could be in the same situation.

Thanks for your attention.

**Comment by disterics** [comment]
+1 To making key bindings optional. As non-beginner with my own set of key bindings that I have been using for years, I would prefer to keep those key bindings as opposed to learning new key bindings to accomplish the same thing now.
