### ISSUE TITLE
how can I only install packages from melpa-stable ?

### ISSUE THREAD

**Issue by bluealert** [bbatsov/prelude#743]
I use Prelude, and I put the below code in init.el

```
(require 'package)
(add-to-list 'package-archives
             '("melpa-stable" . "http://melpa-stable.milkbox.net/packages/"))
(package-initialize)

(add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)

(defvar my-packages '(color-theme-solarized
                      clojure-mode
                      cider))

(dolist (p my-packages)
  (unless (package-installed-p p)
    (package-install p)))
```

but can not work.

thank you very much! :)

**Comment by mlococo** [comment]
This is relevant again, as cider from melpa is currently in a state where it doesn't match the latest cidr-nrepl lein plugin available from maven. If there is an easy way to get cider pinned to stable, documenting it would probably help some folks.

This is similar https://github.com/bbatsov/prelude/issues/637

And a reminder of why prelude doesn't use melpa-stable by default: https://github.com/bbatsov/prelude/issues/674

**Comment by BrunoBonacci** [comment]
+1
