### ISSUE TITLE
editing cython files hangs emacs

### ISSUE THREAD

**Issue by fbkarsdorp** [bbatsov/prelude#747]
I'm not sure what's causing this problem, but using a fresh install of emacs, prelude and installation of cython-model through MELPA, causes emacs to hang and using 100% CPU each time I edit a cython file. Sometimes emacs hangs immediately after opening the file, sometimes it takes a little longer (max 5 minutes).

Any idea what might be the issue here?

**Comment by wbolster** [comment]
@fbkarsdorp i see a similar issue with cython (not using prelude though).  i see you recently closed this issue, did you find the source of the problem?

**Comment by fbkarsdorp** [comment]
I'm afraid not. I was just cleaning up my open issues, and since no answer was given in three years, I thought this could be closed. Happy to reopen.
