### ISSUE TITLE
python `blocking call to accept-process-output with quit inihinited`

### ISSUE THREAD

**Issue by jbernsie** [bbatsov/prelude#768]
only recently (without any changes to prelude configurations) when i go to type something into a python document emacs freezes and gives me this message,  `blocking call to accept-process-output with quit inihinited`

did some digging and saw it related back to anaconda mode so i tried to disable that but still nothing, im at a loss here guys

**Comment by danielwuz** [comment]
Have you seen discussion [here](https://github.com/proofit404/anaconda-mode/issues/54)

If you're using Mac, you may try uninstalling pip from homebrew and then install it again by `easy_install`

**Comment by proofit404** [comment]
Please try last `anaconda-mode`.

**Comment by oggers** [comment]
This solved the problem for me (Ubuntu 14.10):
```shell
# easy_install -U pip
```
Seems to be related with the pip version installed by default.
