### ISSUE TITLE
Enable Smartparens mode for markdown

### ISSUE THREAD

**Issue by k1-hedayati** [bbatsov/prelude#774]
Smartparens mode is useful for entering links and images and markdown documents and closing each pair by hand is pretty hassle

**Comment by bbatsov** [comment]
It used to be enabled, but unfortunately it's not playing well with triple backquotes...

**Comment by k1-hedayati** [comment]
There is a simple solution introduced in Fuco1/smartparens#371 to disable backquotes pairing
```(sp-local-pair 'gfm-mode "`" nil :actions '(:rem autoskip))```

**Comment by k1-hedayati** [comment]
btw I tested triple backquote in markdown mode with smartparens enabled without above fix I didn't notice any issues, each time I insert a backquote smartparens adds another backquote.
