### ISSUE TITLE
Remove grizzl from prelude

### ISSUE THREAD

**Issue by k1-hedayati** [bbatsov/prelude#780]
`grizzl` seems to be completely unmaintained, last commit is for Aug 10, 2013 and there is pull requests without response (d11wtq/grizzl#21), also it's not used in prelude actually and only projectile suggests using it despite that `ido-flx` and `helm` are better solutions. It might be better to remove it.

**Comment by bbatsov** [comment]
Fine by me. `grizzl` showed a lot of promise initially, but was abandoned quickly.
