### ISSUE TITLE
code folding in emacs

### ISSUE THREAD

**Issue by learner010** [bbatsov/prelude#786]
Before Emacs I used Vim. In my Vim configuration file I had following key maps for folding (taken from http://vim.spf13.com/).
The folding is based upon indent level.
<leader>f0 = fold to top level indent
<leader>f1 = fold to 1st level indent
<leader>f2 = fold to 2nd level indent
and so on.

Lets consider following code:

``` python
class AClass:
   def a_method(self):
      pass

  def b_method(self):
      pass

  def c_method(self):
     pass
```

would look like below at 2nd level fold.

``` python
class AClass:
   def a_method(self): ...
   def b_method(self): ...
   def c_method(self): ...
```

Is there anyway in emacs to achieve it? Thanx for any adivce in advanced.

**Comment by tuhdo** [comment]
You should have a look [hs-minor-mode](http://www.emacswiki.org/emacs/HideShow).

**Comment by learner010** [comment]
@tuhdo Following ur suggestion, I added following configuration to my personal config.el.

```
(defun hide-level-1 ()
  (interactive)
  (hs-hide-level 1))

(defun hide-level-2 ()
  (interactive)
  (hs-hide-level 2))

(defun hide-level-3 ()
  (interactive)
  (hs-hide-level 3))

(evil-leader/set-key "f1" 'hide-level-1)
(evil-leader/set-key "f2" 'hide-level-2)
(evil-leader/set-key "f3" 'hide-level-3)
```

The problem is, when I press `,f2` the python code folds in alternative manner. Something like below:
```
class AClass:
   def a_method(self): ...
   def b_method(self): 
       pass
   def c_method(self): ...
   def c_method(self): 
        pass
```

It works fine for lisp and javascript but in python.

**Comment by Avsecz** [comment]
I can also confirm this. A workaround was suggested here:

http://emacs.stackexchange.com/questions/18381/hideshow-with-python-hiding-only-one-part

which is unfortunately not using the hs-* functions to do folding.
