### ISSUE TITLE
evil-mode on all buffers/windows

### ISSUE THREAD

**Issue by jvillasante** [bbatsov/prelude#796]
How can I configure evil to be used on all buffers/windows. I mean, I would like to be able to use evil to navigate everything on emacs, and with evil-leader switch between windows and the like. Is that possible?

**Comment by roryk** [comment]
Hi Julio,

It is tough to do for all buffers because evil clashes with the default keybindings of some modes, so you will end up having to remap some keys in some modes no matter what. Is there a particular mode that's bothering you?
