### ISSUE TITLE
Accidental prelude-kill-other-buffers

### ISSUE THREAD

**Issue by holocronweaver** [bbatsov/prelude#798]
I often accidentally hit the key combo `C-c k`, killing scores of buffers and leaving my face flushed. I think `prelude-kill-other-buffers` is very useful, but it should be left as an interactive command with either no key binding or one that is very difficult to accidentally perform. Thoughts?

(Note that I have disabled the key binding in my config, but I thought I should report my frustration under the assumption that other users are experiencing the same paper cut and not reporting it because it is so easy to fix. Paper cuts add up!)

**Comment by swaroopch** [comment]
+1
