### ISSUE TITLE
Prelude has problems if used with melpa-stable

### ISSUE THREAD

**Issue by limist** [bbatsov/prelude#800]
Not sure if this is the Right Way in Prelude, but: if I want to use melpa-stable packages for more stability, after modifying `core/prelude-packages.el` to refer to it with,

``` elisp
(add-to-list 'package-archives
             '("melpa-stable" . "http://melpa-stable.milkbox.net/packages/") t)
```

...upon restarting Emacs, there are errors from two Prelude modules: `modules/prelude-latex.el` and 
`modules/prelude-python.el`.  Each requires packages not currently in melpa-stable: `company-auctex` and `company-anaconda` respectively.  Commenting out the `load` commands for those packages lets Prelude load and run normally.

**Comment by marknsikora** [comment]
Duplicate of #674
