### ISSUE TITLE
emacs auto-save files are put in both the temp directory and the current directory.

### ISSUE THREAD

**Issue by cowboyd** [bbatsov/prelude#806]
With a pristine install of prelude, If I make an edit to a project's Gemfile, but don't save changes (and `prelude-auto-save` set to `nil`). It creates an entry in the temp directory named:

```
#!home!cowboyd!projects!foo!Gemfile#
```

and in the current directory named:

```
.#Gemfile
```
My understanding is that it should go only go to the temp directory because of https://github.com/bbatsov/prelude/blob/master/core/prelude-editor.el#L57-L58

**Comment by cowboyd** [comment]
More information: 
* If I disable auto-save completely, I still see it in the current directory, but it does not appear in the tmp directory.
* The file in the current directory is a symbolic link:

```
lrwxr-xr-x   1 cowboyd  staff      21 Feb 11 14:20 .#Gemfile -> cowboyd@I.local.11079
```

I've never seen a symlink with this format. Not suprisingly,  `11079` is the emacs PID

The contents of the file are consistent with a normal emacs autosave file.

**Comment by aethanyc** [comment]
This article might help :-)
http://stackoverflow.com/questions/5738170/why-does-emacs-create-temporary-symbolic-links-for-modified-files

**Comment by cowboyd** [comment]
Thanks @aethanyc This was extremely helpful. It's exactly what I had been searching for, for several weeks before finally posting here.
