### ISSUE TITLE
ad-handle-definition: `untabify' got redefined

### ISSUE THREAD

**Issue by pronobis** [bbatsov/prelude#808]
The warning `ad-handle-definition:`untabify' got redefined` shows up annoyingly often occluding useful information in the minibuffer. It seems to be related to this line in prelude-editor.el:

```
(with-region-or-buffer untabify)
```

and the fact that `untabify` is defined already in Emacs in tabify.el. Renaming the Prelude untabify solves the issue. Could we have that fix permanently in Prelude?

**Comment by pronobis** [comment]
@bbatsov Do you have any comment? Should I send a pull request or st?

**Comment by bbatsov** [comment]
I'm not sure what's your intended fix. We advise a built-in command, which is something pretty standard.

**Comment by pronobis** [comment]
Indeed you do. I'm not sure why this warning appears then. Will do more testing.

**Comment by pronobis** [comment]
http://lists.gnu.org/archive/html/help-gnu-emacs/2012-01/msg00199.html explains well why this happens. Basically, adding `(require 'tabify)` to `prelude-core.el` solves the problem for me. There is an identical problem with `defadvice ido-find-file` and adding `(require 'ido)` before that solves the problem as well.

**Comment by pronobis** [comment]
PR: https://github.com/bbatsov/prelude/pull/825

**Comment by toctan** [comment]
https://github.com/bbatsov/prelude/issues/896#issuecomment-137329337

@bbatsov @pronobis Here's another one. Maybe we should solve the problem once and for all with:

```el
;; Annoying redefinition warning
(setq ad-redefinition-action 'accept)
```

Not sure if there is any side effects but it works and it had been in my personal configuration for years.
