### ISSUE TITLE
reverse: Symbol's function definition is void: s-split

### ISSUE THREAD

**Issue by goofansu** [bbatsov/prelude#812]
Prelude reports this error when use `C-c S` to open my shell init file.

**Comment by bbatsov** [comment]
I can't reproduce this.

**Comment by goofansu** [comment]
Reinstalled all packages and cannot reproduce.

**Comment by goofansu** [comment]
I met this error again.

FYI, `(getenv "SHELL") => /usr/local/bin/zsh`

**Comment by bsteuber** [comment]
Happens to me too with emacs 24.3.1. I fixed it here by adding 
`(require 's)`to the top of prelude-core.el

**Comment by goofansu** [comment]
@bsteuber It is strange that the `s` package was not installed. I install it and add `(require 's)` then it's ok.

**Comment by goofansu** [comment]
Close this issue as I wrote my own configs with `use-package`.
