### ISSUE TITLE
fresh install - missing symbol smartrep-define-key

### ISSUE THREAD

**Issue by sebwelkberg** [bbatsov/prelude#813]
A fresh install does not work at the moment. --debug-init shows the missing symbol smartrep-define-key is reference by core/prelude-editor.el. *require smartrep* is missing. The following patch fixes it.

```
diff --git a/core/prelude-editor.el b/core/prelude-editor.el
index e6442a8..32e49dc 100644
--- a/core/prelude-editor.el
+++ b/core/prelude-editor.el
@@ -392,6 +392,7 @@ indent yanked text (with prefix arg don't indent)."
 
 ;; operate-on-number
 (require 'operate-on-number)
+(require 'smartrep)
 (smartrep-define-key global-map "C-c ."
   '(("+" . apply-operation-to-number-at-point)
     ("-" . apply-operation-to-number-at-point)
```

**Comment by bbatsov** [comment]
It's supposed to be autoloaded (package.el generates the autoloads automatically, although sometimes this mysteriously fails).

**Comment by sebwelkberg** [comment]
I could reproduce it every time. I tried it 7 or 8 times.
Am 22.02.2015 15:16 schrieb "Bozhidar Batsov" <notifications@github.com>:

**Comment by bbatsov** [comment]
Hmm, I noticed the autoloads file was empty for me as well which is pretty strange. Anyways, I added the `require`.
