### ISSUE TITLE
make compile command more comfortable

### ISSUE THREAD

**Issue by toolslive** [bbatsov/prelude#815]
for any file, the compile command runs in the current directory. I believe most people have something that needs to be run from the root (or an unspecified parent) directory.
I used http://www.emacswiki.org/emacs/UsingMakefileFromParentDirectory
to hack up something, but it would be really nice to have it available in prelude.

**Comment by marknsikora** [comment]
Sounds more like a projectile issue than a prelude issue

**Comment by RadicalZephyr** [comment]
More specifically, [Projectile](https://github.com/bbatsov/projectile) *already* supports this with the command `projectile-compile-project`.  In prelude, that is bound to `C-c p c`.

**Comment by toolslive** [comment]
`C-c p c` opens a mini buffer `Compile command : make` (at least it does on my emacs)
But that's not what the above does. It finds the closest make file and starts from that directory.

**Comment by RadicalZephyr** [comment]
Okay, that's a fair point.  I would argue that the projectile command is the more useful of the two.  I've never had cause to need the behavior of running the nearest Makefile.

But regardless of the specific behavior, I don't think that this kind of functionality is really in scope for being included directly in prelude.

**Comment by toolslive** [comment]
well, if you have flat structured (toy) projects, or use something like recursive `make` then you don't need this. I already scratched my own itch, and merely suggested this might be useful for others as well. Feel free to do whatever you think is best.
