### ISSUE TITLE
meta shift down (org-table-insert-row) doesn't work in org mode because overridden in prelude-mode

### ISSUE THREAD

**Issue by swaroopch** [bbatsov/prelude#824]
From https://github.com/bbatsov/prelude/blob/b24bea01bf4e8a34307be9e5aaa119192ceb97be/core/prelude-mode.el#L50 :

     (define-key map [(meta shift up)] 'move-text-up)
     (define-key map [(meta shift down)] 'move-text-down)

This overrides `org-shiftmetadown` which calls ``org-table-insert-row'` ( http://orgmode.org/cgit.cgi/org-mode.git/tree/lisp/org.el?id=53c6f68896080c37bdb9276406e8a032b9a3049f#n20339 )

From http://orgmode.org/cgit.cgi/org-mode.git/tree/lisp/org.el?id=53c6f68896080c37bdb9276406e8a032b9a3049f#n19581 :

    (org-defkey org-mode-map [(meta shift down)]   'org-shiftmetadown)

For now, I've commented out those lines in my local copy of emacs prelude, but is there a better way to do this?

**Comment by jkamenik** [comment]
I am similar issue with other keybindings for org-mode.  What I do is run `prelude-mode -1` to turn off prelude while I am in org-mode.

You can put this somewhere in your config.

```lisp
(add-hook 'org-mode-hook
          (lambda ()
            (prelude-mode -1)))
```
