### ISSUE TITLE
Don't open read-only files as root if user owns the file

### ISSUE THREAD

**Issue by disterics** [bbatsov/prelude#839]
I work with perforce where files from the repository are by default not writable. 
The advice: `find-file-sudo` to `ido-find-file`  defined in [prelude-core.el](https://github.com/bbatsov/prelude/blob/master/core/prelude-core.el#L300) to reopen these files with sudo is not ideal in these situations.

An option to disable this would be nice but I just saw the [edit-files-as-root blog post](http://emacsredux.com/blog/2013/04/21/edit-files-as-root/) and I acknowledge that there are some good use cases for this. 

With that in mind, I propose that the code be changed so the call to `find-alternate-file` is only triggered if the file is not writeable and not owned by the current user. The thinking being that, if it is owned by the current user, they can chmod the file to make it writable if they wanted to. 

I am willing to submit the patch if the solution seems reasonable.

**Comment by RadicalZephyr** [comment]
Sounds super reasonable to me, but I can't accept your patch even if you write it ;)
