### ISSUE TITLE
What is the correct way to update the background colour in personal configuration?

### ISSUE THREAD

**Issue by mcraveiro** [bbatsov/prelude#855]
Hi,

I recently started using Prelude and I quite like it, thanks for all your work. I also like Zenburn but I need to change the background colour and font.

The problem I have is that the colour is reset back to gray during start-up.

My personal configuration (available [here](https://github.com/mcraveiro/prelude/blob/personal/personal/init-editor.el)):
```
(set-background-color "black")
(set-frame-font "Inconsolata Bold 16" nil t)


(add-to-list 'default-frame-alist
             '(background-color . "black")
             '(font .  "Inconsolata Bold 16"))
```

The configuration works fine for all frames created after start-up, just not for the original frame. I can also see the colour flashing from gray to black and then back to gray again.

I have read the following pages:

- Emacs Prelude: Background Color:http://stackoverflow.com/questions/20781746/emacs-prelude-background-color
- Emacs Wiki: http://emacswiki.org/emacs/SetFonts

Many thanks for your time.

**Comment by marknsikora** [comment]
Sounds like you need to move the GUI related parts into personal/preload/.

**Comment by mcraveiro** [comment]
Hi,

Somehow I missed this comment, apologies @marknsikora. I'm afraid adding these to personal/preload didn't make any difference. I have resigned myself to manually setting the colour to black for now, which is not a major problem since I don't restart emacs very often. Thanks for your help though.

Cheers

Marco

**Comment by mcraveiro** [comment]
I'll close the issue since it seems to only affect me - if anyone disagrees we can reopen.
