### ISSUE TITLE
Annoying and dangerous find-file-hook

### ISSUE THREAD

**Issue by Bklyn** [bbatsov/prelude#857]
The recent changes to try to open files as root is quite annoying and IMHO dangerous. I have root on my machine, but when visiting e.g. system header files while tracing compile errors, I do not want these files opened as root where I could accidentally make changes to them. I'm also getting prompted for the root password (I believe) when the semantic code does its syntax analysis in the background.

I've added:

```
(remove-hook 'find-file-hook 'prelude-reopen-as-root)
```

to my personal settings, but I think the default behavior should be changed.

**Comment by sunlin7** [comment]
I affect by this issue too. I didn't have the root privilege, and the "sudo:" tips again and again.
Please make this as an optional, or give user hints to change the default behavior.

**Comment by marknsikora** [comment]
This is causing me some pain working with the perforce VCS. By default it locks files by making them read only until they are opened for edit. 

My normal workflow is:
 * Open locked file
 * Use p4.el to open for edit
 * Make changes
 * Submit with p4.el

The current setup gives me an annoying prompt at step 1. 

Also this hook assumes the user has admin access, which in many corporate settings is not true.

**Comment by sunlin7** [comment]
@marknsikora 

I find the `prelude-reopen-as-root` already remove from prelude-core.el, that mean the issue already be fixed now.
