### ISSUE TITLE
Strange artifact with monokai theme

### ISSUE THREAD

**Issue by istinspring** [bbatsov/prelude#861]
It looks like:

![Image](http://i.imgur.com/im1HxC9.png)

**Comment by pigmej** [comment]
Isn't it column 80+ mark ?

Focus it and `M-x describe-face` what does it show ?

**Comment by bbatsov** [comment]
Yep, looks pretty normal to me. `whitespace-mode` is simply highlighting the part of the line which exceeds 80 characters.

**Comment by istinspring** [comment]
I tried to disable whitespace mode but nothing changed.

![Image](http://i.imgur.com/fVJKMzW.png)

**Comment by istinspring** [comment]
But yea for each line: "line too long (86 > 79 characters) [E501]"

**Comment by istinspring** [comment]
is it possible to disable FlyC from checking E501? or better to increase allowed line length to the 120 characters?
