### ISSUE TITLE
How to fix File error: http://melpa.org/packages/anaconda-mode-20150313.655.tar, Not found

### ISSUE THREAD

**Issue by hanks** [bbatsov/prelude#869]
Yesterday emacs was ok, but when I run it this morning, the error was happened.
```
File error: http://melpa.org/packages/anaconda-mode-20150313.655.tar, Not found
```  
Temp solution is to comment out prelude-python module. And how to update to the latest versions of modules or stop to auto upgrade.

**Comment by nylar** [comment]
```M-x package-refresh-contents RET``` usually works for me.

**Comment by hanks** [comment]
@nylar oh, cool, it works for me too. Thanks.

**Comment by chespinoza** [comment]
Worked for me too thanks.
