### ISSUE TITLE
fresh installation of prelude on 24.5 stuck on contacting host: melpa.org:80

### ISSUE THREAD

**Issue by mage666** [bbatsov/prelude#870]
Hi, i just did a fresh install of emacs 24.5 from homebrew and was trying to setup prelude.
on my first run it got past contacting elpa, but stayed stuck on contacting host: melpa.org:80

Waited for 10 minutes and nothing happened.
I'm able to ping the url through terminal so host is definitely reachable.
![screen shot 2015-07-05 at 9 51 53 pm](https://cloud.githubusercontent.com/assets/1426112/8512431/1b01a038-2360-11e5-8042-1db7d7085546.png)

**Comment by marknsikora** [comment]
Does this happen all the time? I get this issue occasionally when I'm on a flaky connection.

**Comment by bbatsov** [comment]
That's not a Prelude problem per se - most likely some issue with the connectivity to melpa.

**Comment by mage666** [comment]
Yes happening all the time, i tested it without prelude, the problem is still there. So not a problem with prelude. closing this issue
