### ISSUE TITLE
Change VC mode settings

### ISSUE THREAD

**Issue by gsingh93** [bbatsov/prelude#875]
I found out today the hard way that the default [vc](http://www.emacswiki.org/emacs/VersionControl) mode has some horrible defaults. By default, for all of the types of version control it handles, it doesn't make a backup for any of the files checked in to version control. I think it would be good for prelude to enable backups for these files by default.

I believe all that needs to be done here is to add this to the configuration:

```
(setq vc-make-backup-files t)
```

I'd be fine with disabling vc altogether. The person who helped me figure out this issue on IRC suggested this: https://paste.debian.net/281692/

**Comment by bbatsov** [comment]
And why's this so bad? I don't use `vc.el` much (I'm a `magit` user), but don't recall ever running issues with `vc.el`.

**Comment by gsingh93** [comment]
If you for some reason lose a file, you have to restore it using the last
commit. Everything up until then is lost because there's no backup.

**Comment by gsingh93** [comment]
@bbatsov Does that make sense?

**Comment by marknsikora** [comment]
I agree with @bbatsov on this. Most users don't use vc mode. I use exclusively either magit or p4.el at this point. Adding support for a feature that is used by a tiny minority of users doesn't seem worth the trouble.

**Comment by gsingh93** [comment]
I don't use vc mode. I didn't even know what it was until I was having
trouble and asked on IRC. This issue is regarding the fact that these
settings are enabled by default for everyone, regardless of whether you use
vc mode or not. Or am I mistaken about that?
