### ISSUE TITLE
How do set my personal setting for emacs?

### ISSUE THREAD

**Issue by zhexuany** [bbatsov/prelude#876]
I started use prelude yesterday. It is really good, but I do not know how to set my own personal setting. For example, I want to use company-mode when I open emacs, How do I download the package?
Should I do it in a regularly way? In addition, which file should I put the code to?

**Comment by sumitsahrawat** [comment]
Whatever is in the the `personal` directory becomes your personal config. For more, look [here](https://github.com/bbatsov/prelude#personalizing).

**Comment by zhexuany** [comment]
I knew that. I was confused how I download packages.  I tried install packages in a regular way and then all packages are put in a file named elpa. Should I move this file into personal? The thing is I tried to move it into personal but when I launch emacs, it return compile error.

**Comment by sumitsahrawat** [comment]
You can install packages normally. I personally like to create `.el` files in the personal directory, and have them use `prelude-require-package(s)` for the required packages.

Installing normally, using `package.el` is also fine, and shouldn't cause any trouble (Prelude also installs packages from elpa).

**Comment by zhexuany** [comment]
Yeah. I want to install packages in your way. Could you give me more details? i.e., how to create .el files to install packages? I am a new user for emacs.

**Comment by sumitsahrawat** [comment]
Sure, you can take a look through my config [here](https://github.com/sumitsahrawat/prelude/tree/personal/personal). The `fugue-` files are similar to prelude modules in spirit.

**Comment by zhexuany** [comment]
Thanks, I will take a look on your config.
