### ISSUE TITLE
How do I set my own prelude up?

### ISSUE THREAD

**Issue by zhexuany** [bbatsov/prelude#877]
I used wget for installing prelude. But, it does not work very well. 
I followed the step provided in readme.md as follows:
emacs --daemon
emacsclient -t
emacsclient -c

And I also added two aliases into my personal .zshrc file. I then typed "e" in my terminal, tried to use "M-x prelude-update", emacs returned "no match". There must be something wrong, but I do not know. 
Could someone tell me how to adjust prelude. 
Any partially will be fully appreciated.

**Comment by sumitsahrawat** [comment]
The aliases, etc. are not compulsory. I for instance, don't use them.

For starters, just use `emacs` to start emacs, or set an alias for emacs directly.

```shell
alias e=emacs
```

**Comment by sumitsahrawat** [comment]
If you're still adamant on using emacs as a daemon, take a look [here](http://www.emacswiki.org/emacs/EmacsAsDaemon).

**Comment by zhexuany** [comment]
I think my problem is not daemon mode. When I typed "emacs" in terminal, I do not know why emacs automatically load .emacs instead of prelude-modules.el.

**Comment by sumitsahrawat** [comment]
You have to remove all traces of any previous config. The `.emacs` file is not recommended anymore, it's been superseded by `.emacs.d/init.el`, so you should remove it.

**Comment by zhexuany** [comment]
I see.  I already use " rm -rf ~/.emacs " for deleting .emacs. Thank for your kindly reply.
