### ISSUE TITLE
Symbol's value as variable is void: ‘google-c-style  

### ISSUE THREAD

**Issue by zhexuany** [bbatsov/prelude#878]
The following is my code in yzx-google-c-style.el. And I put the file in personal. But, emacs return a warning info which is "Symbol's value as variable is void: ‘google-c-style". Anything is wrong?

```
;;;code
;;start flymake-google-cpplint-load
;;let's define a function for flymake initialization
(defun my:flymake-google-init ()
  (prelude-require-packages 'flymake-google-cpplint)
  (require ‘flymake-google-cpplint)
  (custom-set-variables
   '(flymake-google-cpplint-command "/usr/local/bin/cpplint"))
  (flymake-google-cpplint-load)
  )
(add-hook 'c-mode-hook 'my:flymake-google-init)
(add-hook 'c++-mode-hook 'my:flymake-google-init)
;;start google-c-style with emacs
(prelude-require-package 'google-c-style)
(require ‘google-c-style)
(add-hook 'c-mode-common-hook 'google-set-c-style)
(add-hook 'c-mode-common-hook 'google-make-newline-indent)
(provide ‘yzx-google-c-style)
;;; yzx-google-c-style.el ends here
```

**Comment by zhexuany** [comment]
Do not open .el file with textedit in Mac.

**Comment by sumitsahrawat** [comment]
+ It would be best if you didn't add `prelude-require-packages` to a hook. It would slow things down, and not do anything as the packages would be installed from a previous call.
+ Your usage of `prelude-require-packages` is wrong here, either use `prelude-require-package` (no `'s'`), or use it with a **list**, like `(prelude-require-package '(flymake-google-cpplint))`.

This might be the cause of #879
