### ISSUE TITLE
Global key map does not work

### ISSUE THREAD

**Issue by zhexuany** [bbatsov/prelude#879]
I do not know why, but all keybinding seem like not working at all.

**Comment by sumitsahrawat** [comment]
Google will get you a long way. Otherwise, can you describe your problem in
more detail?

**Comment by pigmej** [comment]
@zhexuany Probably something is broken in your config, try emacs --debug-init it will print you stacktrace on error.

**Comment by zhexuany** [comment]
(void-variable ‘flymake-cursor)                                                   
  (prelude-require-package ‘flymake-cursor)                                                                     
  eval-buffer(#<buffer  *load*-378484> nil "/Users/yzx/.emacs.d/personal/zhexuan-google-c-style.el" nil t)  ; R$
  load-with-code-conversion("/Users/yzx/.emacs.d/personal/zhexuan-google-c-style.el" "/Users/yzx/.emacs.d/perso$
  load("/Users/yzx/.emacs.d/personal/zhexuan-google-c-style.el")                                                
  mapc(load ("/Users/yzx/.emacs.d/personal/zhexuan-google-c-style.el" "/Users/yzx/.emacs.d/personal/zhexuan-ied$
  (progn (message "Loading personal configuration files in %s..." prelude-personal-dir) (mapc (quote load) (dir$
  (if (file-exists-p prelude-personal-dir) (progn (message "Loading personal configuration files in %s..." prel$
  eval-buffer(#<buffer  *load*> nil "/Users/yzx/.emacs.d/init.el" nil t)  ; Reading at buffer position 5105     
  load-with-code-conversion("/Users/yzx/.emacs.d/init.el" "/Users/yzx/.emacs.d/init.el" t t)    
load("/Users/yzx/.emacs.d/init" t t)                                                                          
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@$
  command-line()                                                                                                
  normal-top-level()

**Comment by zhexuany** [comment]
@sumitsahrawat 
the keybinding is just not working when I open it in terminal.

**Comment by sumitsahrawat** [comment]
@zhexuany I commented under #878, that might help.
