### ISSUE TITLE
load fail on emacs24.5.1

### ISSUE THREAD

**Issue by YuleiXiao** [bbatsov/prelude#882]
I execute "curl -L https://git.io/epre | sh" to install prelude. Adn first start emacs, but it report error. 

Debugger entered--Lisp error: (file-error "Cannot open load file" "没有那个文件或目录" "/home/bc/.emacs.d/elpa/flycheck-20150716.345/flycheck-autoloads")
  load("/home/bc/.emacs.d/elpa/flycheck-20150716.345/flycheck-autoloads" nil t)
  #[0 "\302\303\304\305\300\"\301\"\306\307#\207" [flycheck "/home/bc/.emacs.d/elpa/flycheck-20150716.345" load expand-file-name format "%s-autoloads" nil t] 5 "\n\n(fn)"]()
  funcall(#[0 "\302\303\304\305\300\"\301\"\306\307#\207" [flycheck "/home/bc/.emacs.d/elpa/flycheck-20150716.345" load expand-file-name format "%s-autoloads" nil t] 5 "\n\n(fn)"])
  package-activate-1([cl-struct-package-desc flycheck (20150716 345) "On-the-fly syntax checking" ((dash (2 4 0)) (pkg-info (0 4)) (let-alist (1 0 1)) (cl-lib (0 3)) (emacs (24 1))) nil nil "/home/bc/.emacs.d/elpa/flycheck-20150716.345" ((:keywords "convenience" "languages" "tools") (:url . "https://www.flycheck.org")) nil])
  package-activate(flycheck)
  package-initialize()
  byte-code("\302\303!\210\302\304!\210\305\306\307\310#\210\311\312\"\313 \207" [prelude-dir package-user-dir require cl package add-to-list package-archives ("melpa" . "http://melpa.org/packages/") t expand-file-name "elpa" package-initialize] 4)
  require(prelude-packages)
  eval-buffer(#<buffer  *load*> nil "/home/bc/.emacs.d/init.el" nil t)  ; Reading at buffer position 4156
  load-with-code-conversion("/home/bc/.emacs.d/init.el" "/home/bc/.emacs.d/init.el" t t)
  load("/home/bc/.emacs.d/init" t t)
  #[0 "\205\262

**Comment by zhexuany** [comment]
You can either try to reinstall flycheck again or create a .el file with "(prelude-require-package 'flycheck)"
and "(require 'flycheck)"

**Comment by bbatsov** [comment]
Indeed. Initial package installation is a bit flaky, but there's little we can do about it.
