### ISSUE TITLE
[Suggestion] Make use of smart-mode-line

### ISSUE THREAD

**Issue by sumitsahrawat** [bbatsov/prelude#884]
Prelude could make good use of it. I personally like the powerline theme because prelude enables a lot of minor modes, and this unclutters the mode-line.

Screenshots from my config:

+ Small window

![image](https://cloud.githubusercontent.com/assets/5645741/8781839/31c18c7c-2f2f-11e5-9485-59f7f71a7d32.png)

+ Large window

![image](https://cloud.githubusercontent.com/assets/5645741/8781869/5ea5971a-2f2f-11e5-8a66-86d3737f3d81.png)

**Comment by bbatsov** [comment]
I've been meaning to play with it for a while, but I never actually did this. As @Malabarba is involved I have no doubts that it's a great project.

**Comment by Malabarba** [comment]
Sml was my very first child, and it's still the one I like the most (don't tell the others).
I wouldn't recommend setting the powerline theme as default (it's a little finicky in some situations), but any of the other themes are perfectly good.

**Comment by Malabarba** [comment]
It also has builtin Projectile integration. :-)

**Comment by bbatsov** [comment]
Ah, a reference to my firstborn (technically zenburn-emacs, but themes don't count). What's this integration? Fancy project name display in sml, perhaps?

Would you recommend any default config changes?

**Comment by Malabarba** [comment]
>  What's this integration? Fancy project name display in sml, perhaps?

Yes. Sml displays file paths with some clever truncation and an abbreviations system, instead of buffer names. 
If you have Projectile installed, the project name is considered an abbreviation, and the path is displayed relative to the project root. 

> Would you recommend any default config changes?

Maybe, does prelude come with a default theme?

**Comment by bbatsov** [comment]
> Maybe, does prelude come with a default theme?

zenburn

**Comment by Malabarba** [comment]
Here's a simple config:


    (setq sml/no-confirm-load-theme t)
    (setq sml/theme 'respectful) ;; or 'dark
    (add-hook 'after-init-hook #'sml/setup)

The `respectful` theme will try to respect zenburn's color palette. I tested it here and I think it looks OK, but you should check out yourself.
You could also set the theme to `dark`, which is a set of colors I've “refined” over the years to put focus on the right parts of the mode-line. I usually recommend this one, but it might be too high-contrast for zenburn standards.

A third option, theme-wise, would be for zenburn to specify colors for the `sml/*` faces. Then you could just set `sml/theme` to `nil`.

**Comment by bbatsov** [comment]
I think someone submitted sml colours to zenburn I while back, but I'm not sure. Didn't you say that generally it's better to go with the powerline theme?

**Comment by Malabarba** [comment]
> I think someone submitted sml colours to zenburn I while back, but I'm not sure.

You mean this https://github.com/bbatsov/zenburn-emacs/pull/74 ? 
That's for sml-modeline, which is a different package. It's an unfortunate confusion. That package is older than smart-mode-line, but when I found out about it it was too late to change the name.

> Didn't you say that generally it's better to go with the powerline theme?

Quite the contrary. :) I said powerline theme would be a bad default because it's a little unstable (it is also a separate package).
The `dark`, `light`, and `respectful` themes are all good-old custom-themes, and are very well behaved.

**Comment by bbatsov** [comment]
Oh, seems I was mistaken on both fronts. It is what it is, I guess. Let's hope Prelude's users will enjoy `smart-mode-line`.

**Comment by marknsikora** [comment]
:+:

**Comment by sumitsahrawat** [comment]
Thanks @bbatsov, this is awesome. :+1:

**Comment by butala** [comment]
I am less than thrilled --- the colors (especially full on red X for a modified buffer) is distracting in zenburn. Setting sml/theme to "Don't use a theme" helps, but the bright red X remains.

Is there a way to have a more muted mode line as was the case before this change (I know, everyone is a critic)?

**Comment by bbatsov** [comment]
Yeah, I'm not fond of the colours myself. Ideally we'll just support for sml in zenburn. That's in my todo, but I'm super busy. It's not hard, so you can tackle if you'd like.

**Comment by Malabarba** [comment]
Indeed, the `sml/modified` face is one of the few that the `respectful` leaves with the default value (instead of inheriting). That's why it stands out. 
I should probably fix that.

**Comment by butala** [comment]
Restart my emacs to start fresh Monday morning and was pleased to find that the new mode line now looks great in zenburn.  A million kudos and thanks!

**Comment by bbatsov** [comment]
The colours are still a work in progress, but at least they're from zenburn. :-)
