### ISSUE TITLE
Required package `emacs-24.4' is unavailable

### ISSUE THREAD

**Issue by xuehao** [bbatsov/prelude#886]
My Ubuntu 14.04 cannot install 24.4. How to fix this problem?

**Comment by marknsikora** [comment]
14.04 is an old version. Either move off LTS, find a ppa, or build it yourself.

**Comment by zhexuany** [comment]
Can you give more details about the error?

**Comment by xuehao** [comment]
@marknsikora @zhexuany I find the reason. My emacs is 24.3. I delete the `magit` package, it's OK now. Maybe the `magit` package is relied on emacs 24.4

**Comment by bbatsov** [comment]
Might be accidental. At any rate - running 24.4 (24.5) is definitely a good idea.
