### ISSUE TITLE
projectile-global-mode causes failure when using TRAMP with /sudo::

### ISSUE THREAD

**Issue by 2mc** [bbatsov/prelude#887]
According to prelude-editor.el projectile-global-mode is on by default.
     (projectile-global-mode t)
 That's why I post the issue here and not straight at the projectile repo.

 Further conditions to reproduce: 
- enable projectile caching
   (setq projectile-enable-caching t)
- setup a auth-source file (even an empty one will do) e.g.:
   (setq auth-sources '((:source "~/authinfo.gpg")))

Description: 

 When typing:

```
 C-x C-f /sudo::
```

 gpg will start to ask for the passphrase of the above mentioned auth-source file.
 After entering the passphrase, we'll get the following approval in the _Messages_ buffer:

```
 Decrypting ... authinfo.gpg...done
```

 But then emacs starts to hang and you have to force to stop the issued find-files command by typing C-g.

 This failure will not happen, if projectile-global-mode is disabled or if projectile caching is disabled.
 However, if you have once disabled one of the above, proceeded with C-x C-f /sudo:: successfully and re-enable the before disabled again, then everything works as expected.

```
 So, in order to reproduce the issues, make sure to always restart emacs for testing.
```

 Further details of my setup: 
- GNU Emacs 24.5.1 (x86_64-apple-darwin14.1.0, NS apple-appkit-1344.72)
- possibly relevant prelude modules switched on: 
  - (require 'prelude-ido)
  - (require 'prelude-helm)
  - (require 'prelude-helm-everywhere) ;; sets itself above ido !
  - (require 'prelude-company)

**Comment by toctan** [comment]
@2mc What's your default shell? If it's zsh, have you tried this:
http://www.emacswiki.org/emacs/TrampMode#toc8

**Comment by 2mc** [comment]
Thank your for the pointer.

Yes, true, I am using zsh as my default shell.
But I am using it successfully and so  I am well aware of its possibly fancy prompts and that it can disturb a dumb TRAMP terminal.

Actually, my zsh setup works fine with TRAMP, not only for local connections via sudo but also for connections to remote hosts (running zsh or not) and even multi-hopping.

That's why I posted the issue here, since it's ONLY an enabled

    projectile-global-mode

that breaks it all!

However, I did follow all the 3 option and suggestions mentioned at the link-location you were pointed me at. After re-checking them all, I can only confirm that they do not help to solve the problem in any way. Hence, in my understanding at least, it remains to be a projectile issue.

**Comment by 2mc** [comment]
And another crosslink: https://github.com/bbatsov/projectile/issues/835
Hoping we can get ahead here soon.

**Comment by wiedzmin** [comment]
It seems setting epg-gpg-program to "gpg2" (instead of default "gpg") works around the issue in question. Now I can enable projectile-global-mode and have "/sudo::" machinery working at the same time, while also having ~/.authinfo.gpg in place.
