### ISSUE TITLE
You're not in a project error

### ISSUE THREAD

**Issue by jsandovalc** [bbatsov/prelude#889]
Hi everyone.
I just updated prelude and I got a problem with using projectile. When I try to use, for example, C-c p f, I get the message "You're not in a project". That is happening with all the projects I had.

Any clues with this problem?

**Comment by jsandovalc** [comment]
After some debugging  (and learning how to debug emacs lisp) I found out that the projectile-root-bottom-up function was not defined.

I deleted projectile from the elpa directory in my .emacs.d, and restarted emacs. It downloaded projectile and it worked perfectly fine.

**Comment by 121onto** [comment]
I am running into this problem as well.  Deleting the projectile directory didn't fix this for me.
