### ISSUE TITLE
Python: SyntaxError: 'return' outside function

### ISSUE THREAD

**Issue by jinyangustc** [bbatsov/prelude#892]
I'm using the default prelude python configuration and have a problem with 'Eval defun'. When I eval the def block (M-C-x), I got an error in the python shell:

```
SyntaxError: 'return' outside function
```

The test code are here:

``` python
def twoSum(nums, target):
    index = {}
    for i, val in enumerate(nums, 1):
        try:
            return index[target - val], i
        except:
            index[val] = i
```

I've also tried 'Eval region' and it works well.

Could you please help me with this problem?

**Comment by bbatsov** [comment]
That's likely a bug in `python-mode` or something.
