### ISSUE TITLE
How can I override the line column?

### ISSUE THREAD

**Issue by bluealert** [bbatsov/prelude#893]
https://github.com/bbatsov/prelude/blob/master/core/prelude-editor.el

how can I override the line column? I want to change it to 120 in my personal configuration file: `personal/preload/init.el`

```
;; whitespace-mode config
(require 'whitespace)
(setq whitespace-line-column 80) ;; limit line length
(setq whitespace-style '(face tabs empty trailing lines-tail))
```

**Comment by bbatsov** [comment]
```
(setq whitespace-line-column 120) ;; limit line length
```

Just add this to your personal config.

**Comment by bluealert** [comment]
I have tried this, but it does not work. I have tried this again after looking your answer.

so, I directly change 80 to 120 in `core/prelude-editor.el`. but I don't want to change source code for this little requirement.

**Comment by freizl** [comment]
@bluealert 
Those steps may be helpful and you shall be all set
1. `m-x customize-variable`
2. `whitespace-line-column`
3. At the customize page, change 80 to 120
4. **click** the `State` button and choose "Save for future sessions".

**Comment by bluealert** [comment]
@freizl @bbatsov  Thank you! :)
