### ISSUE TITLE
How to disable command echoing in  shell-mode?

### ISSUE THREAD

**Issue by lyqscmy** [bbatsov/prelude#895]
➜  ~  date
date
Tue Aug 18 00:44:24 PDT 2015
➜  ~  ls 
ls 
Desktop  Downloads  git 

I think it's my fault.But I can't figure out how to fix it.

And does who know how to make C-l behavior like terminal?'erase-buffer' can clean up output. But I want to keep history.

**Comment by toctan** [comment]
@lyqscmy I suppose you'er using zsh. Try this: http://unix.stackexchange.com/questions/89308/mysterious-repeating-of-entered-command-in-shell
