### ISSUE TITLE
Stuck at "Loading /home/xxx/.emacs.d/savefile/recentf...done "

### ISSUE THREAD

**Issue by gerroon** [bbatsov/prelude#896]
Hi

My emacs does not start at least stays there forever. I can run it with -q, obviously that works. Running -debug-init does not produce any error, it is just same sbeing stuck there forever, it seems like debug mode does not even start.

Loading /home/xxx/.emacs.d/savefile/recentf...done 

Sorry I cant provide any other details because I do not have any other way to it produce.

thanks

**Comment by netroby** [comment]
Same issue here.

**Comment by netroby** [comment]
Some error message:

```
Debugger entered--Lisp error: (void-variable require)                                                                                                                                                                                        
  eval-buffer(#<buffer  *load*-495341> nil "/home/huzhifeng/.emacs.d/prelude-modules.el" nil t)  ; Reading at buffer position 458                                                                                                            
  load-with-code-conversion("/home/huzhifeng/.emacs.d/prelude-modules.el" "/home/huzhifeng/.emacs.d/prelude-modules.el" nil nil)                                                                                                             
  load("/home/huzhifeng/.emacs.d/prelude-modules.el")                                                                                                                                                                                        
  (if (file-exists-p prelude-modules-file) (load prelude-modules-file) (message "Missing modules file %s" prelude-modules-file) (message "You can get started by copying the bundled example file"))                                         
  eval-buffer(#<buffer  *load*> nil "/home/huzhifeng/.emacs.d/init.el" nil t)  ; Reading at buffer position 4710                                                                                                                             
  load-with-code-conversion("/home/huzhifeng/.emacs.d/init.el" "/home/huzhifeng/.emacs.d/init.el" t t)                                                                                                                                       
  load("/home/huzhifeng/.emacs.d/init" t t)                                                                                                                                                                                                  
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\321\202;^@\316\322^S\323^A\322\211#\210^K\322=\203a^@\324\325\326\307^H\327Q!\"\$
  command-line()                                                                                                                                                                                                                             
  normal-top-level()   
```

**Comment by novakboskov** [comment]
Whether you use fresh prelude (starting it for the first time) or it previously worked?
If you starting it for the first time, whether you placed prelude-modules.el example?
From readme:
```
You'll need to adjust your prelude-modules.el file once the installation is done. 
If you are doing a manual install then you first need to copy the prelude-modules.el available in the
sample directory to the root of path/to/prelude/installation and then adjust that one.
```

**Comment by netroby** [comment]
I deleted the prelude-modules.el, it still stuck. very slow to start up emacs.

**Comment by gerroon** [comment]
This is what I have in my modules

;;; Uncomment the modules you'd like to use and restart Prelude afterwards                                                                                                   
                                                                                                                                                                             
;; Emacs IRC client                                                                                                                                                          
(require 'prelude-erc)                                                                                                                                                       
(require 'prelude-ido) ;; Super charges Emacs completion for C-x C-f and more                                                                                                
(require 'prelude-helm) ;; Interface for narrowing and search                                                                                                                
(require 'prelude-company)                                                                                                                                                   
;; (require 'prelude-key-chord) ;; Binds useful features to key combinations                                                                                                 
;; (require 'prelude-mediawiki)                                                                                                                                              
;; (require 'prelude-evil)                                                                                                                                                   
                                                                                                                                                                             
;;; Programming languages support                                                                                                                                            
(require 'prelude-c)                                                                                                                                                         
;; (require 'prelude-clojure)                                                                                                                                                
;; (require 'prelude-coffee)                                                                                                                                                 
;; (require 'prelude-common-lisp)                                                                                                                                            
;; (require 'prelude-css)                                                                                                                                                    
(require 'prelude-emacs-lisp)                                                                                                                                                
;; (require 'prelude-erlang)                                                                                                                                                 
;; (require 'prelude-go)                                                                                                                                                     
;; (require 'prelude-haskell)                                                                                                                                                
(require 'prelude-js)                                                                                                                                                        
;; (require 'prelude-latex)                                                                                                                                                  
(require 'prelude-lisp)                                                                                                                                                      
(require 'prelude-org) ;; Org-mode helps you keep TODO lists, notes and more                                                                                                 
(require 'prelude-perl)                                                                                                                                                      
(require 'prelude-python)                                                                                                                                                    
(require 'prelude-ruby)                                                                                                                                                      
;; (require 'prelude-scala)                                                                                                                                                  
(require 'prelude-scheme)                                                                                                                                                    
(require 'prelude-shell)                                                                                                                                                     
;; (require 'prelude-scss)                                                                                                                                                   
;; (require 'prelude-web) ;; Emacs mode for web templates                                                                                                                    
(require 'prelude-xml)

**Comment by toctan** [comment]
@gerron @netroby I believe it has nothing to do with `prelude-modules.el`, this is probably related to `recentf-mode`. Try to uncomment [this line](https://github.com/bbatsov/prelude/blob/master/core/prelude-editor.el#L145) in `prelude-editor.el`, if that works, post the content of `~/.emacs.d/savefile/recentf` here.

**Comment by netroby** [comment]
ad-handle-definition: `ido-completing-read' got redefined

**Comment by netroby** [comment]
```
;;; Automatically generated by `recentf' on Thu Sep  3 12:35:19 2015.

(setq recentf-list
      '(
        "/root/.emacs.d/core/prelude-editor.el"
        ))

(setq recentf-filter-changer-current 'nil)



;; Local Variables:
;; coding: utf-8-emacs
;; End:
```

**Comment by toctan** [comment]
@netroby Does it work to uncomment `recents-mode`?

**Comment by netroby** [comment]
Yes, if comment recentf-model , emacs will start quickly

**Comment by pigmej** [comment]
Same there for me, just updated prelude, and it hungs at recentf loading.

**Comment by hhnr** [comment]
Same issue. Reproducible with emacs 24.5, ubuntu 15.04, prelude installed by cloning the git repo.
emacs -nw takes around 18 seconds to launch emacs where as emacs -nw -q takes 0.0 seconds.

**Comment by hhnr** [comment]
With my print debugging skills i have managed to find the culprit, it was tramp. Try suggestions mentioned at http://www.emacswiki.org/emacs/TrampMode. Add   (eval-after-load 'tramp '(setenv "SHELL" "/bin/bash")) did the trick for me

**Comment by camechis** [comment]
Also having this issue.  It hangs there on the recentf.  If I comment it out it just hangs on the ad-handle-definition: `ido-completing-read' got redefined

**Comment by christoferjennings** [comment]
I have the same issue. 
I've tried commenting out recents-mode but it seems to just change the message to `ad-handle-definition: `ido-completing-read' got redefined`.
Also tried `(eval-after-load 'tramp '(setenv "SHELL" "/bin/bash"))` but no luck. Maybe I put it in the wrong place? I tried it in init.el

**Comment by camechis** [comment]
It's strange because this just started with me after months of use.

**Comment by gerroon** [comment]
I wish @bbatsov  replied to this bug.

**Comment by bbatsov** [comment]
He's pretty busy, but who knows, your wish might come true...

I don't recall us doing any related to `recentf` recently and I haven't experienced this issue myself. The only things Prelude changes are here https://github.com/bbatsov/prelude/blob/5b0c51d0edcaaf19b7bbf4335cab1a500c6cfa3f/core/prelude-editor.el#L127

**Comment by camechis** [comment]
I have it happening on two  Macbook pros.  I don't know if its related but I did not have the issue until upgrading to OS X El Capitan ( at least noticed it ).

**Comment by camechis** [comment]
I have a little bit of a break through.  If I turn off my wifi emacs starts up just fine.  It only hangs at this spot when my wifi is on.

**Comment by cute-jumper** [comment]
I'm not sure whether this is related to this problem...But did anyone in this issue try `(setq tramp-ssh-controlmaster-options)` before tramp is loaded?

**Comment by laohyx** [comment]
Same problem here, under OS X El Capitan, emacs 24.5.

I paste @cute-jumper 's code to preload directory and it is solved.

Thanks!

**Comment by camechis** [comment]
That appeared to do it for me as well

**Comment by gerroon** [comment]
"setq tramp-ssh-controlmaster-options" 

What is the functionality of this line?

**Comment by cute-jumper** [comment]
If you're interested, look at this thread: https://lists.gnu.org/archive/html/emacs-devel/2015-07/msg00251.html. Basically some ISPs map the domain name `host.does.not.exist` to an IP address and the tramp shipped with Emacs 24 does some computation in the `defcustom` of `tramp-ssh-controlmaster-options`(See the source code of `tramp.el`). `(setq tramp-ssh-controlmaster-options)` avoids the computation so we would not be blocked.

Note this issue has been fixed in Emacs 25 as mentioned in https://lists.gnu.org/archive/html/emacs-devel/2015-07/msg00251.html.

**Comment by christoferjennings** [comment]
@cute-jumper 's fix worked for me too. Thanks!

Here's more details of what I did in case it's helpful.

Added `(setq tramp-ssh-controlmaster-options)` before `(require 'tramp)` in `prelude-editor.el`...
```
(setq tramp-ssh-controlmaster-options)
(require 'tramp)
```

It fixed the startup time, but caused a compile warning (which I'm ignoring) ...
```
prelude-editor.el:206:7:Warning: assignment to free variable
    `tramp-ssh-controlmaster-options'
```

**Comment by gerroon** [comment]
How do I disable this tramp thing without editing the original files? I do not need to edit remote hosts
