### ISSUE TITLE
json-jsonlint warning messages

### ISSUE THREAD

**Issue by jbdatko** [bbatsov/prelude#904]
When opening a json file, I receive the following warning:

> Suspicious state from syntax checker json-jsonlint: Checker json-jsonlint returned non-zero exit code 1, but no errors from output: Error: option -c not recognized.  Use "jsonlint --help" for usage information.

My jsonlint version:
```
$ jsonlint --version
jsonlint (demjson) version 2.2.2 (2014-06-25)
```

The help does indeed not indicate a `-c` option.

This is emacs 24.4.1, on Ubuntu 15.04

Maybe it's a problem with `json-mode`?

**Comment by toctan** [comment]
The `json-jsonlint` checker in `flycheck-mode` requires the `jsonlint` executable from https://github.com/zaach/jsonlint instead of that provided by demjson.

**Comment by jbdatko** [comment]
Indeed it does. Thanks, works well now.
