### ISSUE TITLE
`C-a` no longer works in latest prelude

### ISSUE THREAD

**Issue by yatesco** [bbatsov/prelude#906]
`C-a` consistently jumps only to the beginning of the line, not the beginning of the text. `C-h k C-a` gives:

```
C-a runs the command beginning-of-visual-line, which is an interactive
compiled Lisp function in `simple.el'.

It is bound to C-a.

(beginning-of-visual-line &optional N)

Move point to beginning of current visual line.
With argument N not nil or 1, move forward N - 1 visual lines first.
If point reaches the beginning or end of buffer, it stops there.
To ignore intangibility, bind `inhibit-point-motion-hooks' to t.

[back]```

If I type `M-m` then it jumps to the beginning of the text.

I haven't changed the bindings myself.

**Comment by SiggyF** [comment]
Are you perhaps in [visual-line mode](https://www.gnu.org/software/emacs/manual/html_node/emacs/Visual-Line-Mode.html). Prelude [remaps](https://github.com/bbatsov/prelude/blob/master/core/prelude-core.el#L161) the `move-beginning-of-line` key (C-a in non visual-line mode). If you use visual line mode (possibly enabled by the Word Wrap menu option) the [prelude beginning of line](http://emacsredux.com/blog/2013/05/22/smarter-navigation-to-the-beginning-of-a-line/) is not active.

**Comment by yatesco** [comment]
Thanks SiggyF, I am indeed. Is there a work around? `M-m` still works so it isn't that dire...

**Comment by joonoro** [comment]
As a workaround you could add:

    (global-set-key (kbd "C-a") 'prelude-move-beginning-of-line)

to your personal config.
