### ISSUE TITLE
Selection and line highlight are nearly invisible in zenburn

### ISSUE THREAD

**Issue by yatesco** [bbatsov/prelude#907]
This might just be me and my old eyes, but I really struggle to distinguish the background of selected text and the line highlight in the default zenburn theme.

Attached is a screenshot - I have selected the symbol 'tasks?' and the single occurrence on the next line is highlighted but it is really hard to distinguish:

<img width="693" alt="screen shot 2015-09-20 at 11 06 15 am" src="https://cloud.githubusercontent.com/assets/181469/9980206/ab5b409a-5f87-11e5-9497-f0678ac3a07f.png">

This is on a 2014 macbook pro retina with brightness at about 70%. If I turn the brightness up to 100% then it is slightly easier to see but I am blinded by the screen!

**Comment by nanounanue** [comment]
I am facing the same problem Any ideas?

**Comment by yatesco** [comment]
You can change the styling of the selection (I apologise, I forget how) but more often than not I use a different theme like the `whiteboard` theme for example.
