### ISSUE TITLE
Strange bug with latest prelude.

### ISSUE THREAD

**Issue by istinspring** [bbatsov/prelude#909]
Hello, after i updated packages manually and got strange bug with python mode and anaconda. Reinstalling prelude didn't help.

```
Installing collected packages: jedi, six, service-factory, anaconda-mode
....
/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'anaconda_mode.py': [Errno 2] No such file or directory
```

**Comment by istinspring** [comment]
It's related to the anaconda mode

https://github.com/proofit404/anaconda-mode/issues/114

**Comment by istinspring** [comment]
To bypass it:

Find distutil.cfg in distutil package located in ```Frameworks/Python.framework/Versions/2.7/lib/python2.7``` (for OSX)

And comment the following line: ```prefix=/usr/local```
Run emacs again wait till it install anaconda-mode, after it revert your distutil.cfg back.

**Comment by joehakimrahme** [comment]
I confirm the workaround described above worked for me.

I'm on OS X, python installed with Homebrew.
