### ISSUE TITLE
Undo does not (redo) as expected

### ISSUE THREAD

**Issue by jramapuram** [bbatsov/prelude#910]
Not sure if this is a feature or not.

Usually if I use `C+/` it undoes something
If I say move the cursor (or basically any OP) and press `C+/` again I expect a redo as it pops the stack.

This does not happen with prelude installed.

**Comment by bkruczyk** [comment]
This is because prelude uses [undo-tree](http://www.emacswiki.org/emacs/UndoTree) mode which binds undo to <kbd>C-?</kbd> and <kbd>M-_</kbd>. 
You can turn it off to get default behaviour.

**Comment by jramapuram** [comment]
thanks @bkruczyk

**Comment by jramapuram** [comment]
@bkruczyk : I added `(undo-tree-mode 0)` to `~/.emacs.d/personal/base.el` however it looks like the prelude config always overwrites it. What would be a more apt location/override command?

**Comment by bkruczyk** [comment]
Try `(global-undo-tree-mode 0)`.

**Comment by jramapuram** [comment]
@bkruczyk : perfect! thanks a bunch
