### ISSUE TITLE
How to disable undotree?

### ISSUE THREAD

**Issue by tenpn** [bbatsov/prelude#918]
I find undotree conflicts with iedit: after I use iedit, emacs will error when I try to save. The callstack is in undo-tree-save-history-hook. 

I'm not particularly interested in fixing the conflict, as I haven't found myself using undotree much. How can I tell prelude to stop turning it on from my config.el? I can see the global-undo-tree-mode in prelude-editor.el but I don't want to hack the internals and make conflicts for myself on upgrading.

**Comment by tenpn** [comment]
...I tried `(undo-tree-mode -1)` in my config.el but that didn't seem to help. Maybe it's executed too early?

**Comment by bkruczyk** [comment]
Try putting `(global-undo-tree-mode 0)` in your `.emacs.d/personal/personal.el ` file.

**Comment by tenpn** [comment]
No luck with that or `(global-undo-tree-mode -1)`. Still get undo tree on tapping `uu`.

**Comment by bkruczyk** [comment]
Yup, because `uu` is bound to command `undo-tree-visualize`. You can unbind it or bind to `undo`:
`(key-chord-define-global "jj" 'undo)`

**Comment by tenpn** [comment]
Ah ha so undo-tree-visualize can run even if undo-tree is disabled! Thank you!
