### ISSUE TITLE
(Emacs novice) Anzu problem.

### ISSUE THREAD

**Issue by fithisux** [bbatsov/prelude#920]
System Windows 10 x64
emacs-24.5-bin-i686-mingw32.zip
set HOME=C:\langs\home

I git cloned the prelude repository and put all the contents to

%HOME%.emacs.d

When I start emacs it says that anzu- is missing.

I download the 0.59 version and put contents to 
C:\langs\home.emacs.d\elpa\anzu-0.59

I executed emacs from conemu (cmd) as

c:\winoss-x86\emacs\bin\runemacs.exe

and ...
Suddenly it worked. 
It also downloaded 

anzu-20151008.2237

What is going on?

Thank you.

**Comment by bbatsov** [comment]
Maybe some auto-loads haven't been generated properly or something. Usually deleting the problematic package and reinstalling it solves such issues.

**Comment by clifford** [comment]
I am experiencing the same issue as @fifthisux.
How, do I go about deleting the package? as emacs won't load because of the problem.

Thanks
Clifford

**Comment by r03** [comment]
I had the same problem. It seems that Emacs on Windows has problems with https. There is a note about this here: https://melpa.org/#/getting-started

I changed the url in this file: c:\Users\foo\AppData\Roaming\.emacs.d\core\ **prelude-packages.el**
https://melpa.org/packages/ -> http://melpa.org/packages

After restarting emacs the installation started just fine.

**Comment by javjar** [comment]
yup, s/https/http solved the issue.
