### ISSUE TITLE
multiple emacsclients zap zenburn theme

### ISSUE THREAD

**Issue by michaelkarlcoleman** [bbatsov/prelude#925]
I'm running emacs --daemon, and if I start a second emacsclient, it seems to zap the zenburn theme (colors change).  If I disconnect all clients and reconnect, it seems to be back.  Not sure.

**Comment by bbatsov** [comment]
That's quite odd. I can't imagine how the second client might be affecting the theme, as it should be loaded just once when the server boots.

**Comment by tutufan** [comment]
Ran it under 'script' just to verify there wasn't something wrong with my terminal, but the escape sequences being sent are indeed different.

Googling didn't produce much, but this post kind of hints at this situation being more complex than it looks: 
https://www.reddit.com/r/emacs/comments/3a5kim/emacsclient_does_not_respect_themefont_setting/
