### ISSUE TITLE
request for alternative to Super bindings

### ISSUE THREAD

**Issue by tutufan** [bbatsov/prelude#926]
It'd be nice not to require the Super modifier for standard bindings, as it's pretty frequently either unavailable or not really possible to pass through.  Am aware of the C-x @ s alternative, but this doesn't seem practical.

And really, if the arrow keys are considered to be gauche, Super is a real faux pas...  :-)

(Am quite enjoying prelude so far.  Cheers!)

**Comment by bbatsov** [comment]
You can simply remove those (or unset them) from the prelude-mode keymap (https://github.com/bbatsov/prelude/blob/master/core/prelude-mode.el).

As for an alternative prefix - it's easy to add some prefix, but as you noted, this would make the key combos a bit less comfortable.

**Comment by tutufan** [comment]
I guess what's really needed is an easy substitute for Super-.  Might just see if I can map <ESC> to be an alternate Super- instead of M-, since I don't really need it for the latter.
