### ISSUE TITLE
Symbol's function definition is void: set-fontset-font

### ISSUE THREAD

**Issue by yu-yuxuan** [bbatsov/prelude#933]
I use emacs -nw.  And my os system is Mac 10.10.  emacs version is 24.5
The phenomenon happens when I reinstall emacs by home brew. And then when I open it in the terminal. It shows this error.  I update all the thing: 2015-10-29

Debugger entered--Lisp error: (void-function set-fontset-font)
  (set-fontset-font t (quote unicode) "Apple Color Emoji" nil (quote prepend))
  eval-buffer(#<buffer  *load*-835748> nil "/Users/******/.emacs.d/core/prelude-osx.el" nil t)  ; Reading at buffer position 2375
  load-with-code-conversion("/Users/******/.emacs.d/core/prelude-osx.el" "/Users/******/.emacs.d/core/prelude-osx.el" nil t)
  require(prelude-osx)
  (progn (require (quote prelude-osx)))
  (if (eq system-type (quote darwin)) (progn (require (quote prelude-osx))))
  eval-buffer(#<buffer  *load*> nil "/Users/******/.emacs.d/init.el" nil t)  ; Reading at buffer position 4449
  load-with-code-conversion("/Users/******/.emacs.d/init.el" "/Users/******/.emacs.d/init.el" t t)
  load("/Users/******/.emacs.d/init" t t)
  #[0 "^H\205\262^@     \306=\203^Q^@\307^H\310Q\202;^@ \311=\204^^^@\307^H\312Q\202;^@\313\307\314\315#\203*^@\316\202;^@\313\307\314\317#\203:^@\320\nB^R\3$
  command-line()
  normal-top-level()

**Comment by yu-yuxuan** [comment]
use `brew install emacs --with-cocoa` instead of `brew install emacs`

**Comment by godylango** [comment]
#936 and #921 address this issue as well
