### ISSUE TITLE
Recursive load: "/usr/share/emacs/24.5

### ISSUE THREAD

**Issue by gerroon** [bbatsov/prelude#938]
I started getting this massively messed up error. I believe it has something to do with prelude because it goes away when I delete .emacs.d. I get this error even with a vanilla prelude.

Recursive load: "/usr/share/emacs/24.5/lisp/jka-compr.el.gz", "/usr/share/emacs/24.5/lisp/jka-compr.el.gz", "/usr/share/emacs/24.5/lisp/jka-compr.el.gz", "/usr/share/emacs/24.5/lisp/jka-com\
pr.el.gz", "/usr/share/emacs/24.5/lisp/jka-compr.el.gz", "/usr/share/emacs/24.5/lisp/emacs-lisp/warnings.el.gz"

I am on Debian Jessie x64

**Comment by raviksharma** [comment]
Any updates on this issue?

I am facing the same issue.

**Comment by mcraveiro** [comment]
Same here. Trying to debug it at the moment as I can't use emacs, but any help is appreciated. Cheers

**Comment by mcraveiro** [comment]
FWIW, I am on Debian Testing.

**Comment by mcraveiro** [comment]
Yes, my intuition was correct, this is actually most likely a debian bug, at least one version of which is being tracked under #803462:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=803462

From those comments it seems the bug will go away with a dist-upgrade soon. In the mean time, a work around is to comment this line in init.el:

;; Always load newest byte code
;; (setq load-prefer-newer t)

Use either another editor for this or start emacs with -Q. Then restart emacs.

**Comment by vasw** [comment]
Exactly the same issue I have on Debian testing,
thanks for the temporary fix !

**Comment by gerroon** [comment]
;; Always load newest byte code
;; (setq load-prefer-newer t)

This fix does not work for me.

**Comment by cpbotha** [comment]
I was experiencing this same error with the ubuntu-elisp emacs PPA on Ubuntu 16.04.

Following the advice in https://github.com/bbatsov/prelude/issues/1038#issuecomment-331087419 I simply removed the `emacs-el` package and then could start emacs up normally, without having to comment out my `load-prefer-newer` init.
