### ISSUE TITLE
which-function-mode hangs emacs in cython-mode

### ISSUE THREAD

**Issue by michaelkarlcoleman** [bbatsov/prelude#940]
(Mentioned this on a closed issue, but opening a new issue so it doesn't get lost.)

I just tracked a severe hang down to which-function-mode being enabled for a Cython file (cython-mode). Disabling it fixed things. The file is about 500 lines long. emacs 24-4. Suggest disabling this completely until it's seriously reworked.

Detail: This is particularly nasty if you're running in emacs --daemon mode, as you don't get standard C-g (quit) behavior. The emacs process just keeps buzzing and using up memory.

**Comment by 121onto** [comment]
bump.

**Comment by 121onto** [comment]
+1

**Comment by butala** [comment]
Adding `(add-hook 'cython-mode-hook (lambda () (which-func-mode -1)))` fixed this problem for me.

**Comment by owlas** [comment]
Thanks @butala - I'm also using this for now but doesn't resolve the problem. Has there been any progress on this?

**Comment by Yevgnen** [comment]
Any news ?

**Comment by rciorba** [comment]
Seems to work well if you use https://melpa.org/#/python-mode instead of the default python.el
