### ISSUE TITLE
rainbow-mode.el file is empty after a fresh installation of prelude

### ISSUE THREAD

**Issue by zzhjerry** [bbatsov/prelude#942]
First I need to say this is an excellent project. 

I just installed it and everything looks great except I was constantly getting errors saying `rainbow-mode` function is void during emacs start up. 

After some investigations, I found the file `rainbow-mode.el` file in `~/.emacs.d/elpa/rainbow-mode-0.12/` directory is empty. So I manually copied codes from [here](http://git.savannah.gnu.org/cgit/emacs/elpa.git/tree/packages/rainbow-mode/rainbow-mode.el) into that file and solved the problem. But this could still remain a problem for new installation for other users. 

So it would be great to work this out in the future.

I'm using Mac OS by the way.

**Comment by bbatsov** [comment]
You likely hit some package.el bug. Reinstalling packages usually fixes problems like these.
