### ISSUE TITLE
Prelude-update fails with smartparens not found

### ISSUE THREAD

**Issue by MatthewRock** [bbatsov/prelude#943]
When I run prelude-update, I get following error:

```
http://melpa.org/packages/smartparens-20151010.402.tar: Not found
```

What could be causing this problem?

**Comment by zheng27** [comment]
Try refreshing the list of packages with `M-x epl-refresh` before running `prelude-update`.

**Comment by MatthewRock** [comment]
I get stuck on `Contacting host: melpa.org:80`
