### ISSUE TITLE
can't discard file in magit mode when evil mode is turned on.

### ISSUE THREAD

**Issue by tmccombs** [bbatsov/prelude#944]
When evil mode is turned on, the K hotkey doesn't work for discarding changes to a file in magit (although it does work for chunks). This is because K is used by magit to untrack files, whereas k is used for discard, but since k is used for navigation in evil mode there isn't a hotkey to discard changes to a file.  

I'm not sure what the best solution is, but it is very annoying, for now I have been either discarding individual chunks or using `M-x magit-discard` on the file.

For me, discarding file changes is an important part of my workflow, I will often add debug statements or other changes to help with debugging on a branch, and then when I am done with them want to quickly revert said changes. For me at least I discard changes to files much more frequently than I untrack files, and would be fine with not having a hotkey for untracking, or having it moved to something else. I would also be okay with having a different hotkey for discarding files.

**Comment by t-p** [comment]
Hi, there was a discussion in the magit project about evil keybindings. I ended up using [this config](https://github.com/magit/magit/issues/1968#issuecomment-122468447)
