### ISSUE TITLE
anaconda-mode issues

### ISSUE THREAD

**Issue by licorna** [bbatsov/prelude#948]
Anaconda-mode displaying messages like - while on a Python buffer.

```
error in process filter: apply: Wrong type argument: stringp, ((code . -32700) (message . "Parse error"))
error in process filter: Wrong type argument: stringp, ((code . -32700) (message . "Parse error"))
Mark set
error in process sentinel: json-read: End of file while parsing JSON
error in process sentinel: End of file while parsing JSON
error in process filter: apply: Wrong type argument: stringp, ((code . -32700) (message . "Parse error"))
error in process filter: Wrong type argument: stringp, ((code . -32700) (message . "Parse error"))
```

It will not allow me to do any work as Emacs becomes unresponsive. I had to disable it completely with `anaconda-mode`.

Emacs version (download from emacsforosx.com): `GNU Emacs 25.0.50.1 (x86_64-apple-darwin13.4.0, NS appkit-1265.21 Version 10.9.5 (Build 13F1112))
 of 2015-09-27`

**Comment by joonro** [comment]
I get this as well - GNU Emacs `25.0.50.1 (x86_64-w64-mingw32)`, anaconda-mode `20150922.537`.

**Comment by nanounanue** [comment]
Any solutions?

**Comment by licorna** [comment]
I've updated (and also downgraded) a few things and I'm not seeing this problem anymore. Anaconda-mode is working as expected. I assume it was happening because I was using a nightly build of Emacs 25.

Current Setup Working Correctly
*Emacs*
From: http://emacsformacosx.com/
about-emacs: GNU Emacs 24.5.1 (x86_64-apple-darwin13.4.0, NS apple-appkit-1265.21)
 of 2015-04-10 on builder10-9.porkrind.org

*Anaconda-Mode*
Installed from: MELPA
Version: 20150922.537

*Prelude*
Version: Just updated with prelude-update (don't know how to check version)
