### ISSUE TITLE
Error while checking syntax automatically: (void-function seq-find)

### ISSUE THREAD

**Issue by webframp** [bbatsov/prelude#949]
Filing as an issue in case anyone else searches for the same problem. 

It seems like one of the included modules for prelude may depend on https://github.com/NicolasPetton/seq.el and is missing the dependency declaration, perhaps it's flycheck since flycheck appeared to be giving me this error.

simply adding 
```scheme
(prelude-require-package 'seq)
```
to one of my personal modules was enough to get working without error again.

**Comment by webframp** [comment]
actually fixed

**Comment by yangsheng6810** [comment]
I ran into the same problem, and the fix above does not work. Here is a link to the solution that work for me (in case anyone arrive here): [https://github.com/Malabarba/beacon/issues/13](https://github.com/Malabarba/beacon/issues/13) . In short, delete your `seq` package from Melpa, and install it from gnu
