### ISSUE TITLE
RefTeX not working

### ISSUE THREAD

**Issue by nanounanue** [bbatsov/prelude#951]
In my personal `init.el` (placed in `personal`) I got the following lines:

```
(add-hook 'latex-mode-hook 'turn-on-reftex)
(add-hook 'Latex-mode-hook 'turn-on-reftex)
(setq reftex-plug-into-AUCTeX t)

```

(as suggested in the page of AUCTeX)

But when I open a TeX buffer it doesn't activate automatically. What am I doing wrong?

**Comment by arbox** [comment]
I don't know if this is related to your question, but I had to put the path to my bibliography file to use RefTeX. I set this locally in my file.

`% reftex-default-bibliography: ("bib/bibliography.bib")`
