### ISSUE TITLE
package 'gist' fails to install for Emacs < 24.4

### ISSUE THREAD

**Issue by alexhutcheson** [bbatsov/prelude#952]
It fails with message:

    error: Package `emacs-24.4' is unavailable

To maintain compatibility with prior versions of emacs, the package should be fixed, or gist should be conditionally installed.

**Comment by alexhutcheson** [comment]
This also applies to magit

**Comment by bbatsov** [comment]
More and more packages are going drop support for Emacs 24.3 and older, so I'm not sure if this is worth it.

**Comment by alexhutcheson** [comment]
That's fair - it's your call whether this is worth the additional complexity.

That being said - Emacs 24.3 is the most recent version available in the [Ubuntu 14.04 (trusty) packages](http://packages.ubuntu.com/trusty/emacs24). trusty is the most recent LTS release, so 24.3 is the latest Emacs available in a lot of corporate and university settings. 

If you decide not to fix this, maybe it would make sense to update the README to reflect that 24.4 is a hard requirement.

**Comment by bbatsov** [comment]
I've opted to make 24.4 the required version now that there's a new Ubuntu LTS. More and more packages are starting to depend on 24.4 and this makes alternative solutions hard.
