### ISSUE TITLE
Can not install web-mode

### ISSUE THREAD

**Issue by stream1984** [bbatsov/prelude#954]
Hi 
I try to uncomment `(require 'prelude-web) ;; Emacs mode for web templates`
but get error message below, someone can help ?

Opening TLS connection to `melpa.org'...
Opening TLS connection with `gnutls-cli --insecure -p 443 melpa.org'...done
Opening TLS connection to `melpa.org'...done
url-insert-file-contents: https://melpa.org/packages/web-mode-20151031.59.el: Not found

**Comment by zheng27** [comment]
Try `M-x package-refresh-contents`

**Comment by stream1984** [comment]
That working, thanks :D
