### ISSUE TITLE
Debugger entered--Lisp error: (error "Package `emacs-24.4' is unavailable")

### ISSUE THREAD

**Issue by insflow** [bbatsov/prelude#956]
I use emacs 24.3
Debugger entered--Lisp error: (error "Package `emacs-24.4' is unavailable")
  signal(error ("Package `emacs-24.4' is unavailable"))
  error("Package `%s-%s' is unavailable" "emacs" "24.4")
  package-compute-transaction((gh gist) ((emacs (24 4)) (pcache (0 3 1)) (logito (0 1))))
  package-compute-transaction((gist) ((emacs (24 1)) (gh (0 9 2))))
  package-install(gist)
  prelude-require-package(gist)
  mapc(prelude-require-package (ace-window avy anzu beacon browse-kill-ring dash discover-my-major diff-hl diminish easy-kill epl expand-region flych$
  prelude-require-packages((ace-window avy anzu beacon browse-kill-ring dash discover-my-major diff-hl diminish easy-kill epl expand-region flycheck $
  prelude-install-packages()

**Comment by syohex** [comment]
This is similar to #886.

This error is raised at installing gist package. [gh.el](https://github.com/sigma/gh.el) which is used by [gist](https://github.com/defunkt/gist.el) package requires Emacs 24.4 or higher version now. Other packages such as magit also require Emacs 24.4 or higher. So I suppose that you should use Emacs 24.4 or higher if you use any package of prelude.

**Comment by dlineberger** [comment]
If that's the case, then prelude itself should say it's only compatible with emacs 24.4 and later, not 24.1 and later like it does now.

**Comment by bbatsov** [comment]
Yeah, guess I should update the docs. Some things are simply out of my control.
