### ISSUE TITLE
defadvice "set-major-mode" breaks forms-mode

### ISSUE THREAD

**Issue by cacology** [bbatsov/prelude#960]
Lines 182-6 of prelude-editor.el include a defadvice for the C function "set-buffer-major-mode" called "set-major-mode" which breaks the builtin forms-mode in Emacs by changing the mode at an inopportune time. Steps to reproduce:

1.) Create any form.el file; a fine example is here: https://www.gnu.org/software/emacs/manual/html_mono/forms.html#Format-Description 

2.) Open the form.el file, M-x forms-mode, answer 'y', and the crash happens. It's not covered by forms-mode's normal error detecting bits since it's a mode change that isn't expected.

In my local copy, I've commented out this entire defadvice, since it doesn't seem to make anything work better for me and I suspect it's changing modes at a time that Emacs doesn't expect it to (which might cause problems elsewhere?), but I hesitate to give it as a pull since I don't actually understand what "set-major-mode" is supposed to accomplish beyond what "set-buffer-major-mode" already does.

I'm happy to do more work to fix this, but I don't think I know enough about when Emacs expects modes to change. Guidance would be welcome if you want me to try to put a patch together.

Respectfully submitted,
-James

PS If "set-major-mode" is left intact, you can also avoid the problem by naming your form.el file something else, like "form.txt", but this seems at odds with the intent of forms-mode in the Emacs manual.

**Comment by toctan** [comment]
@cacology See #592. Sorry, I didn't take this kind of use case into account when I implemented this advice. Going to try to fix it today :)

**Comment by toctan** [comment]
@cacology I'm sorry to tell you that I haven't found a solution yet. During the setup process of forms mode,  the current filename was set to nil, which is not very regular I believe, via:

	(set-visited-file-name nil)

This will call `set-buffer-major-mode` and the advice would be applied to change the major mode according to file extension. We do not have much to do inside this advice cause we do not whether the advised function is called by forms mode or not.

**Comment by toctan** [comment]
@cacology A quick fix would be to advise the `forms-mode` to prohibit the major mode change:

```el
(defadvice forms-mode (around prohibit-major-mode-change activate compile)
  (let ((change-major-mode-with-file-name nil)) ad-do-it))
```

**Comment by cacology** [comment]
@toctan thanks for looking at it. I poked around a bit more in emacs lisp and a quick grep gives
    set-visited-file-name nil
In filesets.el, forms.el (our current culprit), gnus/plstore.el, mail/sendmail.el, and vc/ediff-patch.el. I don't use those bits of Emacs, but I think you're right that they're less commonly used pieces. As I understand the backtrace, the problem we have with forms.el is that smart-mode-line retains the original file name as the buffer name and then set-major-mode uses that to change the mode. It seems to be the interaction of the two causing the problem.

From what I gather in #592 , it seems like the goal is to set the major-mode on the creation of a new special buffer. What if this advice was on "generate-new-buffer"? That way, it leaves buffers that already have a mode alone, but uses the buffer's name to set an initial mode for a new buffer. Thoughts?

**Comment by toctan** [comment]
@cacology I do not think advising `generate-new-buffer` would be a good idea cause it's used quite widely and there is a good chance something will get broken. We only want to set the major mode automatically when we intentionally create a new special buffer.

**Comment by cacology** [comment]
@toctan Hm. I see. It seems that this works differently in Emacs 25 as well. I've left this disabled for my personal setup, as I don't really use special buffers like this expects. *However*, it seems that Emacs 25 does what you want without the advice. That is, C-x b "test.rb" sets-up a Ruby mode, even without this bit of code.

Maybe it's worth making this bit `(when (version< "25" emacs-version) ...)` would solve the problem for future users of forms-mode and emacs 25?

**Comment by toctan** [comment]
@cacology I've downloaded a nightly build Emacs 25.1 from http://emacsformacosx.com, without this advice, it would still be in fundamental mode in my case. I would try to fix this and keep you updated if I made any progress :)

**Comment by cacology** [comment]
Thanks @toctan . For now, I've disabled the feature in my .emacs.d/personal configuration file, which I post here in case anyone else runs across the same problem:
`(ad-remove-advice 'set-buffer-major-mode 'after 'set-major-mode)`

Meanwhile, I attach my features below in the off chance it might be some help:
`(helm-command rainbow-mode color rainbow-delimiters elisp-slime-nav jpsa-config org-mu4e mu4e mu4e-speedbar speedbar sb-image ezimage dframe mu4e-main mu4e-context mu4e-view epa mu4e-headers mu4e-compose mu4e-draft mu4e-actions rfc2368 smtpmail sendmail mu4e-mark mu4e-message html2text mu4e-proc mu4e-utils doc-view jka-compr image-mode mu4e-lists mu4e-vars mu4e-meta darkroom org-ref org-ref-glossary reftex-cite reftex reftex-loaddefs reftex-vars ox-latex ox-icalendar ox-html ox-ascii ox-publish ox org-ref-bibtex message rfc822 mml mml-sec epg mm-decode mm-bodies mm-encode mail-parse rfc2231 rfc2047 rfc2045 ietf-drums mailabbrev gmm-utils mailheader key-chord helm-bibtex f s parsebib doi-utils org-bibtex bibtex paradox paradox-menu paradox-commit-list hydra lv paradox-execute paradox-github paradox-core spinner server wc-mode twittering-mode org-mac-link org-element avl-tree org-mobile org-agenda the-org-mode-expansions org org-macro org-footnote org-pcomplete org-list org-faces org-entities noutline outline org-version ob-emacs-lisp ob ob-tangle ob-ref ob-lob ob-table ob-exp org-src ob-keys ob-comint ob-core ob-eval org-compat org-macs org-loaddefs cal-menu calendar cal-loaddefs rnc-mode flymake typo on-screen hexrgb gnus gnus-ems nnheader mail-utils cus-start cus-load prelude-yaml prelude-xml nxml-mode-expansions rng-nxml rng-valid rng-loc rng-uri rng-parse nxml-parse rng-match rng-dt rng-util rng-pttrn nxml-ns nxml-mode nxml-outln nxml-rap nxml-util nxml-enc xmltok prelude-web web-mode-expansions web-mode prelude-shell sh-script smie executable prelude-scheme geiser prelude-perl prelude-latex company-auctex yasnippet latex-mode-expansions latex tex-style tex crm smartparens-latex prelude-js js2-mode-expansions js2-mode js-mode-expansions js html-mode-expansions smartparens-html sgml-mode json map cc-mode-expansions cc-mode cc-fonts cc-guess cc-menus cc-cmds cc-styles cc-align cc-engine cc-vars cc-defs prelude-emacs-lisp prelude-lisp prelude-css prelude-c prelude-programming flycheck find-func subr-x which-func prelude-company company-files company-oddmuse company-keywords company-etags company-gtags company-dabbrev-code company-dabbrev company-capf company-cmake company-xcode company-clang company-semantic company-eclim company-template company-css company-nxml company-bbdb company prelude-helm-everywhere helm-mode helm-descbinds helm-eshell helm-elisp helm-eval edebug prelude-helm helm-projectile helm-files rx image-dired dired-aux ffap helm-tags helm-bookmark helm-adaptive helm-info helm-external helm-net browse-url xml url url-proxy url-privacy url-expand url-methods url-history url-cookie url-domsuf url-util mailcap helm-buffers helm-grep helm-regexp helm-plugin helm-elscreen helm-utils helm-locate helm-help helm-types helm helm-source eieio-compat helm-multi-match helm-lib helm-config helm-easymenu async-bytecomp async prelude-erc erc-truncate erc-autoaway erc-spelling erc-notify erc-log erc-list erc-menu erc-join erc-ring erc-networks erc-pcomplete erc-track erc-match erc-button erc-fill erc-stamp erc-netsplit erc-goodies erc erc-backend erc-compat prelude-osx exec-path-from-shell prelude-global-keybindings prelude-editor operate-on-number calc-bin calc-ext calc calc-loaddefs calc-macs diff-hl smartrep vc-dir ewoc vc vc-dispatcher diff-mode easy-mmode winner undo-tree diff esh-var esh-io esh-cmd esh-opt esh-ext esh-proc esh-arg esh-groups eshell esh-module esh-mode esh-util re-builder whitespace tabify browse-kill-ring derived midnight ediff-merg ediff-wind ediff-diff ediff-mult ediff-help ediff-init ediff-util ediff dired-x dired dired-loaddefs anzu avy projectile grep compile ibuf-ext ibuffer ibuffer-loaddefs bookmark pp expand-region text-mode-expansions er-basic-expansions expand-region-core expand-region-custom flyspell ispell tramp tramp-compat tramp-loaddefs trampver shell pcomplete comint ansi-color format-spec rect etags xref project ring volatile-highlights hl-line windmove recentf tree-widget wid-edit savehist saveplace diminish edmacro kmacro smartparens-config smartparens autorevert filenotify delsel prelude-mode prelude-core imenu epl ido ov dash thingatpt prelude-ui beacon seq smart-mode-line advice rich-minority zenburn-theme prelude-custom prelude-packages cl finder-inf tex-site info package epg-config url-handlers url-parse auth-source cl-seq eieio byte-opt bytecomp byte-compile cl-extra cconv eieio-core cl-macs gv eieio-loaddefs gnus-util time-date mm-util help-fns help-mode easymenu cl-loaddefs pcase cl-lib mail-prsvr password-cache url-vars disp-table mule-util tooltip eldoc electric uniquify ediff-hook vc-hooks lisp-float-type mwheel ns-win ucs-normalize term/common-win tool-bar dnd fontset image regexp-opt fringe tabulated-list newcomment elisp-mode lisp-mode prog-mode register page menu-bar rfn-eshadow timer select scroll-bar mouse jit-lock font-lock syntax facemenu font-core frame cl-generic cham georgian utf-8-lang misc-lang vietnamese tibetan thai tai-viet lao korean japanese eucjp-ms cp51932 hebrew greek romanian slovak czech european ethiopic indian cyrillic chinese charscript case-table epa-hook jka-cmpr-hook help simple abbrev obarray minibuffer cl-preloaded nadvice loaddefs button faces cus-face macroexp files text-properties overlay sha1 md5 base64 format env code-pages mule custom widget hashtable-print-readable backquote kqueue cocoa ns multi-tty make-network-process emacs)`
