### ISSUE TITLE
Error when opening certain filetypes

### ISSUE THREAD

**Issue by joonoro** [bbatsov/prelude#968]
When opening certain filetypes (e.g. a gpg file, "test.gpg") there is an error "File mode specification error: (invalid-function (nil epa-file))". I've traced this bug to `prelude-editor.el` and it's caused by bc53a70. The defadvice assumes that auto-mode-alist is a list of conses, but in fact auto-mode-alist includes two kinds of entries:

- (REGEXP . FUNCTION)
- (REGEXP FUNCTION NON-NIL)

The defadvice will produce the error every time on the second type because it returns a list if it is found. Other examples of filetypes that are affected by this are .dz, .xz, .Z

I'm not sure I see the point of the defadvice, doesn't Emacs do this already?

**Comment by syohex** [comment]
I sent PR and it was merged at #969. Please check latest version.

**Comment by joonoro** [comment]
Yep, seems to work fine now. Closing.
