### ISSUE TITLE
helm stops working at M-x with 20160302.947

### ISSUE THREAD

**Issue by dl1ely** [bbatsov/prelude#978]
I don't know if this even belongs here, to be honest. Running GNU Emacs 25.0.90.3 (x86_64-w64-mingw32) of 2016-02-03 on Win10 with prelude. Did a package update this morning, bringing helm to 20160302.947. Now no command gets executed. I can match them fine, but pressing RET on a command just yields „Quit” in the mini buffer. 

Any pointers whether this might be prelude-related or solely in helm?

**Comment by dubnde** [comment]
ah! Thought I messed up my setup. I observe this as well after updating this morning.

**Comment by dl1ely** [comment]
@dubnde At least it seems to be reproducible. Still unclear if rooted in helm or if the update just breaks prelude-integration.

**Comment by aresaguilar** [comment]
Same happens here, with emacs 24.3.1. Helm does not work for commands (M-x) and kill-buffer (C-x k), it just shows 'Quit' in the minibuffer. It works for opening files though.

**Comment by syohex** [comment]
I think this issue was fixed by https://github.com/emacs-helm/helm/pull/1416. Please upgrade helm version and retry.

**Comment by dubnde** [comment]
Upgraded and can confirm fixed.
