### ISSUE TITLE
user-defined key is conflicted with Prelude Mode Keybinding

### ISSUE THREAD

**Issue by yu-yuxuan** [bbatsov/prelude#981]
In the personal folder, I add `(global-set-key "\C-cs" 'dictionary-lookup-definition)`. But since it is conflicted   with Prelude Mode Keybinding, it didn't work until I disable the Prelude-Mode. Is there any other way to cover this keybinding?

**Comment by cute-jumper** [comment]
I guess maybe you can define the key binding in the `prelude-mode-map`: `(define-key prelude-mode-map "\C-cs" 'dictionary-lookup-definition)`

**Comment by bbatsov** [comment]
Yep. I understand the current mappings might conflict with user keybindings, but I've defined them this way in the spirit of convenience and with the idea that people can simply override keys in the `prelude-mode-map`.

**Comment by bbatsov** [comment]
P.S. I should probably make the keymap prefix configurable.

**Comment by yu-yuxuan** [comment]
Thank you, it works
