### ISSUE TITLE
Documentation suggestion: 

### ISSUE THREAD

**Issue by derek-pappas** [bbatsov/prelude#988]
In the Fast forward section of the documentation perhaps a few details should be mentioned to the new Emacs prelude user:
1. If the user does not remove/move the ~/.emacs file the ~/.emacs.d/init.el file which initializes and loads Emacs prelude will not (?) be loaded and Emacs will start without prelude.

If you want to do a clean install of Emacs 24.5 =<; then you should remove the current version of emacs on your machine and mv your ~/.emacs file to ~/.emacs.bak.

`mv ~/.emacs ~/.emacs.bak`
1. Configure the ~/.emacs.d/prelude-modules.el by copying the necessary (require <module>)'s to the ~/.emacs.d/prelude-modules.el file.
2. Perhaps it might be a good idea to mention to the user how to do a clean install of Emacs on their platform.
   OSX example: Setting up emacs from scratch on OSX
# Save the old emacs configuration if relevant

`mv ~/.emacs ~/.emacs.bak
mv ~/.emacs.d ~/.emacs.d.bak
`

Reinstall/install Emacs: [http://www.wikemacs.org/wiki/Installing_Emacs_on_OS_X](url)
`brew update
sudo rm /usr/bin/emacs
sudo rm -rf /usr/share/emacs
brew install emacs --with-cocoa
`
1. Install Emacs prelude
   `curl -L https://git.io/epre | sh
   `

**Comment by bbatsov** [comment]
The install script actually preserves any old configuration if present. I'm always open to documentation improvements - PRs welcome. :-)

**Comment by derek-pappas** [comment]
I have been using emacs since 1992. But I do not have anywhere near the
level of expertise and understanding that you and the others that have
developed prelude. Good job!

Did you see my documentation suggestion for the installation steps in the
comments on the github site. I new to git. Used RCS, SCCS, svn, and many
others.

I am having issues with the Python setup. I must have missed something
during the setup. I am going to perhaps try reinstalling emacs prelude and
see if I am prompted for the Python virtualenv path.

Here are my key bindings. Rectangles and macros and replace are the main
things that I use. Perhaps I should add auto-indent-region... Perhaps
prelude should have some sort of default .emacs equivalent and keybindings
equivalent. If I am missing the point about the emacs prelude setup please
excused me. I have a lot on my plate right now.

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;; Set up the global keys

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;


(global-set-key [f1 ] 'indent-region           ) ;; search-forward-regexp

(global-set-key [f2 ] 'undo                    )

(global-set-key [f3 ] 'call-last-kbd-macro     )

(global-set-key [f4 ] 'start-kbd-macro         )

(global-set-key [f5 ] 'end-kbd-macro           )

(global-set-key [f6 ] 'clear-rectangle         )

(global-set-key [f7 ] 'delete-extract-rectangle)

(global-set-key [f8 ] 'kill-rectangle          )

(global-set-key [f9 ] 'string-rectangle        )

(global-set-key [f10] 'query-replace-regexp    )

(global-set-key [f11] 'yank-rectangle          )

(global-set-key [f12] 'goto-line               )


(global-set-key [insert] 'yank)


(global-set-key [remove] 'kill-region)

(global-set-key [select] 'set-mark-command)


(global-set-key [kp-f1] 'beginning-of-buffer)

(global-set-key [kp-f2] 'end-of-buffer)

(global-set-key [kp-f3] 'delete-other-windows)

(global-set-key [kp-f4] 'kill-line)


;;

;;visit-tags-table

;; tags-query-replace


(global-set-key [kp-0] 'overwrite-mode)

(global-set-key [kp-1] 'end-of-line)

;;;(global-set-key [kp-2] 'scroll-up)

(global-set-key [kp-2] 'backward-line)

(global-set-key [kp-3] 'end-of-buffer)

(global-set-key [kp-4] 'backward-word)

(global-set-key [kp-5] 'save-buffer)

(global-set-key [kp-6] 'forward-word)

(global-set-key [kp-7] 'beginning-of-line)

;;;(global-set-key [kp-8] 'scroll-down)

(global-set-key [kp-8] 'forward-line)

(global-set-key [kp-9] 'beginning-of-buffer)

(global-set-key [kp-subtract] 'kill-word)

(global-set-key [kp-separator] 'delete-char)

(global-set-key [kp-enter] 'save-buffer)

(global-set-key [kp-decimal] 'copy-region-as-kill)

(global-set-key [kp-period] 'copy-region-as-kill)



(global-set-key [?\C-f] 'forward-word)

(global-set-key [?\C-b] 'backward-word)

Derek Pappas

**Comment by derek-pappas** [comment]
Hi,

I like prelude and I have a suggestion and would like to know what you
think.

The following are the functions that over the last 25 years I have decided
are the ones I use the most in emacs.

1. Undo is much more useful as a function key

2. Macros are easy to create with the three function keys

3. Rectangles are easy to use when mapped to function keys

4. Query replace

(global-set-key [f1 ] 'indent-region           ) ;; search-forward-regexp

(global-set-key [f2 ] 'undo                    )

(global-set-key [f3 ] 'call-last-kbd-macro     )

(global-set-key [f4 ] 'start-kbd-macro         )

(global-set-key [f5 ] 'end-kbd-macro           )

(global-set-key [f6 ] 'clear-rectangle         )

(global-set-key [f7 ] 'delete-extract-rectangle)

(global-set-key [f8 ] 'kill-rectangle          )

(global-set-key [f9 ] 'string-rectangle        )

(global-set-key [f10] 'query-replace-regexp    )

(global-set-key [f11] 'yank-rectangle          )

(global-set-key [f12] 'goto-line               )

(global-set-key [kp-f1] 'beginning-of-buffer) ;; kp == escape

(global-set-key [kp-f2] 'end-of-buffer)

Thanks,

Derek




Derek Pappas
