### ISSUE TITLE
Use eldoc-mode in place of haskell-doc-mode

### ISSUE THREAD

**Issue by gracjan** [bbatsov/prelude#989]
In light of https://github.com/haskell/haskell-mode/issues/1138 please do not use `haskell-doc-mode`. It doesn't work anymore and `eldoc-mode` is much better serving its function.

The line to change is here: https://github.com/bbatsov/prelude/blob/1f3ddb638ccd5d714371f2bd794de25ca66fed64/modules/prelude-haskell.el#L42

Thanks.

**Comment by bbatsov** [comment]
Thanks for the heads up!
