### ISSUE TITLE
Missing replacement function from crux

### ISSUE THREAD

**Issue by wscisme** [bbatsov/prelude#993]
Missing 
crux-duplicate-current-line-or-region, and 
crux-duplicate-and-comment-current-line-or-region
(and maybe some other) from the crux package. 
Don't know if you want them also to be in crux or keep them back in prelude-core.

**Comment by bbatsov** [comment]
I think I was wondering if anyone thinks they are useful or not. I never really used them myself.

**Comment by sicenw** [comment]
Seems that I'm one of the guy that use this every day... Anyway it would be up to you, I can put these functions in my personal config.

**Comment by haishengwu-okta** [comment]
+0.9

**Comment by bbatsov** [comment]
Feel free to add them to crux then.
