### ISSUE TITLE
C-a broken in eshell

### ISSUE THREAD

**Issue by joonoro** [bbatsov/prelude#998]
In emacs -Q, doing C-a moves the cursor to the beginning of the prompt, in Prelude C-a moves it to the beginning of the line (wrong).

**Comment by bbatsov** [comment]
Guess this should be fixed in `crux`.

**Comment by gregory-nisbet** [comment]
The same problem exists in `ansi-term`, but for ansi-term `C-a` should just send `^A` to the inferior process.

**Comment by zhubenwuzui** [comment]
I have the same problom, help!

**Comment by hackrole** [comment]
I got the same problem. I disable the prelude-mode in eshell now.

**Comment by junnu-github** [comment]
Workaround : disabling the "C-a" of prelude minor mode map in eshell-mode

`(defun my-eshell-mode-hook ()
    (let ((oldmap (cdr (assoc 'prelude-mode minor-mode-map-alist)))
          (newmap (make-sparse-keymap)))
      (set-keymap-parent newmap oldmap)
      (define-key newmap (kbd "C-a") nil)
      (make-local-variable 'minor-mode-overriding-map-alist)
      (push '(prelude-mode . ,newmap) minor-mode-overriding-map-alist))
    )

(add-hook 'eshell-mode-hook 'my-eshell-mode-hook)`


[Reference/Source](http://emacsredux.com/blog/2013/09/25/removing-key-bindings-from-minor-mode-keymaps/)

**Comment by KarlFish** [comment]
I have a pull request that may solve both the ansi-term and eshell problems at the [crux repo](https://github.com/bbatsov/crux/pull/45).
